### ISSUE TITLE
Why is there no fuse.ENOTEMPTY?

### ISSUE THREAD

**Issue by ppanyukov** [hanwen/go-fuse#105]
In `Rmdir` do we want to return `ENOTEMPTY` if the directory is not empty? If so, no such const in this library. Is this an omission or I am missing something?

The current workaround is to do `return fuse.Status(syscall.ENOTEMPTY)` but it feels a bit wrong.

**Comment by hanwen** [comment]
the status codes are just syscall codes, but they're not exhautive. Your workaround is OK, but you could submit a PR to add ENOTEMPTY if it's bothersome to you.

**Comment by hanwen** [comment]
this is fixed in the v2 API, which uses syscall.Errno consistently as error code.
