### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by petr-tik** [hanwen/go-fuse#111]
Currently:
- Supports 3 interfaces for writing filesystems:
  - PathFileSystem: define filesystems in terms path names.

Should be: 
- Supports 3 interfaces for writing filesystems:
  - PathFileSystem: define filesystems in terms **of** path names.

Didn't feel big enough to open a PR

**Comment by hanwen** [comment]
I rewrote the README - https://review.gerrithub.io/c/hanwen/go-fuse/+/462699/1
