### ISSUE TITLE
[Request] New example for "Create" function

### ISSUE THREAD

**Issue by sarpk** [hanwen/go-fuse#113]
Hello,
In the `FileSytem` interface there is a function called `Create(name string, flags uint32, mode uint32, context *fuse.Context) (file nodefs.File, code fuse.Status)` however this function does not have any example in regards to how to use it. Is it possible for someone to add a simple example (such as creating a file)? I have tried the below in hello example:
```
func (me *HelloFs) Create(name string, flags uint32, mode uint32, context *fuse.Context) (file nodefs.File, code fuse.Status) {
	return nodefs.NewDataFile([]byte(name)), fuse.OK
}
```
It just freezes when I try to create a file, so I am guessing it's something very different...

**Comment by ahl** [comment]
You definitely don't want to call `Create()`. Take a look at these two files: example/memfs/main.go and fuse/nodefs/memnode.go.

You might also look here:
https://github.com/attic-labs/noms/blob/master/samples/go/nomsfs/nomsfs.go#L282
