### ISSUE TITLE
Doesn't work on freebsd

### ISSUE THREAD

**Issue by testhmaa** [hanwen/go-fuse#120]
Though fuse works fine on freebsd. however go-fuse fails to build on freebsd
```
 ./all.bash 
go test github.com/hanwen/go-fuse/fuse
# github.com/hanwen/go-fuse/fuse
../github.com/hanwen/go-fuse/fuse/types.go:369: undefined: Attr
FAIL    github.com/hanwen/go-fuse/fuse [build failed]
```
is freebsd platform supported ??

the first line here says, it is supported !!!
https://godoc.org/bazil.org/fuse

several parts of documentation say freebsd is supported..

**Comment by ahl** [comment]
That's a different project entirely. I don't know how this project compares to https://github.com/bazil/fuse, but unless there's some deeply compelling reason you might want to use the other project.

Adding FreeBSD support wouldn't be that hard, but it wouldn't be zero work.

**Comment by testhmaa** [comment]
My bad,  i messed it up.Sorry. i am closing it rightaway
