### ISSUE TITLE
Compilation failure (undefined: fuse.ENOATTR, undefined: setupUfs, undefined: setRecursiveWritable)

### ISSUE THREAD

**Issue by wschlich** [hanwen/go-fuse#127]
The current code fails to compile on my Gentoo Linux box with the following messages:
`cd /var/tmp/portage/dev-libs/go-fuse-9999/work/go-fuse-9999/src/github.com/hanwen/go-fuse/unionfs`
`/usr/lib/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/hanwen/go-fuse/unionfs.a -trimpath $WORK -p github.com/hanwen/go-fuse/unionfs -complete -buildid 604f8a0484fe2a7907183d22a3bc5624dc0babcc -D _/var/tmp/portage/dev-libs/go-fuse-9999/work/go-fuse-9999/src/github.com/hanwen/go-fuse/unionfs -I $WORK -pack ./autounion.go ./cachingfs.go ./create.go ./dircache.go ./timedcache.go ./unionfs.go ./unionfs_test_linux.go ./unionfs_xattr_test_linux.go`
`# github.com/hanwen/go-fuse/unionfs`
`src/github.com/hanwen/go-fuse/unionfs/autounion.go:300: undefined: fuse.ENOATTR`
`src/github.com/hanwen/go-fuse/unionfs/unionfs.go:711: undefined: fuse.ENOATTR`
`src/github.com/hanwen/go-fuse/unionfs/unionfs_test_linux.go:18: undefined: setupUfs`
`src/github.com/hanwen/go-fuse/unionfs/unionfs_test_linux.go:23: undefined: setRecursiveWritable`
What's wrong?

**Comment by hanwen** [comment]
what tooling are you using to compile this? What is your command line?

**Comment by gentoo-junkie** [comment]
I have a similar problem so I'll supply more details.  I didn't get the first two errors in autounion.go and unionfs.go, but got the same two in unionfs_test_linux.go...

`cd /tmp/portage/portage/dev-libs/go-fuse-9999/work/go-fuse-9999/src/github.com/hanwen/go-fuse/unionfs
/usr/lib/go/pkg/tool/linux_amd64/compile -o $WORK/github.com/hanwen/go-fuse/unionfs.a -trimpath $WORK -p github.com/hanwen/go-fuse/unionfs -complete -buildid 33ce89add17893807b746024e9b7da5defef35fe -D _/tmp/portage/portage/dev-libs/go-fuse-9999/work/go-fuse-9999/src/github.com/hanwen/go-fuse/unionfs -I $WORK -I /tmp/portage/portage/dev-libs/go-fuse-9999/work/go-fuse-9999/pkg/linux_amd64 -pack ./autounion.go ./cachingfs.go ./create.go ./dircache.go ./timedcache.go ./unionfs.go ./unionfs_test_linux.go ./unionfs_xattr_test_linux.go
# github.com/hanwen/go-fuse/unionfs
src/github.com/hanwen/go-fuse/unionfs/unionfs_test_linux.go:18: undefined: setupUfs
src/github.com/hanwen/go-fuse/unionfs/unionfs_test_linux.go:23: undefined: setRecursiveWritable
`

Those two functions are found in unionfs_test.go so it seems strange that file is not iin the compile line.

I used go version devel +38765eb Sun Sep 25 12:22:04 2016 +0000 linux/amd64
along with:

app-shells/bash:          4.3_p46-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.22.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
dev-util/cmake:           3.5.2-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.21.7::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo, 4.9.4::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.5::gentoo (virtual/os-headers)
sys-libs/glibc:           2.23-r2::gentoo

This command line is in the gentoo .ebuild pkg file:

`src_compile() {
        local d
#no examples right now
#    example/hello example/loopback example/zipfs \
#    example/multizip example/unionfs example/memfs \
#    example/autounionfs ; \
#or tests
#fuse/test
        for d in fuse fuse/pathfs zipfs unionfs; do
                go build -v -x -work ${GO_PN}/${d} || die
        done
}
`
Complete build log at [http://dpaste.com/0KT8N6T](url)

**Comment by wschlich** [comment]
Same here using

dev-lang/go-1.7.1

and

app-shells/bash:          4.3_p48::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.22.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
dev-util/ccache:          3.2.4::gentoo
dev-util/cmake:           3.5.2-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.21.7::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.7::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r4::gentoo

**Comment by wschlich** [comment]
@gentoo-junkie, @hanwen : Any idea why unionfs_test.go isn't being pulled in?

**Comment by hanwen** [comment]
looks like gentoo rules for compling go are broken. Please file a bug whomever is responsible for the gentoo rules.

**Comment by Reonaydo** [comment]
Golang prefer old system libraries located in /usr/lib/go/.. instead new from git repo.
emerge -C go-fuse && emerge go-fuse fix problem
