### ISSUE TITLE
Mount paths, other issues on darwin

### ISSUE THREAD

**Issue by keleher** [hanwen/go-fuse#128]
OSX 10.12 (sierra)

> const bin = "/Library/Filesystems/osxfusefs.fs/Support/mount_osxfusefs"

looks like it should be

> const bin = "/Library/Filesystems/osxfuse.fs/Contents/Resources/mount_osxfuse"

However, still doesn't mount:

> hub:~/go/src/github.com/hanwen/go-fuse/example/hello> go run main.go ~/space 
> 2016/09/15 15:50:22 Mount fail: init: 19=operation not supported by device
> exit status 1

**Comment by rprieto** [comment]
I have the same issue on **10.11 El capitan** and **Fuse for macOS 3.5.2**.

**Comment by hanwen** [comment]
There is another program next to the mount program that has to be run once
to setup the kernel module. Can you try that?

Op wo 5 okt. 2016 14:36 schreef Romain <notifications@github.com>:

**Comment by mikegray** [comment]
According to the release notes for FUSE for MacOS version 3.5.2 - "Let mount_osxfuse load the FUSE kernel extension - When mounting a FUSE volume, libosxfuse used to be responsible for loading the kernel extension by calling load_osxfuse. Starting with this release mount_osxfuse will call load_osxfuse. This allows us to further decouple libosxfuse from the FUSE kernel extension."

I was seeing the same mount failure as listed above. I corrected the path in my local code. I made sure the kernel module was setup and running.  Then the next problem I ran into it was "panic: darwin has no splice" from fuse/splice_darwin.go, called from opcode.go. Looks like the input.Minor >= 13 is now causing server.setSplice() to be called on darwin platform.

**Comment by hanwen** [comment]
the setSplice problem should be fixed in https://github.com/hanwen/go-fuse/commit/81de1746a0a3e8b66c5a0a4f76d71010fb3564fc

**Comment by mikegray** [comment]
Can you reopen this to also fix the bin file location for FUSE for MacOS version 3.5.2 mentioned at the top of this issue? Without that fix too, the setSplice problem never gets hit because mount for darwin can never succeed.

**Comment by hanwen** [comment]
I would be really glad if somebody could provide me a PR for this. I don't actually have an OSX device nearby, so it's really hard to test if my fixes make any sense.

**Comment by mikegray** [comment]
See #135.
