### ISSUE TITLE
About flush and close

### ISSUE THREAD

**Issue by allspace** [hanwen/go-fuse#129]
Regarding the comments below, how can I distinguish "real" "flush" call and "close" call?

    // Flush is called for close() call on a file descriptor. In
    // case of duplicated descriptor, it may be called more than
    // once for a file.
    Flush() fuse.Status

**Comment by hanwen** [comment]
the real problem is that there is no such thing. The correct solution is to flush all buffers on Flush, and use  Close in forget to release the resource.
