### ISSUE TITLE
Need to examine device number to determine if files are hard linked

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#130]
Currently pathfs in its `clientInodeMap` only looks at the inode number to determine if a file is a hard link to another, already-known file. This is, strictly speaking, incorrect because the other file may reside on a different device.

For example, if you loopback-mount "/" somewhere else, inode numbers from /sys, /proc etc may clash and pathfs will consider them hard-linked and may read from the wrong file.

**Comment by rfjakob** [comment]
I started working on this, but then found out that it's not a good idea to add a field to `struct Attr`: https://github.com/rfjakob/go-fuse/commit/b20b3d8270c5a8ddb7e3226bf1a1bb5838991919

**Comment by hanwen** [comment]
nodefs/pathfs are deprecated.
