### ISSUE TITLE
Why does not loopbackFile.Read write the result into buf?

### ISSUE THREAD

**Issue by chmduquesne** [hanwen/go-fuse#132]
I am referring to this line:

https://github.com/hanwen/go-fuse/blob/master/fuse/nodefs/files.go#L128

It seems like apart from its size, the input buffer is ignored and the result of the read is directly sent through the fuse wire protocol. Does it mean that buf is useless?

Is there a way to rewrite this function so that it make use of buf?

**Comment by hanwen** [comment]
for data coming out of a file, it's less work to leave the data in the kernel and use splice.

You could just use f.Read() on the passed-in buf.
