### ISSUE TITLE
Regression: xfstests generic/035 fails because Nlink is forced to 1

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#137]
This seems to have been introduced in 3e9dd8f9e17171580aa481e9bee415a8546535d7 and causes xfstests generic/035 to fail with this:

```
 QA output created by 035
 overwriting regular file:
+nlink is 1, should be 0
 overwriting directory:
```

I suggest a revert.

**Comment by rfjakob** [comment]
What this test does is
1) create two files, `a` and `b`
2) open `b`
3) rename `a` over `b`
4) fstat `b` and check nlink (should be zero)

**Comment by hanwen** [comment]
I don't think you could ever get that test to pass due to https://github.com/libfuse/libfuse/issues/62 - the kernel doesn't issue a FH for GetAttr calls.

**Comment by hanwen** [comment]
Correction: this test can pass if you build an in-memory node based FS. For loopback, you don't get FH, so there is no path to stat.

**Comment by rfjakob** [comment]
I see your point, and I also remember adding that comment in 8b95cbfda9742b2781cb8481fd04fa2101762529 .

However, xfstests generic/035 at the moment looks like this:
```
$ cat fuse-xfstests/results/generic/035.out.bad
QA output created by 035
overwriting regular file:
nlink is 1, should be 0
overwriting directory:
t_rename_overwrite: fstat(3): No such file or directory
```

And with 3e9dd8f9e17171580aa481e9bee415a8546535d7 reverted it looks like this:
```
$ cat fuse-xfstests/results//generic/035.out.bad
QA output created by 035
overwriting regular file:
overwriting directory:
t_rename_overwrite: fstat(3): No such file or directory
```

I'll have to check the xfstests code. Maybe it actually gets an error from the fstat but does not report it.

**Comment by rfjakob** [comment]
I'm not sure how, but it looks like the fstat succeeds: [code](https://github.com/rfjakob/fuse-xfstests/blob/gocryptfs-2018-08-18/src/t_rename_overwrite.c#L31)

I have added a debug printf [(commit)](https://github.com/rfjakob/fuse-xfstests/commit/18d8c59f3a4da81bbd00eabbed67e6d030823344), and the fstat result looks sane:
```
QA output created by 035
overwriting regular file:
res=0 dev=75 ino=9180181 mode=100644 nlink=0 uid=0
overwriting directory:
t_rename_overwrite: fstat(3): No such file or directory
res=-1 dev=140732372285592 ino=140076708261629 mode=4637360474 nlink=4294967295 uid=32614
```

**Comment by rfjakob** [comment]
Debug log:
```
rx 94: OPEN i5 {O_RDONLY,0x8000} # open file2
tx 94:     OK, {Fh 2 }
rx 96: RENAME i3 {i3} ["file1" "file2"] 12b
tx 96:     OK
rx 98: GETATTR i5 {Fh 0}
tx 98:     OK, {tA=1s {M0100644 SZ=0 L=0 0:0 B0*4096 i0:2756255 A 1551010887.001112 M 1551010887.001112 C 1551010887.002746}}
```
This works because of
```go
file = n.Inode().AnyFile()
```
https://github.com/hanwen/go-fuse/blob/fb9b7327a6ab6a80f4a61aab97f021ebcea25142/fuse/pathfs/pathfs.go#L591

**Comment by hanwen** [comment]
Jakob, is this an issue with the v2 API ? If not, I think we can close this.

**Comment by hanwen** [comment]
@rfjakob - paging jakob

**Comment by rfjakob** [comment]
Will retest.

**Comment by rfjakob** [comment]
No, the `nlink is 1, should be 0` is gone!
