### ISSUE TITLE
unionfs test race.

### ISSUE THREAD

**Issue by hanwen** [hanwen/go-fuse#138]
Read at 0x00c4204984b0 by goroutine 66:
  github.com/hanwen/go-fuse/unionfs.TestXAttrCaching()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/unionfs_xattr_test.go:120 +0x12a0
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:610 +0xc9

Previous write at 0x00c4204984b0 by goroutine 6:
  github.com/hanwen/go-fuse/unionfs.(*TestFS).GetXAttr()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/unionfs_xattr_test.go:35 +0x121
  github.com/hanwen/go-fuse/unionfs.getXAttr()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/cachingfs.go:71 +0x110
  github.com/hanwen/go-fuse/unionfs.NewCachingFileSystem.func4()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/cachingfs.go:102 +0x62
  github.com/hanwen/go-fuse/unionfs.(*TimedCache).GetFresh()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/timedcache.go:76 +0x5f
  github.com/hanwen/go-fuse/unionfs.(*TimedCache).Get()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/timedcache.go:55 +0x156
  github.com/hanwen/go-fuse/unionfs.(*cachingFileSystem).GetXAttr()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/cachingfs.go:127 +0xe7
  github.com/hanwen/go-fuse/unionfs.(*unionFS).GetXAttr()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/unionfs/unionfs.go:727 +0x13e
  github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).GetXAttr()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:393 +0xc3
  github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).GetXAttrData()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:402 +0xbb
  github.com/hanwen/go-fuse/fuse.doGetXAttr()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:219 +0x573
  github.com/hanwen/go-fuse/fuse.(*Server).handleRequest()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:398 +0x410
  github.com/hanwen/go-fuse/fuse.(*Server).loop()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x1d0

Goroutine 66 (running) created at:
  testing.(*T).Run()
      /usr/lib/google-golang/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/lib/google-golang/src/testing/testing.go:795 +0xb9
  testing.tRunner()
      /usr/lib/google-golang/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/lib/google-golang/src/testing/testing.go:801 +0x4ba
  testing.(*M).Run()
      /usr/lib/google-golang/src/testing/testing.go:745 +0x12f
  main.main()
      github.com/hanwen/go-fuse/unionfs/_test/_testmain.go:152 +0x1b8

Goroutine 6 (running) created at:
  github.com/hanwen/go-fuse/fuse.(*Server).readRequest()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x62e
  github.com/hanwen/go-fuse/fuse.(*Server).loop()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:358 +0x80
  github.com/hanwen/go-fuse/fuse.(*Server).Serve()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:325 +0x66

**Comment by jmhodges** [comment]
I fixed the first race in #157.

The race that fix reveals seems to be because the `mount` on a parent of a parent of a node (`p.parents[k].parent.mount`) is not always the same as `mount` on the current node. There seems to be only one case of this revealed in TestXAttrCaching and only when all the tests are run.

**Comment by jmhodges** [comment]
Yeah, I can get this to happen with any pair of tests. Even ones that do not fs work like `go test -race github.com/hanwen/go-fuse/unionfs -run '(TestXAttrCaching|TestFilePathHash)'

**Comment by hanwen** [comment]
I think this has been fixed by now. Please reopen if you see this again.

**Comment by jmhodges** [comment]
Thanks!
