### ISSUE TITLE
Read messages delivered out of order

### ISSUE THREAD

**Issue by ncw** [hanwen/go-fuse#140]
I'm finding that if I attempt to stream a big file (cat it to /dev/null) then the read messages are delivered out of order sometimes.

Here message 180 and 181 are delivered by the kernel almost simultaneously.  Unfortunately the read from 128k is delivered to the filesystem code before the read from 0k leading to needless seeking.  I'm attaching go-fuse to https transactions, so a seek is really expensive (~0.5 second) - I'd really like it if these messages were delivered in order.

```
2016/11/25 13:43:35 Dispatch 180: READ, NodeId: 46. data: {Fh 2 off 0 sz 131072  L 0 RDONLY,0x8000} 
2016/11/25 13:43:35 Dispatch 181: READ, NodeId: 46. data: {Fh 2 off 131072 sz 131072  L 0 RDONLY,0x8000} 
2016/11/25 13:43:35 big_file: ReadFileHandle.Read size 131072 offset 131072
2016/11/25 13:43:35 big_file: ReadFileHandle.seek from 0 to 131072 (io.Seeker)
2016/11/25 13:43:35 big_file: ReadFileHandle.Read OK
2016/11/25 13:43:35 Serialize 181: READ code: OK value:  131072 bytes data
2016/11/25 13:43:35 big_file: ReadFileHandle.Read size 131072 offset 0
2016/11/25 13:43:35 big_file: ReadFileHandle.seek from 262144 to 0 (io.Seeker)
2016/11/25 13:43:35 big_file: ReadFileHandle.Read OK
2016/11/25 13:43:35 Serialize 180: READ code: OK value:  131072 bytes data
```

The code which handles the read has locking so only one ever runs at once (as you can see from the above log) however as each message delivery is started in a go routine at very nearly the same time it is racy as to which one arrives first and I can't see a way of solving this with locking in the filesystem code.

The code is correct, it is just very inefficient!

Any ideas?  I tried patching the code to set `ms.singleReader` but that only made a bit less likely - it didn't fix the problem.

**Comment by hanwen** [comment]
the kernel can reorder reads as it sees fit. 

Ideas: 

* try is to read in 128k chunks. I think the kernel would hopefullly don't read ahead of you.
* keep track of the last read offset. If you can't read it efficiently, add a sleep to allow the out-of-order request to complete earlier. Bonus points for adding select wizardry to avoid sleeping the full sleep interval if the OOO request is done processing.

**Comment by ncw** [comment]
> the kernel can reorder reads as it sees fit.

It isn't the kernel re-ordering the messages in my example though, it is go-fuse.  You can see quite clearly that the messages arrive in order, but go-fuse dispatches them out of order due to some fluke of go-routine scheduling.

This problem exists even if I set the noseek flag, delivering the messages out of order here breaks the API.

I was thinking more on the line of having a per (nodeid, opcode) dispatch queue to make sure there is only ever one message outstanding per (nodeid, opcode) tuple.

> keep track of the last read offset. If you can't read it efficiently, add a sleep to allow the out-of-order request to complete earlier. 

Clever idea :-)

**Comment by hanwen** [comment]
the trace clearly shows that the kernel doesn't wait for the result of the first read to complete, so they happen simultaneously for all practical purposes. (the FUSE process is multithreaded, so the both reads can even happen on different CPUs.)

the queues you suggest are expensive, so I'd rather suggest to try something with delays.

**Comment by ncw** [comment]
I'll give it a go!

**Comment by rfjakob** [comment]
Sorry for resurrecting this old ticket, but disabling [FUSE_CAP_ASYNC_READ](https://github.com/libfuse/libfuse/blob/8c4d315108352f9cc2c0d141989b4c01faff8b9e/include/fuse_common.h#L141) may have just done the trick. Quoting:

```
/**
 * Indicates that the filesystem supports asynchronous read requests.
 *
 * If this capability is not requested/available, the kernel will
 * ensure that there is at most one pending read request per
 * file-handle at any time, and will attempt to order read requests by
 * increasing offset.
 *
 * This feature is enabled by default when supported by the kernel.
 */
#define FUSE_CAP_ASYNC_READ		(1 << 0)
```

gocryptfs has implemented read ordering using delays (option `-serialize_reads`), but this capability may allow to let the kernel handle the complexity instead. I'll test and send a PR.

**Comment by rfjakob** [comment]
Yes that works nicely. See https://github.com/hanwen/go-fuse/issues/395 .
