### ISSUE TITLE
Cannot run tests: no buildable Go source files

### ISSUE THREAD

**Issue by juliangilbey** [hanwen/go-fuse#144]
Hi Hanwen,

Running the following two commands gives an error:

erdos:/tmp/godir $ GOPATH=/tmp/godir go get github.com/hanwen/go-fuse
erdos:/tmp/godir $ GOPATH=/tmp/godir src/github.com/hanwen/go-fuse/all.bash
go build github.com/hanwen/go-fuse/fuse/test: no buildable Go source files in /tmp/godir/src/github.com/hanwen/go-fuse/fuse/test

I presume that this is ignorable?

**Comment by companycy** [comment]
I guess so. You can also tell bash to continue even there is error following below workaround.

$ git diff all.bash
diff --git a/all.bash b/all.bash
index b844afb..9cffe92 100755
--- a/all.bash
+++ b/all.bash
@@ -1,5 +1,5 @@
 #!/bin/sh
-set -eu
+set -u

**Comment by hanwen** [comment]
fixed in 0ad840cf1c835844c01474aba565475b03909a01
