### ISSUE TITLE
Does go-fuse have support for libfuse3?

### ISSUE THREAD

**Issue by chmduquesne** [hanwen/go-fuse#147]
libfuse3 has been out for about 10 days and is making it to my distrib. I wanted to know if that is going to be fully supported in the future.

Cheers!

**Comment by hanwen** [comment]
libfuse is the userspace library, which go-fuse does not use.

**Comment by chmduquesne** [comment]
I was more thinking of changes they made because of changes in the kernel module. From [libfuse/ChangeLog.rst](https://github.com/libfuse/libfuse/blob/085cbab117b72df8da113a46d9ec9ba64ca301c6/ChangeLog.rst):

> * FUSE filesystems are now responsible for unsetting the setuid/setgid flags when a file is written, truncated, or its owner changed. Previously, this was handled by the kernel but subject to race conditions.
