### ISSUE TITLE
Efficient directory listings

### ISSUE THREAD

**Issue by dsoprea** [hanwen/go-fuse#148]
The underlying `libfuse` implementation using a static function called `fuse_add_direntry_to_dh` to add one directory after another to a linked-list representing the contents of a directory: https://github.com/libfuse/libfuse/blob/ae49d8860d28d6630cb78b079067ee5611f97382/lib/fuse.c#L3274

This function is accessed indirectly via a callback that's provided as an argument to the `readdir` callback. What this looks like in the *hello* example: https://github.com/libfuse/libfuse/blob/7983414b33b43e76fc9766067b27060772150dbf/example/hello.c#L85

I'm implementing an FS on top of `PathFs`, but PathFs' interface only allows for an `OpenDir` method that returns all of the children in a big slice. Even if I was going to implement `FileSystem` directly, the directory-access-and-listing interfaces are such:

```go
OpenDir(input *OpenIn, out *OpenOut) (status Status)
ReadDir(input *ReadIn, out *DirEntryList) Status
ReadDirPlus(input *ReadIn, out *DirEntryList) Status
```

...where `DirEntryList` is still little more than one long byte-array. NOTE: Curiously, `ReadDir`/`ReadDirPlus` don't even appear to be called when doing an actual directory listing at the command-line; I added logging statements to `rawBridge`, a type-alias of `FileSystemConnector`, and only `OpenDir` appeared to activate when I did directory listings.

The Unix filesystem interface is iterative. Isn't there someway to avoid returning a massive block of data (which could technically be billions of files, where millions of files aren't uncommon in large data-collection operations/projects) through the FUSE interface? Consider also that you're building a slice on the Go side that remains allocated while *libfuse* is populating those entries into its own data-structures?

It makes me cringe.

**Comment by hanwen** [comment]
the reason to build a slice beforehand is because it makes it easier to provide correct semantics when there are seeks on the directory fd.

Do you have any benchmarking results that indicate that the overhead you observe affects real world timings?  

If you have millions of directory entries, your best bet is to simply not return anything from readdir, and access files through lookup alone.

**Comment by dsoprea** [comment]
It's not a speed thing, other than the time it'd take to build the slice of
course (especially if you're having to do other operations to collect the
attributes for each).

Yes. That's a great point.


On Fri, Mar 10, 2017 at 10:23 AM, Han-Wen Nienhuys <notifications@github.com
