### ISSUE TITLE
Slow/ breaks on large files?

### ISSUE THREAD

**Issue by sb10** [hanwen/go-fuse#152]
Hi,

I'm trying to implement a remote file system with local caching, so I'm using `nodefs.NewLoopbackFile(osFile)` in my `Open()` func. However, this is exceptionally slow, and also breaks at the end. I added some debug prints to the loopbackFile methods; it works perfectly for a reading a small file:

    download took 80.364986ms
    in Read
    got lock, have buffer size 4096
    got readresultfd
    unlocked
    in Flush
    Flush got lock
    flush duped
    flush unlocked
    flush closed, returning
    in Release
    release got lock
    2017/03/29 08:16:48 reading small file took 81.56844ms in total
    release closed file
    release unlocked
    [was able to unmount without error]

But with a 1GB file:

    download took 5.789764271s
    in Read
    got lock, have buffer size 32768
    got readresultfd
    unlocked
    skipped 1 read debugs for buf size 32768
    skipped 1 read debugs for buf size 32768
    in Read
    got lock, have buffer size 131072
    got readresultfd
    unlocked
    in Read
    got lock, have buffer size 65536
    got readresultfd
    unlocked
    skipped 1 read debugs for buf size 65536
    in Read
    got lock, have buffer size 131072
    got readresultfd
    unlocked
    skipped 8190 read debugs for buf size 131072
    in Read
    got lock, have buffer size 32768
    got readresultfd
    unlocked
    skipped 1 read debugs for buf size 32768
    in Read
    got lock, have buffer size 4096
    got readresultfd
    unlocked
    2017/03/29 08:19:43 reading big file took 2m54.75161396s in total
    in Flush
    Flush got lock
    flush duped
    flush unlocked
    flush closed, returning
    in Flush
    Flush got lock
    flush duped
    flush unlocked
    flush closed, returning
    in Flush
    Flush got lock
    flush duped
    flush unlocked
    flush closed, returning
    in Flush
    Flush got lock
    flush duped
    flush unlocked
    flush closed, returning
    in Flush
    Flush got lock
    flush duped
    flush unlocked
    flush closed, returning
    2017/03/29 08:19:43 could not unmount: /bin/fusermount: failed to unmount /tmp/mnt/test: Device or resource busy
     (code exit status 1)

So it takes nearly 3m, and then fails to unmount, apparently with no call to Release().

Without digging further, I wasn't able to see what determines those buffer sizes. Would it go faster with much bigger buffers? Is there any way to bypass a lot of the busy work to get it go closer to native disk speed, since the file being read is actually on the local disk?

**Comment by hanwen** [comment]
the max buffer is hardcoded to 128kb, however, I think your test program is reading in smaller chunks and forgetting to close the file (hence the failed unmount).

**Comment by sb10** [comment]
You're right that I forgot to close, and that fixes that hang. However, using my same read buffer size (10000 bytes) and code, I can read my remote file in 6s using an alternate go fuse library.

Can you suggest some code that can read 1GB from a `nodefs.NewLoopbackFile(osFile)` in a few seconds?

**Comment by rfjakob** [comment]
Have you tested the loopback example?
https://github.com/hanwen/go-fuse/tree/master/example/loopback

**Comment by rfjakob** [comment]
(gocryptfs developer here. I've never had performance problems with go-fuse.)

**Comment by sb10** [comment]
Yes, sorry, I don't know where I went wrong, but after starting from scratch based on the loopback example it's fast.
