### ISSUE TITLE
pathfs.FileSystem Link() method not called

### ISSUE THREAD

**Issue by sb10** [hanwen/go-fuse#158]
I have implemented a pathfs.FileSystem and so have methods GetAttr(), Open(), Create(), Link() etc.
Everything works fine except for when I:

    os.Link("/mount/point/source", "/mount/point/dest")

This fails with a "function not implemented". If I put debug print statements at the start of the above methods, the only thing that gets called is GetAttr() for source and dest. Why wouldn't my Link() method or anything else be called?

**Comment by hanwen** [comment]
enable the debug prints, and see if there is a LINK operatioin issued by the kernel. If not, I suspect you may be trying to link directories (which the VFS doesnt allow)

**Comment by rfjakob** [comment]
@sb10 I'd suggest to compare what the [loopback example](
https://github.com/hanwen/go-fuse/blob/master/example/loopback/main.go) is doing. Everything works there, it even passes xfstests (mostly).

**Comment by sb10** [comment]
I'm trying to link a file, not a directory. Symlink on the same path works, and reading the data from the same path works. My code is like:

	opts := &nodefs.Options{
		NegativeTimeout: time.Second,
		AttrTimeout:     time.Second,
		EntryTimeout:    time.Second,
		Owner: &fuse.Owner{
			Uid: uid,
			Gid: gid,
		},
		Debug: true,
	}
	pathFsOpts := &pathfs.PathNodeFsOptions{ClientInodes: false}
	pathFs := pathfs.NewPathNodeFs(fs, pathFsOpts)
	conn := nodefs.NewFileSystemConnector(pathFs.Root(), opts)
	mOpts := &fuse.MountOptions{
		AllowOther:           true,
		FsName:               "MinFys",
		Name:                 "MinFys",
		RememberInodes:       true,
		DisableXAttrs:        true,
		IgnoreSecurityLabels: true,
		Debug:                true,
	}
	server, err := fuse.NewServer(conn.RawFS(), fs.mountPoint, mOpts)
	if err != nil {
		return
	}

	server.Serve()

...

    func (fs *MinFys) GetAttr(name string, context *fuse.Context) (attr *fuse.Attr, status fuse.Status) {
        fmt.Printf("\n\nGot GetAttr(%s, ...)\n", name)
        //...
    }

    func (fs *MinFys) Link(source string, dest string, context *fuse.Context) (code fuse.Status) {
    	fmt.Printf("\n\nGot Link(%s, %s, ...)\n", source, dest)
    	localPathSource := fs.writeRemote.getLocalPath(fs.writeRemote.getRemotePath(source))
    	localPathDest := fs.writeRemote.getLocalPath(fs.writeRemote.getRemotePath(dest))
    	return fuse.ToStatus(os.Link(localPathSource, localPathDest))
    }

...

    source := mountPoint + "/numalphanum.txt"
	dest := mountPoint + "/link.hard"

	_, err := ioutil.ReadFile(path)
	if err != nil {
		fmt.Printf("\n\nReadFile error: %s\n", err)
	}
	So(err, ShouldBeNil)

	err = os.Link(source, dest)
	if err != nil {
		fmt.Printf("\n\nLink error: %s\n", err)
	}

This produces:

    2017/05/06 11:13:42 Dispatch 2: LOOKUP, NodeId: 1. names: [numalphanum.txt] 16 bytes


    Got GetAttr(numalphanum.txt, ...)
    2017/05/06 11:13:42 Serialize 2: LOOKUP code: OK value: {NodeId: 3 Generation=0 EntryValid=1.000 AttrValid=1.000 Attr={M0100600 SZ=47 L=1 1000:1000 B0*0 i0:3 A 1491214703.000000000 M 1491214703.000000000 C 1491214703.000000000}}
    2017/05/06 11:13:42 Dispatch 3: OPEN, NodeId: 3. data: {O_RDONLY,0x8000}
    2017/05/06 11:13:42 Serialize 3: OPEN code: OK value: {Fh 2 }
    2017/05/06 11:13:42 Dispatch 4: READ, NodeId: 3. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000}
    2017/05/06 11:13:42 Serialize 4: READ code: OK value:  4096 bytes data (fd data)

    2017/05/06 11:13:42 Dispatch 5: GETATTR, NodeId: 3. data: {Fh 2}
    2017/05/06 11:13:42 Serialize 5: GETATTR code: OK value: {A1.000000000 {M0100664 SZ=47 L=1 1000:1000 B8*4096 i0:257487 A 1494069222.407124154 M 1494069222.407124154 C 1494069222.407124154}}
    2017/05/06 11:13:42 Dispatch 6: READ, NodeId: 3. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000}
    2017/05/06 11:13:42 Serialize 6: READ code: OK value:  4096 bytes data (fd data)

    2017/05/06 11:13:42 Dispatch 7: FLUSH, NodeId: 3. data: {Fh 2}
    2017/05/06 11:13:42 Serialize 7: FLUSH code: OK value:
    2017/05/06 11:13:42 Dispatch 8: RELEASE, NodeId: 3. data: {Fh 2 0x8000  L0}
    2017/05/06 11:13:42 Serialize 8: RELEASE code: OK value:
    2017/05/06 11:13:42 Dispatch 9: LOOKUP, NodeId: 1. names: [link.hard] 10 bytes


    Got GetAttr(link.hard, ...)
    2017/05/06 11:13:42 Serialize 9: LOOKUP code: OK value: {NodeId: 0 Generation=0 EntryValid=1.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
    2017/05/06 11:13:42 Dispatch 10: LINK, NodeId: 1. data: {Oldnodeid: 3} names: [link.hard] 10 bytes
    2017/05/06 11:13:42 Serialize 10: LINK code: 38=function not implemented value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}


    Link error: link /tmp/wr_testing_minfys335007708/mount/numalphanum.txt /tmp/wr_testing_minfys335007708/mount/link.hard: function not implemented

What am I doing wrong?

**Comment by rfjakob** [comment]
What does the 
```
os.Link(localPathSource, localPathDest)
```
call return?

**Comment by rfjakob** [comment]
Whoah, this also fails in the loopback example, something must have broken in the library:

```
~/go/src/github.com/hanwen/go-fuse/example/loopback/b$ ln l1 l2
15:01:20.520181 Dispatch 185: GETATTR, NodeId: 1. data: {Fh 0} 
15:01:20.520225 Serialize 185: GETATTR code: OK value: {A1.000000000 {M040775 SZ=4096 L=2 1026:1026 B8*4096 i0:8782514 A 1493752029.689212769 M 1494075595.754520571 C 1494075595.754520571}}
15:01:20.521183 Dispatch 186: LOOKUP, NodeId: 1. names: [l2] 3 bytes
15:01:20.521219 Serialize 186: LOOKUP code: OK value: {NodeId: 0 Generation=0 EntryValid=1.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
15:01:20.521256 Dispatch 187: LOOKUP, NodeId: 1. names: [l1] 3 bytes
15:01:20.521279 Serialize 187: LOOKUP code: OK value: {NodeId: 3 Generation=1 EntryValid=1.000 AttrValid=1.000 Attr={M0100664 SZ=0 L=1 1026:1026 B0*4096 i0:8782516 A 1494075595.756089966 M 1494075595.756089966 C 1494075595.754520571}}
15:01:20.521307 Dispatch 188: LINK, NodeId: 1. data: {Oldnodeid: 3} names: [l2] 3 bytes
15:01:20.521319 Serialize 188: LINK code: 38=function not implemented value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
ln: failed to create hard link 'l2' => 'l1': Function not implemented
```
Investigating.

**Comment by rfjakob** [comment]
Oh, sorry, my bad, everything is fine. You just have to enable hard links using `./loopback -l`.

@sb10 This is how you do it, set `ClientInodes` to true: [loopback/main.go#L94](https://github.com/hanwen/go-fuse/blob/5404bf0e372d1676fdf039b170556850e6a571df/example/loopback/main.go#L94)

**Comment by sb10** [comment]
Thanks, sorry for missing that option. Out of interest, why is it an option? That is, under what circumstances would I need to make ClientInodes false?

**Comment by rfjakob** [comment]
With clientinodes=false, the library manages inode numbers for you (it automatically assigns unique numbers from a counter). If you don't need hard links, this can simplify things a bit.

**Comment by sb10** [comment]
What is happening when I make clientinodes=true then? Because from a quick test everything still seems to work, but I'm not doing anything with inode numbers myself.

**Comment by rfjakob** [comment]
What do you get when run run "ls "li"?

**Comment by rfjakob** [comment]
Sorry, "ls -li".

**Comment by sb10** [comment]
Extending my little test to:

    source := mountPoint + "/numalphanum.txt"
    dest := mountPoint + "/link.hard"

    _, err := ioutil.ReadFile(source)
    if err != nil {
        fmt.Printf("\n\nReadFile error: %s\n", err)
    }

    err = os.Link(source, dest)
    if err != nil {
        fmt.Printf("\n\nLink error: %s\n", err)
    }

    cmd := exec.Command("ls", "-li", mountPoint)
    out, err := cmd.CombinedOutput()
    if err != nil {
        fmt.Printf("\n\nls error: %s\n", err)
    }
    fmt.Printf("\n\n%s\n", out)

With `&pathfs.PathNodeFsOptions{ClientInodes: true}` I get:

    2017/05/08 08:26:13 Dispatch 2: LOOKUP, NodeId: 1. names: [numalphanum.txt] 16 bytes


    Got GetAttr(numalphanum.txt, ...)
    2017/05/08 08:26:13 Serialize 2: LOOKUP code: OK value: {NodeId: 3 Generation=0 EntryValid=1.000 AttrValid=1.000 Attr={M0100600 SZ=47 L=1 1000:1000 B0*0 i0:3 A 1491214703.000000000 M 1491214703.000000000 C 1491214703.000000000}}
    2017/05/08 08:26:13 Dispatch 3: OPEN, NodeId: 3. data: {O_RDONLY,0x8000}
    2017/05/08 08:26:13 Serialize 3: OPEN code: OK value: {Fh 2 }
    2017/05/08 08:26:13 Dispatch 4: READ, NodeId: 3. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000}
    2017/05/08 08:26:13 Serialize 4: READ code: OK value:  4096 bytes data (fd data)

    2017/05/08 08:26:13 Dispatch 5: GETATTR, NodeId: 3. data: {Fh 2}
    2017/05/08 08:26:13 Serialize 5: GETATTR code: OK value: {A1.000000000 {M0100664 SZ=47 L=1 1000:1000 B8*4096 i0:257487 A 1494231973.666548452 M 1494231973.666548452 C 1494231973.666548452}}
    2017/05/08 08:26:13 Dispatch 6: READ, NodeId: 3. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000}
    2017/05/08 08:26:13 Serialize 6: READ code: OK value:  4096 bytes data (fd data)

    2017/05/08 08:26:13 Dispatch 7: FLUSH, NodeId: 3. data: {Fh 2}
    2017/05/08 08:26:13 Serialize 7: FLUSH code: OK value:
    2017/05/08 08:26:13 Dispatch 8: RELEASE, NodeId: 3. data: {Fh 2 0x8000  L0}
    2017/05/08 08:26:13 Serialize 8: RELEASE code: OK value:
    2017/05/08 08:26:13 Dispatch 9: LOOKUP, NodeId: 1. names: [link.hard] 10 bytes


    Got GetAttr(link.hard, ...)
    2017/05/08 08:26:13 Serialize 9: LOOKUP code: OK value: {NodeId: 0 Generation=0 EntryValid=1.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
    2017/05/08 08:26:13 Dispatch 10: LINK, NodeId: 1. data: {Oldnodeid: 3} names: [link.hard] 10 bytes


    Got Link(numalphanum.txt, link.hard, ...)


    Got GetAttr(link.hard, ...)
    2017/05/08 08:26:13 Serialize 10: LINK code: 2=no such file or directory value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}


    Link error: link /tmp/wr_testing_minfys878292252/mount/numalphanum.txt /tmp/wr_testing_minfys878292252/mount/link.hard: no such file or directory
    2017/05/08 08:26:13 Dispatch 11: GETATTR, NodeId: 1. data: {Fh 0}


    Got GetAttr(, ...)
    2017/05/08 08:26:13 Serialize 11: GETATTR code: OK value: {A1.000000000 {M040700 SZ=4096 L=1 1000:1000 B0*0 i0:1 A 1494231973.000000000 M 1494231973.000000000 C 1494231973.000000000}}
    2017/05/08 08:26:13 Dispatch 12: GETXATTR, NodeId: 1. data: {sz 255} names: [security.selinux] 17 bytes
    2017/05/08 08:26:13 Serialize 12: GETXATTR code: 38=function not implemented value:
    2017/05/08 08:26:13 Dispatch 13: OPENDIR, NodeId: 1.
    2017/05/08 08:26:13 Serialize 13: OPENDIR code: OK value: {Fh 2 }
    2017/05/08 08:26:13 Dispatch 14: READDIRPLUS, NodeId: 1. data: {Fh 2 off 0 sz 4096  L 0 NONBLOCK,DIRECTORY,0x8000}


    Got GetAttr(100k.lines, ...)


    Got GetAttr(1G.file, ...)


    Got GetAttr(numalphanum.txt, ...)


    Got GetAttr(emptyDir, ...)


    Got GetAttr(sub, ...)
    2017/05/08 08:26:13 Serialize 14: READDIRPLUS code: OK value:  1136 bytes data

    2017/05/08 08:26:13 Dispatch 15: READDIRPLUS, NodeId: 1. data: {Fh 2 off 7 sz 4096  L 0 DIRECTORY,NONBLOCK,0x8000}
    2017/05/08 08:26:13 Serialize 15: READDIRPLUS code: OK value:
    2017/05/08 08:26:13 Dispatch 16: RELEASEDIR, NodeId: 1. data: {Fh 2 NONBLOCK,DIRECTORY,0x8000  L0}
    2017/05/08 08:26:13 Serialize 16: RELEASEDIR code: OK value:


    total 0
    4 -rw------- 1 ubuntu ubuntu     700000 Apr  3 19:51 100k.lines
    5 -rw------- 1 ubuntu ubuntu 1073741824 Apr  5 10:21 1G.file
    6 drwx------ 0 ubuntu ubuntu       4096 May  8 08:26 emptyDir
    3 -rw------- 1 ubuntu ubuntu         47 Apr  3 10:18 numalphanum.txt
    7 drwx------ 0 ubuntu ubuntu       4096 May  8 08:26 sub

ie. the `ls` works fine. (The "not found" error for Link() is expected, since I didn't actually implement my Link() method properly yet, the main thing is my Link() method actually got called, which is good.)

My OpenDir() permanently caches a mapping from file paths to their fuse.Attr, and things like GetAttr() return the Attr from my map. I don't deal in inode numbers. Am I doing something totally crazy? You can see my whole implementation (minus my dev changes related to Link()) here: https://github.com/VertebrateResequencing/wr/blob/develop/minfys/filesystem.go
Can I achieve the same in a more "proper" (uses less memory?) way using other go-fuse methods?

**Comment by rfjakob** [comment]
Looks like go-fuse sets an inode number if you leave it at zero: [fsconnector.go#L99](https://github.com/hanwen/go-fuse/blob/11be620b1524e0c7a2d37a1f7c81b49b34d1eb06/fuse/nodefs/fsconnector.go#L99). Note that this number can change at any time as files fall out of the kernel cache. If you don't want to manage persistent inode numbers I would recommend to disable ClientInodes.

**Comment by sb10** [comment]
Will I actually be affected by the inode number for a file changing? As long as my own code isn't doing anything with inode numbers, I should be fine?
