### ISSUE TITLE
MAC issues, fixes

### ISSUE THREAD

**Issue by anonopete** [hanwen/go-fuse#16]
I was able to install go and go-fuse w/ no issues on my linux box, but ran into some issues on my darwin 10.8 machine.  The fuse build errors are the following:

splice_darwin.go:9: undefined: Write 
splice_darwin.go:11: *ReadResultFd is not a type 
mount_darwin.go:124: cannot use nil as type int in return argument
mount_darwin.go:126: cannot use fd (type C.int) as type int in return argument

I followed the instructions here (https://bitbucket.org/oniony/tmsu/issue/59/solving-mac-compilation-errors-but-there) and the build and install works fine, as does go test in the fuse directory.

However, when trying to run the hello world fs, I get this cryptic comment:
go build
main.go:11:2: found packages pathfs (api.go) and fuse (loopback_darwin.go) in /Users/keleher/go/src/github.com/hanwen/go-fuse/fuse/pathfs

Hmm... turns out lookback_darwin.go has package 'fuse'. Chaning this to 'pathfs', I now get:

../../fuse/nodefs/files.go:95: cannot use loopbackFile literal (type *loopbackFile) as type File in return argument:
	*loopbackFile does not implement File (missing Allocate method)
../../fuse/nodefs/fsops.go:126: input.NodeId undefined (type *fuse.GetAttrIn has no field or method NodeId)
../../fuse/nodefs/fsops.go:136: input.Context undefined (type *fuse.GetAttrIn has no field or method Context)
../../fuse/nodefs/fsops.go:141: input.NodeId undefined (type *fuse.GetAttrIn has no field or method NodeId)

The first error appears to be because allocate() is only implemented for linux (in files_linux.go). Not sure of the others.

Thanks,
pete

**Comment by patrickxb** [comment]
@DanielHeath my pull request https://github.com/hanwen/go-fuse/pull/35 in combination with go1.4 fixes the problem you are experiencing.

**Comment by hanwen** [comment]
closing this. Please open new issue if any other issues surface.
