### ISSUE TITLE
PAGESIZE is fixed at 4096, needs to be dynamically determined

### ISSUE THREAD

**Issue by juliangilbey** [hanwen/go-fuse#160]
Dear Hanwen,

Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864007 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863994 which describe this error: there are many archs on which the pagesize is not 4096.  I don't know whether go-fuse will fail if the page size is not 4096 for any other reason than the panic in the misc.go init() function, so I daren't try to fix this myself.

Thanks!

**Comment by rfjakob** [comment]
gocryptfs does not run on arm64 because of this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849662

**Comment by juliangilbey** [comment]
Thanks!
