### ISSUE TITLE
Provide a release

### ISSUE THREAD

**Issue by misery** [hanwen/go-fuse#161]
I like to add a package of gocryptfs to AlpineLinux. (https://github.com/alpinelinux/aports/pull/1533)

Mostly all linux distributions uses separate packages for the dependencies instead of rust/go package manager. It would be necessary to have a release for "go-fuse" to build a package from it so the gocryptfs package could depend on it.

Is it possible to officially release a version of go-fuse?

**Comment by hanwen** [comment]
what to you constitutes "a release"?

**Comment by rfjakob** [comment]
I think a git tag should be all that's needed.

Would also allow me to drop some "git rev-parse" ugliness from gocryptfs' build.bash and use plain "git describe".

**Comment by misery** [comment]
A tag would be enough.

**Comment by hanwen** [comment]
Tagged https://github.com/hanwen/go-fuse/releases/tag/v20170619
