### ISSUE TITLE
Asynchronous API

### ISSUE THREAD

**Issue by boramalper** [hanwen/go-fuse#162]
Hi! libfuse [offers a "low-level" (inode-based) asynchronous API](https://libfuse.github.io/doxygen/index.html) and I wonder if go-fuse also offers a similar functionality? It would be great if it's high-level **and** asynchronous, but asynchrony comes first in any case. Thanks!

**Comment by hanwen** [comment]
there is an inode based api at https://github.com/hanwen/go-fuse/tree/master/fuse/nodefs
and https://github.com/hanwen/go-fuse/tree/master/fuse

I'm not completely sure what you mean with asynchronous, and why it matters to you.

**Comment by rfjakob** [comment]
I think "asynchronous" means this:

> responses must be sent explicitly using a separate set of API functions.

and returning from your handler function does not send anything to the kernel.

**Comment by boramalper** [comment]
@rfjakob is right. It matters to me because before certain operations, I want to create a pop-up and ask for user's explicit permission.

**Comment by hanwen** [comment]
I don't understand why you'd need an asynchronous API. The kernel interface itself is synchronous: it sends out a request and then the kernel waits for the FS to say something back.

Also, in general, libraries in Go have a synchronous model as well.

**Comment by boramalper** [comment]
By "kernel interface" do you mean the fuse module or the file-system related system calls? In either case, libfuse library offers an asynchronous interface through callbacks and explicit reply functions and I wondered if something akin possible in go-fuse.

Why not use the C library then you might ask, but the issue is, some arguments of the callback will be invalid after callback returns and to I need to save that arguments somewhere to process the request later on, and as C lacks any reflection capabilities that might have made deep copying those variables easier, I need to get involved in many many nasty details. I thought using Go might help, and saw your library and that is all.

**Comment by rfjakob** [comment]
Hmm, won't it send multiple requests concurrently *without* waiting for
reply?

On Jun 25, 2017 2:49 PM, "Han-Wen Nienhuys" <notifications@github.com>
wrote:

I don't understand why you'd need an asynchronous API. The kernel interface
itself is synchronous: it sends out a request and then the kernel waits for
the FS to say something back.

Also, in general, libraries in Go have a synchronous model as well.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/hanwen/go-fuse/issues/162#issuecomment-310900825>, or mute
the thread

**Comment by hanwen** [comment]
correct, the kernel sends multiple requests in parallel,  and this translates into multiple calls in to the API on separate goroutines. The kernel waits on the specific request to answer back, which is the return value of the API calls in go-fuse. If you want to do return to the kernel and do something els,e you can spawn a goroutine.
