### ISSUE TITLE
splice: TestCopyFile fails with go1.9

### ISSUE THREAD

**Issue by hyangah** [hanwen/go-fuse#164]
Stuck or timed out after https://golang.org/cl/36800 os: use poller for file I/O

<pre>

$ go test -timeout=1m github.com/hanwen/go-fuse/splice
panic: test timed out after 1m0s

goroutine 7 [running]:
testing.startAlarm.func1()
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:1029 +0xf9
created by time.goFunc
	/usr/local/google/home/hakim/golang/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42008c4e0, 0x54a18b, 0xc, 0x552020, 0x462776)
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:702 +0x309
testing.runTests.func1(0xc42008c4e0)
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:888 +0x67
testing.tRunner(0xc42008c4e0, 0xc42004be10)
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:659 +0x98
testing.runTests(0xc42000ad20, 0x5ebf40, 0x3, 0x3, 0x521b40)
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:886 +0x2c1
testing.(*M).Run(0xc42004bf20, 0x0)
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:828 +0xfc
main.main()
	github.com/hanwen/go-fuse/splice/_test/_testmain.go:50 +0xdb

goroutine 6 [syscall]:
syscall.Syscall(0x0, 0x8, 0x60e8c0, 0x8000, 0x0, 0x0, 0xc420050c00)
	/usr/local/google/home/hakim/golang/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0x60e8c0, 0x8000, 0x8000, 0x72, 0x0, 0x0)
	/usr/local/google/home/hakim/golang/go/src/syscall/zsyscall_linux_amd64.go:756 +0x55
syscall.Read(0x8, 0x60e8c0, 0x8000, 0x8000, 0x430866, 0xc420001200, 0x200000003)
	/usr/local/google/home/hakim/golang/go/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc420016b90, 0x60e8c0, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/google/home/hakim/golang/go/src/internal/poll/fd_unix.go:109 +0x115
os.(*File).read(0xc42000c0e0, 0x60e8c0, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/google/home/hakim/golang/go/src/os/file_unix.go:203 +0x4e
os.(*File).Read(0xc42000c0e0, 0x60e8c0, 0x8000, 0x8000, 0x0, 0x5, 0x0)
	/usr/local/google/home/hakim/golang/go/src/os/file.go:101 +0x77
github.com/hanwen/go-fuse/splice.DiscardAll(0x5d8540, 0xc42000c0e0)
	/usr/local/google/home/hakim/go/src/github.com/hanwen/go-fuse/splice/pool.go:101 +0x4f
github.com/hanwen/go-fuse/splice.(*pairPool).done(0xc420012990, 0xc42000ae20)
	/usr/local/google/home/hakim/go/src/github.com/hanwen/go-fuse/splice/pool.go:109 +0x3e
github.com/hanwen/go-fuse/splice.CopyFds(0xc42000c0d8, 0xc42000c0d0, 0xc42000c0d8, 0x1ed)
	/usr/local/google/home/hakim/go/src/github.com/hanwen/go-fuse/splice/copy.go:61 +0x152
github.com/hanwen/go-fuse/splice.CopyFile(0xc42000ada0, 0x15, 0xc42000ad40, 0x15, 0x1ed, 0x0, 0x0)
	/usr/local/google/home/hakim/go/src/github.com/hanwen/go-fuse/splice/copy.go:53 +0x10f
github.com/hanwen/go-fuse/splice.TestCopyFile(0xc42008c5b0)
	/usr/local/google/home/hakim/go/src/github.com/hanwen/go-fuse/splice/copy_test.go:26 +0x1c3
testing.tRunner(0xc42008c5b0, 0x552020)
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:659 +0x98
created by testing.(*T).Run
	/usr/local/google/home/hakim/golang/go/src/testing/testing.go:701 +0x2df
FAIL	github.com/hanwen/go-fuse/splice	60.035s

</pre>

**Comment by hanwen** [comment]
yeah, Heschi bugged me about it already. Let me just disable this.

**Comment by hanwen** [comment]
this is not the end of the story though, I am now seeing hangs that I don't understand in the fuse tests (fuse/test/)

**Comment by DsXack** [comment]
I'm sorry, I found #183

**Comment by DsXack** [comment]
I see https://github.com/golang/go/issues/21014 but go-fuse don't work with go1.10.2 for me

**Comment by rfjakob** [comment]
Works fine with here:

    gocryptfs v1.4.4-39-g44caf21; go-fuse v20170619-35-gb16719c; 2018-05-22 go1.10.2

That is, it passes the gocryptfs test suite and all kinds of stress tests.
