### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by hanwen** [hanwen/go-fuse#166]
==================
WARNING: DATA RACE
Write at 0x00c4200d0060 by goroutine 10:
  runtime.mapdelete()
      /home/hanwen/sdk/go1.9beta2/src/runtime/hashmap.go:635 +0x0
  github.com/hanwen/go-fuse/fuse/nodefs.(*Inode).rmChild()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/nodefs/inode.go:214 +0x17d
  github.com/hanwen/go-fuse/fuse/nodefs.(*FileSystemConnector).forgetUpdate()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsconnector.go:157 +0x4fb
  github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Forget()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:128 +0x4c
  github.com/hanwen/go-fuse/fuse.doForget()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:250 +0x109
  github.com/hanwen/go-fuse/fuse.(*Server).handleRequest()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:400 +0x3c5
  github.com/hanwen/go-fuse/fuse.(*Server).loop()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x1ba

Previous read at 0x00c4200d0060 by goroutine 9:
  runtime.mapiterinit()
      /home/hanwen/sdk/go1.9beta2/src/runtime/hashmap.go:709 +0x0
  github.com/hanwen/go-fuse/fuse/nodefs.(*Inode).Parent()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/nodefs/inode.go:97 +0xc0
  github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).GetPath()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:285 +0x151
  github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).GetAttr()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:594 +0x6b
  github.com/hanwen/go-fuse/fuse/nodefs.(*FileSystemConnector).internalLookup()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:92 +0xcd
  github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Lookup()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:107 +0x103
  github.com/hanwen/go-fuse/fuse.doLookup()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:285 +0x102
  github.com/hanwen/go-fuse/fuse.(*Server).handleRequest()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:400 +0x3c5
  github.com/hanwen/go-fuse/fuse.(*Server).loop()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0x1ba

Goroutine 10 (running) created at:
  github.com/hanwen/go-fuse/fuse.(*Server).readRequest()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x4a0
  github.com/hanwen/go-fuse/fuse.(*Server).loop()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:358 +0x78
  github.com/hanwen/go-fuse/fuse.(*Server).Serve()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:325 +0x66

Goroutine 9 (running) created at:
  github.com/hanwen/go-fuse/fuse.(*Server).readRequest()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x4a0
  github.com/hanwen/go-fuse/fuse.(*Server).loop()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:358 +0x78
  github.com/hanwen/go-fuse/fuse.(*Server).Serve()
      /home/hanwen/go/src/github.com/hanwen/go-fuse/fuse/server.go:325 +0x66
==================

**Comment by rfjakob** [comment]
I'm working on this. Unfortunately, the trivial fix (see below) causes deadlocks.
```
diff --git a/fuse/nodefs/inode.go b/fuse/nodefs/inode.go
index 032e157..fee8cc4 100644
--- a/fuse/nodefs/inode.go
+++ b/fuse/nodefs/inode.go
@@ -94,6 +94,8 @@ func (n *Inode) Parent() (parent *Inode, name string) {
        if n.mountPoint != nil {
                return nil, ""
        }
+       n.mount.treeLock.Lock()
+       defer n.mount.treeLock.Unlock()
        for k := range n.parents {
                return k.parent, k.name
        }
```
