### ISSUE TITLE
It will not build on OSX Sierra

### ISSUE THREAD

**Issue by kuking** [hanwen/go-fuse#169]
I'm trying to build it on OSX Sierra but it fails with the following error message:
```
$ ./all.bash
# github.com/hanwen/go-fuse/fuse
fuse/server.go:608: undefined: syscall.Creat
fuse/server.go:612: undefined: unix.PollFd
fuse/server.go:619: undefined: unix.Poll
```
It looks like some bindings are outdated. -- but not very sure, I will investigate further.

#### Environment
* Fuse for macOS Version 3.6.0
```
$ uname -a
Darwin host.local 16.6.0 Darwin Kernel Version 16.6.0; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
$ go version
go version go1.8.3 darwin/amd64
```

Apologies if this is a duplicated or a non-issue, I tried to find a duplicated issue or documentation but I couldn't. -- Thanks!

**Comment by kuking** [comment]
Hi, it produces the same error message with latest unstable:
```
$ go version
go version go1.9beta2 darwin/amd64
```

**Comment by hanwen** [comment]
https://github.com/hanwen/go-fuse/commit/b4cc1627b15503e91be5602dc30f06108b7ea169

**Comment by kuking** [comment]
Hey! Thank you! It works! 👍
