### ISSUE TITLE
darwin: server.go:608: undefined: syscall.Creat

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#172]
Looks like https://github.com/hanwen/go-fuse/commit/4f10e248ebabd3cdf9c0aa3ae58fd15235f82a79 breaks on darwin:

https://travis-ci.org/rfjakob/gocryptfs/jobs/254027058#L542
```
+GOOS=darwin
+GOARCH=amd64
+go build -tags without_openssl
# github.com/hanwen/go-fuse/fuse
../../hanwen/go-fuse/fuse/server.go:608: undefined: syscall.Creat
../../hanwen/go-fuse/fuse/server.go:612: undefined: unix.PollFd
../../hanwen/go-fuse/fuse/server.go:619: undefined: unix.Poll
```

**Comment by hanwen** [comment]
https://github.com/hanwen/go-fuse/commit/b4cc1627b15503e91be5602dc30f06108b7ea169
