### ISSUE TITLE
Data race during Unmount()

### ISSUE THREAD

**Issue by sb10** [hanwen/go-fuse#174]
In tests of my own software that uses go-fuse, I end up mounting and then immediately unmounting. With race detection on, I sometimes get something like:

    WARNING: DATA RACE
    Write at 0x00c4200a4990 by goroutine 7:
      internal/race.Write()
          /home/ubuntu/go/src/internal/race/race.go:41 +0x38
      sync.(*WaitGroup).Wait()
          /home/ubuntu/go/src/sync/waitgroup.go:129 +0x14b
      github.com/hanwen/go-fuse/fuse.(*Server).Unmount()
          /home/ubuntu/work/src/github.com/hanwen/go-fuse/fuse/server.go:113 +0x124
     [...]

    Previous read at 0x00c4200a4990 by goroutine 58:
      internal/race.Read()
          /home/ubuntu/go/src/internal/race/race.go:37 +0x38
      sync.(*WaitGroup).Add()
          /home/ubuntu/go/src/sync/waitgroup.go:71 +0x26b
      github.com/hanwen/go-fuse/fuse.(*Server).Serve()
          /home/ubuntu/work/src/github.com/hanwen/go-fuse/fuse/server.go:324 +0x53

    [...]

**Comment by hanwen** [comment]
are you using WaitMount before you do Unmount?

**Comment by sb10** [comment]
Ah, no, I wasn't aware of that. Using it seems to have fixed the problem. Thanks!
