### ISSUE TITLE
getdents: d_ino field not populated

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#175]
At the moment, the d_ino field of getdents(2) is always set to `FUSE_UNKNOWN_INO = 4294967295`. This breaks `find -inum`.

In a loopback mount:
```
$ find . -inum 8654086
(returns empty)
$ ls -li
total 0
8654086 -rw-rw-r--. 1 jakob jakob 0 27. Jul 23:23 a
[...]
```
Let's look at what getdents returns:
```
$ strace -e getdents -v ls
getdents(3, [
{d_ino=4294967295, d_off=1, d_reclen=24, d_name="b", d_type=DT_REG},
{d_ino=4294967295, d_off=2, d_reclen=24, d_name="a", d_type=DT_REG},
{d_ino=4294967295, d_off=3, d_reclen=24, d_name="c", d_type=DT_REG},
{d_ino=4294967295, d_off=4, d_reclen=24, d_name=".", d_type=DT_DIR},
{d_ino=4294967295, d_off=5, d_reclen=24, d_name="..", d_type=DT_DIR}], 32768) = 120
getdents(3, [], 32768)                  = 0
a  b  c
```
find uses the bogous d_ino field from getdents() to avoid a stat() call.

**Comment by hanwen** [comment]
tricky: should these be the inode numbers that we return as handls for the kernel (probably: no, because we can never make the lookup semantics work). Then the inodes should be some other number, provided by the user filesystem.

**Comment by rfjakob** [comment]
I'd suggest extending [`struct DirEntry`](https://github.com/hanwen/go-fuse/blob/master/fuse/direntry.go#L20) with an `Ino` field that allows `ClientInodes = true` filesystems to set an inode number in OpenDir.

With `ClientInodes = false`, I would just keep things as-is for now. These filesystem probably care less about POSIX compliance.

**Comment by rfjakob** [comment]
Don't know yet how to do this without breaking all existing users, though.

**Comment by hanwen** [comment]
ClientInodes is a property of the path filesystem. It would be best to put this in nodefs instead.
