### ISSUE TITLE
Equivalent of WaitMount for Unmount()?

### ISSUE THREAD

**Issue by sb10** [hanwen/go-fuse#176]
On NFS, if I Unmount() and then immediately try and remove associated directories (a sister cache directory of the mount point, not even the mount point itself), it fails because of "device or resource busy".

I suppose that the server is holding on to some file handles I opened up in there, even though I tried to close everything.

    <-time.After(2 * time.Second)

Is needed after calling Unmount() before I can remove the directories successfully.

Is there a way of knowing when Unmount() has really finished and the server has closed all open file handles?

And on a related note, is there a way that if some external process opens a file in a mount point but never closes it, can we have Unmount() just force close everything?

**Comment by hanwen** [comment]
if you FS server closes files on other filesystems on FORGET, then this cannot be avoided. FORGET has no return value, so you cannot synchronize on it. You could build synchronization infrastructure that is specific to your filesystem.

FWIW, the current code already does sleeps, see https://github.com/hanwen/go-fuse/blob/ae405425e7b7380972c2e486a82ea1b3e81b0861/fuse/server.go#L103 

re force closing: you can use umount -f if you are root, or killl the FUSE mount by writing into the abort control file under /sys/fs/fuse/ . unfortunately, i don't know of a way to find which connection to use.
