### ISSUE TITLE
First Write operation works, but none thereafter

### ISSUE THREAD

**Issue by leonj1** [hanwen/go-fuse#179]
Using this library I have been able to implement "read" operations.
Now I'm interested in implementing "write" ops, but managed to only get an initial write to take affect. Any subsequent writes to either the same or new file fails with "no such file exists" error.

The client I am using for testing is below. 
The `open()` call only works the first time; fails subsequent times.

I have verified that `unregisterFileHandle()` does remove a reference to the file being worked on. While I do believe there is state being kept by go-fuse, at least this one gets cleaned up.

I do not know what else to check or implement to ensure subsequent `Write()` calls work.
I am unable to find an example fusefs where `Write` is implemented, so if one exists please point me to that source. Any help would be appreciated.

```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>

int main (int argc, char *argv[])
{
    int fd1;
    char buf[128];
    fd1 = open(argv[1], O_CREAT | O_WRONLY);
    if (fd1 == -1) {
        perror(argv[1]);
        return EXIT_FAILURE;
    }

    /* Human entering input */
    scanf("%[^\n]s",buf);

    write(fd1, buf, strlen(buf));

    close(fd1);

    return 0;
}
```

**Comment by rfjakob** [comment]
Take a look at the [loopback example](https://github.com/hanwen/go-fuse/tree/master/example/loopback).

The `Open()` impemetation is here: https://github.com/hanwen/go-fuse/blob/master/fuse/pathfs/loopback.go#L120

and the `Write()` implementation is here: https://github.com/hanwen/go-fuse/blob/master/fuse/nodefs/files.go#L79

**Comment by leonj1** [comment]
Yea, saw that, but that did not help since the problem remains.
When debug is enabled, the initial successful `open()`  returns
The `CREAT` operation being invoked. Great, this is what I want.
```
17:59:24.019524 Serialize 4: LOOKUP code: 2=no such file or directory value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000
17:59:24.019625 Dispatch 5: CREATE, NodeId: 4. data: {0100240 [WRONLY,CREAT,0x8000] (022)} names: [55a.txt] 8 bytes
```

Subsequent write operation fails.
As you can see from the debug output, CREAT was never attempted.
What do I need to do to declare the intent to allow other writes?
```
17:59:52.675412 Serialize 14: LOOKUP code: 2=no such file or directory value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
17:59:52.675738 Dispatch 15: MKNOD, NodeId: 4. data: {0104140 (022), 0} names: [55b.txt] 8 bytes
```

**Comment by hanwen** [comment]
for understanding what is happening you shoudl provide the complete debug log. The snippets you post leave out the most important information.

**Comment by leonj1** [comment]
Preface
I have added lots more print debugging to the code to see the calls being made. Any log line with a time is "native", all others are the ones I added. Indentation was used to help determine what code my file system implemented (left most), while anything indented is native to go-fuse. I've not removed any debug print statements, just additions. The debug print statements are the common `fmt.printf("parent.functionName: arg1 %v arg2: %v", arg1, arg2)` format.

Here is the "happy" case, where everything works as expected. Highlighted is the code path where it finds the parent directory and then decides to "CREAT" the file:
https://gist.github.com/leonj1/ad6080602d0138c9cc727031839e1c9d#file-fuse_write_working-txt-L52-L103

Here is the log for the "not working" case. I've highlighted similar lines for comparison. It also shows the file was not found, yet I cannot determine why it did not invoke a "CREAT" operation like the first attempt. As you can see, the file names are *intentionally* different, to eliminate the chance of conflicting filenames. Also, notice how multiple attempts are made to find the file. I cannot explain why this is happening since I've not added any such logic.
https://gist.github.com/leonj1/2c48719021e154bec5fc13c472aa1432#file-fuse_write_not_working-txt-L52-L78

**Comment by hanwen** [comment]
1st trace:

20:46:56.671057 Serialize 5: CREATE code: 38=function not implemented value: {NodeId: 0 Generation=0 {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000} &{0 0 0}}

you are saying that the FS doesnt implement CREATE, so the kernel tries MKNOD. Then your code manages to produce 

 20:47:03.980531 Serialize 15: MKNOD code: 2=no such file or directory value:

I would suggest implementing the Create call.

**Comment by leonj1** [comment]
Ok. More digging and debugging, have found that in the "happy" case the opcode headers in `server.handleRequest` begins with "1" for LOOKUP, then upon not finding the file calls "35" to CREAT.
```
			.............................
			IN server.handleRequest Beginning. Request Header: &{53 1 4 4 {{0 0} 32374} 0}
goroutine 1 [running]:
runtime/debug.Stack(0x39, 0xc42006dc30, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc4200b6540, 0xc4200d4900, 0xc4200d4900)
	/home/jleon43/go/src/ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse/server.go:387 +0x17c
ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc4200b6540, 0x0)
	/home/jleon43/go/src/ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse/server.go:378 +0x175
ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).Serve(0xc4200b6540)
	/home/jleon43/go/src/ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse/server.go:326 +0x59
main.main()
	/home/jleon43/go/src/ds-webhdfs/webhdfs.go:63 +0x98e
22:06:34.403332 Dispatch 4: LOOKUP, NodeId: 4. names: [09909aaa.txt] 13 bytes
			IN server.handleRequest req.Status is OK
			[UTIL] Returning GetCurrentNameNode
GetAttr
Filesystem info for tmp/jose/09909aaa.txt: {0 0 0 0  0 0    0 0 }
GetAttr FileStatus: {0 0 0 0  0 0    0 0 }
Does not exist (leaving): tmp/jose/09909aaa.txt
			 *** In fsops.Lookup code Not OK (leaving) Name: 09909aaa.txt ***
			IN server.handleRequest Performing Write. Request Header: &{53 1 4 4 {{0 0} 32374} 0}
22:06:34.409158 Serialize 4: LOOKUP code: 2=no such file or directory value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
			IN server.handleRequest Leaving: OK
			.............................
			IN server.handleRequest Beginning. Request Header: &{69 35 5 4 {{0 0} 32374} 0}
```

The same exact log block in the "not working" case starts with an opcode of "1" LOOKUP, then immediately calls "8" MKNOD. But there's no hint on why that happened?
```
			IN server.handleRequest Beginning. Request Header: &{53 1 14 4 {{0 0} 32420} 0}
goroutine 1 [running]:
runtime/debug.Stack(0x39, 0xc42006dc30, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc4200b6540, 0xc4200d4900, 0xc4200d4900)
	/home/jleon43/go/src/ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse/server.go:387 +0x17c
ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc4200b6540, 0x0)
	/home/jleon43/go/src/ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse/server.go:378 +0x175
ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).Serve(0xc4200b6540)
	/home/jleon43/go/src/ds-webhdfs/vendor/github.com/hanwen/go-fuse/fuse/server.go:326 +0x59
main.main()
	/home/jleon43/go/src/ds-webhdfs/webhdfs.go:63 +0x98e
22:06:52.148702 Dispatch 14: LOOKUP, NodeId: 4. names: [09909bbb.txt] 13 bytes
			IN server.handleRequest req.Status is OK
			[UTIL] Returning GetCurrentNameNode
GetAttr
Filesystem info for tmp/jose/09909bbb.txt: {0 0 0 0  0 0    0 0 }
GetAttr FileStatus: {0 0 0 0  0 0    0 0 }
Does not exist (leaving): tmp/jose/09909bbb.txt
			 *** In fsops.Lookup code Not OK (leaving) Name: 09909bbb.txt ***
			IN server.handleRequest Performing Write. Request Header: &{53 1 14 4 {{0 0} 32420} 0}
22:06:52.155126 Serialize 14: LOOKUP code: 2=no such file or directory value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
			IN server.handleRequest Leaving: OK
			.............................
			IN server.handleRequest Beginning. Request Header: &{69 8 15 4 {{0 0} 32420} 0}
```

Anywhere else I should be looking to help determine what's causing that decision?

**Comment by rfjakob** [comment]
When the kernel gets "function not implemented" for CREATE, it remembers that, and won't call CREATE again

**Comment by leonj1** [comment]
I forgot to mention that I did implement Create after your recommendation, yet the problem remains.
For debugging, I added debug statements to `fuse.handleRequest` like so:
```
func (ms *Server) handleRequest(req *request) Status {
	fmt.Println("\t\t\t.............................")
	req.parse()
	fmt.Printf("\t\t\tIN server.handleRequest Beginning. Request Header: %v\n", req.inHeader)
	debug.PrintStack()

	if req.handler == nil {
		req.status = ENOSYS
	}

	if req.status.Ok() && ms.opts.Debug {
		log.Println(req.InputDebug())
	}

	if req.inHeader.NodeId == pollHackInode {
		fmt.Println("\t\t\tIN server.handleRequest Not using pollHackInode")
		// We want to avoid switching off features through our
		// poll hack, so don't use ENOSYS
		req.status = EIO
		if req.inHeader.Opcode == _OP_POLL {
			req.status = ENOSYS
		}
	} else if req.inHeader.NodeId == FUSE_ROOT_ID && len(req.filenames) > 0 && req.filenames[0] == pollHackName {
		fmt.Println("\t\t\tIN server.handleRequest Doing pollHackLookup")
		doPollHackLookup(ms, req)
	} else if req.status.Ok() && req.handler.Func == nil {
		log.Printf("Unimplemented opcode %v", operationName(req.inHeader.Opcode))
		fmt.Printf("\t\t\tIN server.handleRequest Unimplemented opcode: %v\n", operationName(req.inHeader.Opcode))
		req.status = ENOSYS
	} else if req.status.Ok() {
		fmt.Println("\t\t\tIN server.handleRequest req.Status is OK")
		req.handler.Func(ms, req)
	}

	fmt.Printf("\t\t\tIN server.handleRequest Performing Write. Request Header: %v\n", req.inHeader)
	errNo := ms.write(req)
	if errNo != 0 {
		log.Printf("writer: Write/Writev failed, err: %v. opcode: %v",
			errNo, operationName(req.inHeader.Opcode))
	}
	ms.returnRequest(req)
	fmt.Printf("\t\t\tIN server.handleRequest Leaving: %v\n", errNo)
	return Status(errNo)
}
```
In the "happy" case you can see `Line 56: Request Header: &{53 1 4 4 {{0 0} 34439} 0}` has an opcode of "1" (LOOKUP), then the next `Line 80: handleRequest` invocation has an opcode of "35" (CREAT)
https://gist.github.com/leonj1/1610e7b9a9fca600229643c84fadb632#file-fuse_write_working2-txt-L55-L80

In the "not working" case `Line 56` starts off with LOOKUP, but the next invocation becomes opcode "8" (MKNOD).
https://gist.github.com/leonj1/646c93ba02177e7aefc5ab73273e50ed#file-fuse_not_working2-txt-L55-L80

So, now that Create is implemented, any idea what would cause the difference in code path being executed?

**Comment by leonj1** [comment]
Ah. Wait. I still see "function not implemented" within my filesystem's Create.
I thought I did implement this. Fixing to see if it resolves the problem.

**Comment by leonj1** [comment]
Confirmed. I had not implemented `Create`. Just updating this as a confirmation that was the problem. Thanks!
