### ISSUE TITLE
Mounted fuse directory shows question marks

### ISSUE THREAD

**Issue by leonj1** [hanwen/go-fuse#189]
As root, mounted fuse directory shows questions marks like so:
```
d????????? ? ? ? ?            ? foobar
```
From what I've read its because the directory is missing the 'execute' bit.
But I cannot find a way to do that.

Attempts:
1. added "user_allow_other" in /etc/fuse/conf
2. enabled -allow-other=true in for fuse.MountOptions. This should pass "-o allow_other" to fuse.
3. added "umask=0002" to Options in fuse.MountOptions based on last comment in: https://github.com/s3fs-fuse/s3fs-fuse/issues/189

Not really sure what else to try.
The goal is for the mounted fuse directory to appear like a normal directory because libraries, such as Python's "os.path.isdir" return false currently. Also, when attempting to pass this fuse mount to a Docker container using "-v" Docker attempts to create the directory; presumably because it also believes its not a directory.

Any help or guidance is appreciated.

```
	jediFs := webhdfs.GetJediFileSystem(*user, *keytabFile, *krbPrinciple, *mountpoint, *namenodes, *protocol, *uriBase, util)

	opts := &nodefs.Options{
		// These options are to be compatible with libfuse defaults,
		// making benchmarking easier.
		NegativeTimeout: time.Second,
		AttrTimeout:     time.Second,
		EntryTimeout:    time.Second,
	}

	pathFsOpts := &pathfs.PathNodeFsOptions{ClientInodes: *enableLinks}
	pathFs := pathfs.NewPathNodeFs(jediFs, pathFsOpts)
	conn := nodefs.NewFileSystemConnector(pathFs.Root(), opts)
	mOpts := &fuse.MountOptions{
		AllowOther: *other,
		Name:       "jediFs",
		FsName:     "bach_webhdfs",
		Debug:      *debug,
		Options:    []string{"umask=0002"},
	}
	state, err := fuse.NewServer(conn.RawFS(), *mountpoint, mOpts)
```

**Comment by hanwen** [comment]
Usually is when you have readdir but forgot to implement lookup/getatr

Op 10 okt. 2017 17:32 schreef "Jose M Leon" <notifications@github.com>:

**Comment by leonj1** [comment]
hmm... I don't have Readdir or Lookup implemented, same as the loopback example. 
I do have GetAttr() else nothing works =)
I've done my best to follow the loopback example in the project which does show the proper attributes of the mount directory (no question marks).
Question marks still appear.

**Comment by rfjakob** [comment]
The question marks mean that the stat() call that ls launches fails.

What does the go-fuse debug log say?

**Comment by leonj1** [comment]
Apologies, the problem was when my driver implementation was handling root "/" it was failing.
Once I got that resolved the mount appears correctly.
