### ISSUE TITLE
How to handle writing large files?

### ISSUE THREAD

**Issue by leonj1** [hanwen/go-fuse#190]
After adding some logging, I can see the `Write(data []byte, off int64)` function is being called consecutively in 65K blocks.
The fuse driver I'm writing uses an http client and I need to upload a file (method=PUT).
But the receiving web server, which I do not control, does not append each PUT.
Using `curl` a single PUT is performed with all bytes of the file.
Is there a way I can perform a single Write call for "large" files - apparently files 65K of size or larger?

**Comment by hanwen** [comment]
no. It's a limitation of the FUSE protocol.

**Comment by rfjakob** [comment]
You can increase the limit to 128kiB ([example](https://github.com/rfjakob/gocryptfs/blob/64e5906ffa1f225a51048b3d0ac6b1a09e2ca170/mount.go#L255)) but that's it. Larger blocks are not allowed by the Linux kernel.

You will have to store all writes in your filesystem and upload when the file is closed.

**Comment by leonj1** [comment]
Interesting. Thanks!
