### ISSUE TITLE
splice: build failure on macOS: p.discard undefined

### ISSUE THREAD

**Issue by glycerine** [hanwen/go-fuse#198]
macOS 10.12.5 sierra, go1.9.1. at 14c301560741efa61ca3a9e7695bc8cdf5002fad

build of master branch fails; p.discard is implemented on linux only, in splice/pair_linux.go.
~~~
jaten@Jasons-MacBook-Pro ~/go/src/github.com/hanwen/go-fuse/splice (master) $ go install
# github.com/hanwen/go-fuse/splice
./pool.go:96:3: p.discard undefined (type *Pair has no field or method discard)
./splice.go:76:9: undefined: syscall.Pipe2
jaten@Jasons-MacBook-Pro ~/go/src/github.com/hanwen/go-fuse/splice (master) $
~~~

**Comment by hanwen** [comment]
why should it pass? splice is a linux-specific construct. Why are you compiling this on darwin?

**Comment by glycerine** [comment]
> why should it pass? splice is a linux-specific construct. Why are you compiling this on darwin?

why so hostile?  Just trying to help.

The README.md file says the project should work, somewhat, on OSX, and requests that any issues by filed if it does not.

>macOS Support
>go-fuse works somewhat on OSX. Known limitations:
> ...
>Tests are expected to pass; report any failure as a bug!
 -- from https://github.com/hanwen/go-fuse/blob/master/README.md

Here is what happens when one tries to install on OSX:
~~~
$ go get -t -u -v github.com/hanwen/go-fuse/...
github.com/hanwen/go-fuse (download)
github.com/hanwen/go-fuse/benchmark/bulkstat
github.com/hanwen/go-fuse/fuse
github.com/hanwen/go-fuse/example/benchmark-read-throughput
github.com/hanwen/go-fuse/fuse/test
github.com/hanwen/go-fuse/internal/testutil
github.com/hanwen/go-fuse/splice
# github.com/hanwen/go-fuse/splice
go/src/github.com/hanwen/go-fuse/splice/pool.go:96:3: p.discard undefined (type *Pair has no field or method discard)
go/src/github.com/hanwen/go-fuse/splice/splice.go:76:9: undefined: syscall.Pipe2
github.com/hanwen/go-fuse/fuse/nodefs
github.com/hanwen/go-fuse/fuse/pathfs
github.com/hanwen/go-fuse/example/memfs
github.com/hanwen/go-fuse/benchmark
github.com/hanwen/go-fuse/example/hello
github.com/hanwen/go-fuse/unionfs
github.com/hanwen/go-fuse/example/loopback
github.com/hanwen/go-fuse/zipfs
github.com/hanwen/go-fuse/example/statfs
github.com/hanwen/go-fuse/example/multizip
github.com/hanwen/go-fuse/example/zipfs
github.com/hanwen/go-fuse/example/autounionfs
github.com/hanwen/go-fuse/example/unionfs
$
~~~

...displaying an error on install, which would be reasonably equivalent to "does not pass test zero".

If splice is not intended to compile on OSX, then it would be reasonable to build-tag it out so that `go install` doesn't try.  There's no mention of this special case in the README, so a comment there would be helpful.

**Comment by rfjakob** [comment]
Hmm, as far as I can see, `splice` is only imported here

https://github.com/hanwen/go-fuse/blob/00d53976f3f71ce3d8327b3af528ce3d4700620e/fuse/splice_linux.go#L11

where the whole file is build-tagged for linux only. So this should not cause trouble when compiling an actual app. `splice` will not be compiled on MacOS.

Then the other thing is that a Go library usually is not installed by itself. On Linux:
```
$ go get github.com/hanwen/go-fuse
can't load package: package github.com/hanwen/go-fuse: no Go files in
/home/jakob/go/src/github.com/hanwen/go-fuse
```
I guess this error is why you used `go get github.com/hanwen/go-fuse/...` with the three dots on the end?

**Comment by lad** [comment]
This still fails on OSX, is there an alternate install method we should use?

```
$ env|grep GO
GOPATH=/some/path/go
$ go get github.com/hanwen/go-fuse
package github.com/hanwen/go-fuse: no Go files in /some/path/go/src/github.com/hanwen/go-fuse
$ go get github.com/hanwen/go-fuse/...
# github.com/hanwen/go-fuse/splice
github.com/hanwen/go-fuse/splice/pool.go:96:3: p.discard undefined (type *Pair has no field or method discard)
github.com/hanwen/go-fuse/splice/splice.go:76:9: undefined: syscall.Pipe2
```

```
$ go version
go version go1.9.3 darwin/amd64
$ sw_vers -productVersion
10.13.5
```

**Comment by hanwen** [comment]
if anything, ```go get github.com/hanwen/go-fuse/fs``` is probably the current recommended install procedure.
