### ISSUE TITLE
Writes _using dd_ seem to cause EIOs at times, not sure why; it seems OS X only(?)

### ISSUE THREAD

**Issue by fingon** [hanwen/go-fuse#201]
I am writing a filesystem using raw API ( https://github.com/fingon/go-tfhfs ). For most part, it seems to work. E.g. rsync/cp of large amount of data to it works fine.

With dd, however, after first block is written by dd (e.g. megabyte in this case), subsequent one fails with EIO error. My code is not returning EIO, and as far as debug log of fuse also is concerned, there is simply few 64kb WRITEs and then FLUSH and RELEASE of the file. There does not seem to be subsequent failing WRITEs in go-fuse code at all.

I am not sure if this problem is actually in osxfuse and not this project at all, but please let me know if there is some way I could determine where to look next.

This does not seem to reproduce on my Debian 9 box; on OS X 10.13.2 with 3.7.1 OSXFUSE it happens always.

**command**
dd "if=/tmp/perf/size/install-highsierra-app.tgz" of=/tmp/x/bar.dat bs=1024000

**sudo fs_usage -w dd output**
14:05:41.772433  open              F=3        (R_____)  private/tmp/perf/size/install-highsierra-app.tgz                                                                                                                      0.000026   dd.9640084
14:05:41.772436  fstat64           F=3                                                                                                                                                                                        0.000002   dd.9640084
14:05:41.772437  lseek             F=3    O=0x00000000         <SEEK_CUR>                                                                                                                                                     0.000001   dd.9640084
14:05:41.784746  open              F=4        (RWC_T_)  private/tmp/x/bar.dat                                                                                                                                                 0.012308   dd.9640084
14:05:41.784750  fstat64           F=4                                                                                                                                                                                        0.000003   dd.9640084
14:05:41.784752  lseek             F=4    O=0x00000000         <SEEK_CUR>                                                                                                                                                     0.000002   dd.9640084
14:05:41.785310  read              F=3    B=0xfa000                                                                                                                                                                           0.000529   dd.9640084
14:05:41.889167  write             F=4    B=0xfa000                                                                                                                                                                           0.103855   dd.9640084
14:05:41.889351  read              F=3    B=0xfa000                                                                                                                                                                           0.000182   dd.9640084
14:05:42.095195  write             F=4  [  5]

**Comment by hanwen** [comment]
no idea. if this were linux, I'd suggest looking at strace, which gives you more detail on what syscall is returning EIO.

BTW, you are aware of the nodefs interface? It looks as if you're reinventing the wheel a bit by writing a raw filesystem.

**Comment by fingon** [comment]
nodefs had some scalability issues for my design; I can't remember offhand why but there were at least two things (one of them being that it made some assumptions about e.g. directories being relatively small and/or in one data structure with a slice easily available; the target dataset I am shooting for has directories with 100+k files in places).

anyway, that 5 return in fs_usage is the EIO, and it comes for second megabyte-sized write (same thing happens also with smaller bs, so it is some interaction of dd and osxfuse).

This does NOT occur with other osxfuse based filesystems (e.g. encfs seems to be fine). So I suspect it is something to do with go-fuse as I do not even have anything to do with EIO on my side.

**Comment by hanwen** [comment]
if it's go-fuse you should be able to repro with one of the existing go-fuse examples. Have you tried that?

**Comment by rfjakob** [comment]
So the user process gets EIO but your filesystem did not send it. This
usually means that the kernel (osxfuse in your case) did not like the data
it received. This means your filesystem is violating some osxfuse constraint

**Comment by fingon** [comment]
I found out actually the source of the problem and it was on my side. I assumed the write call behaves like e.g. C write, but it is actually write-all-or-error :-) With block offset + write size crossing block border in my case, EIO occurred.  Everything OS X normally does apparently does things in ~4-64kb increments so I managed to use the filesystem a bit until I encountered dd :-p

**Comment by fingon** [comment]
Apparently Linux version of fuse is bit more forgiving than osxfuse in this matter, as I did not see the problem there.

**Comment by rfjakob** [comment]
Watch out, linux will pad with zeros if it gets too little data. Anyway,
congrats for finding it!
