### ISSUE TITLE
zipfs memtree initialization depends on map iteration order

### ISSUE THREAD

**Issue by andrewchambers** [hanwen/go-fuse#203]
https://github.com/hanwen/go-fuse/blob/9060525339d688b3e8313f25eee96690d7314a60/zipfs/memtree.go#L53

initializes the filesystem based on on random map initialization order, if I am understanding correctly then a tar with contents like:
```
/foo/
/foo/bar/
/foo/bar/bang.txt
```
will mount with unpredictable results, (my private code based on this sample was randomly crashing).

**Comment by hanwen** [comment]
I'm pretty sure we have unittests for memtree that cover this piece of code. 

What crash do you see?
