### ISSUE TITLE
MacOS breakage: "osxfuse: vnode changed generation"

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#204]
I recenty got a ticket filed against gocryptfs with macos users seeing errors when copying files: https://github.com/rfjakob/gocryptfs/issues/213

I have now managed to get my hands on macos box (high sierra, osxfuse 3.7.1). The [extractloop.bash](https://github.com/rfjakob/gocryptfs/blob/master/tests/stress_tests/extractloop.bash) stress test reproduces the issue, both for gocryptfs (just run `./extractloop.bash`) and loopback (running `./extractloop.bash -loopback`). 

The tar extract fails with lots of
```
Can't create file
```
errors while we get these [osxfuse errors](https://github.com/osxfuse/kext/blob/534773bd3135f04b7f6fb801faa2f8991daf4a6b/osxfuse/fuse_node.c#L225) in dmesg:
```
osxfuse: vnode changed generation
osxfuse: vnode changed generation
osxfuse: vnode changed generation
```
I was tempted to suggest that osxfuse is just completely broken, but `./extractloop.bash -encfs` (running the same tarball extract test against encfs) works fine. So I guess we should be doing something differently on macos. Ideas?

**Comment by hanwen** [comment]
the generation numbes are generated in a harebrained way, 

https://github.com/hanwen/go-fuse/blob/da8b3e44dd6cb8bbb2325ca4135f70cc6398773c/fuse/nodefs/handle.go#L85

**Comment by rfjakob** [comment]
Let's see if the osxfuse people can shed some light on this: https://github.com/osxfuse/osxfuse/issues/482

**Comment by magnusja** [comment]
Looks very much the same for encfs? https://github.com/vgough/encfs/blob/1c273ecba57d95c529f21d72c7615e2bb8a911cf/encfs/Context.cpp#L190
