### ISSUE TITLE
PathFileSystem Create returning EIO to userspace

### ISSUE THREAD

**Issue by ncw** [hanwen/go-fuse#207]
I've been trying to create a PathFileSystem fuse FS for rclone using go-fuse.

However I can't get [the Create callback](https://github.com/ncw/rclone/blob/go-fuse/cmd/mount2/fs.go#L228-L251) to work.

When I do this

```
$ echo hellohellohello > /mnt/tmp/hello3
bash: /mnt/tmp/hello3: Input/output error
```

I see this

```
2018/03/21 14:45:11 Dispatch 55: LOOKUP, NodeId: 1. names: [hello3] 7 bytes
2018/03/21 14:45:11 Serialize 55: LOOKUP code: 2=no such file or directory value: {NodeId: 0 Generation=0 EntryValid=0.000 AttrValid=0.000 Attr={M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000000 M 0.000000000 C 0.000000000}}
2018/03/21 14:45:11 Dispatch 56: CREATE, NodeId: 1. data: {0100664 [CREAT,WRONLY,TRUNC,0x8000] (02)} names: [hello3] 7 bytes
2018/03/21 14:45:11 DEBUG : hello3: Create: flags=0101101, mode=0100664
2018/03/21 14:45:11 DEBUG : hello3: Open: flags=O_WRONLY|O_CREATE|O_TRUNC|0x8000
2018/03/21 14:45:11 DEBUG : hello3: >Open: fd=hello3 (w), err=<nil>
2018/03/21 14:45:11 DEBUG : hello3: >Create: handle=File fh=0xc42047e550(hello3) () TRUNC,CREAT,WRONLY,0x8000 NONSEEK, status=OK
2018/03/21 14:45:11 status = OK
2018/03/21 14:45:11 Serialize 56: CREATE code: OK value: {NodeId: 11 Generation=10 {M00 SZ=0 L=1 502:502 B0*0 i0:11 A 0.000000000 M 0.000000000 C 0.000000000} &{3 4 0}}
```

Note the OK status in the serialize return (and there were no logs after that).

I conjecture that [this bit of code in the linux kernel source fs/fuse/dir.c](https://github.com/torvalds/linux/blob/master/fs/fuse/dir.c#L452) is noting that the mode of the file is 0 and changing that OK status into EIO.

```c
	err = fuse_simple_request(fc, &args);
	if (err)
		goto out_free_ff;

	err = -EIO;
	if (!S_ISREG(outentry.attr.mode) || invalid_nodeid(outentry.nodeid))
		goto out_free_ff;
```

Which is telling me that I should be setting attributes with the Create call.
I don't see a way of setting that attribute returned with the Create call.  I have implemented `GetAttr` on the handle but it doesn't seem to be being called.

What I think is happening is that
  * [nodefs Create gets called](https://github.com/hanwen/go-fuse/blob/master/fuse/nodefs/fsops.go#L364-L377)
  * this calls [childLookup](https://github.com/hanwen/go-fuse/blob/master/fuse/nodefs/fsconnector.go#L93-L106)
  * this calls [pathfs GetAttr](https://github.com/hanwen/go-fuse/blob/master/fuse/pathfs/pathfs.go#L578)
  * However inserting a few debug statements I find that it never finds an open file
  * so it ends up calling the [fallback GetAttr](https://github.com/hanwen/go-fuse/blob/master/fuse/pathfs/pathfs.go#L596)
  * which returns ENOENT as as far as rclone is concerned the file hasn't been created yet
  * and back in [childLookup the error return is ignored](https://github.com/hanwen/go-fuse/blob/master/fuse/nodefs/fsconnector.go#L95) - I think that is a bug!

So I think this is caused by go-fuse not finding the newly opened file and using that for its GetAttr which I think it should be doing. I think what should happen is that `childLookup` or a variant should call `GetAttr` on the open file handle directly.

I'll make a PR with a proposed fix in a moment

**Comment by hanwen** [comment]
i'm pretty sure there is test coverage for Create under fuse/test/ , which should cover most normal behaviors.

what should happen is that from here 
https://github.com/hanwen/go-fuse/blob/a9ddcb8a4b609500fc59c89ccc9ee05f00a5fefd/fuse/nodefs/fsops.go#L371

we call childLookup, which does GetAttr on the newly created filename,

https://github.com/hanwen/go-fuse/blob/a9ddcb8a4b609500fc59c89ccc9ee05f00a5fefd/fuse/nodefs/fsconnector.go#L94


Can you compare what the LoopbackFileSystem does?

**Comment by hanwen** [comment]
no response, so closing.

note that the new FS API makes it impossible to commit this error.
