### ISSUE TITLE
Passing the umask value for Create, Mknod, Mkdir Filesystem calls

### ISSUE THREAD

**Issue by zarmin** [hanwen/go-fuse#228]
Currently the rawBridge functions are not passing the umask argument (only in types_linux) to Mknod, Create, Mkdir Filesystem calls.

The only way to get it to copy the rawBridge implementation into my project and modify these calls.

Can you change the arguments by adding the umask or give some alternative solution to access them?

**Comment by zarmin** [comment]
I've also come to the same conclusion about an hour ago :) Thanks!

It's works for me perfectly:
```go
type FileSystemBridge struct {
	fuse.RawFileSystem
}

func applyUmask(mode uint32, umask uint32) uint32 {
	const permMask uint32 = 0777
	return mode & ^(umask & permMask)
}

func (c *FileSystemBridge) Mkdir(input *fuse.MkdirIn, name string, out *fuse.EntryOut) (code fuse.Status) {
	input.Mode = applyUmask(input.Mode, input.Umask)
	return c.RawFileSystem.Mkdir(input, name, out)
}

// only in _linux
func (c *FileSystemBridge) Mknod(input *fuse.MknodIn, name string, out *fuse.EntryOut) (code fuse.Status) {
	input.Mode = applyUmask(input.Mode, input.Umask)
	return c.RawFileSystem.Mknod(input, name, out)
}

// only in _linux
func (c *FileSystemBridge) Create(input *fuse.CreateIn, name string, out *fuse.CreateOut) (code fuse.Status) {
	input.Mode = applyUmask(input.Mode, input.Umask)
	return c.RawFileSystem.Create(input, name, out)
}

func GetFileSystemBridge(c *nodefs.FileSystemConnector) fuse.RawFileSystem {
	rawFS := &FileSystemBridge{c.RawFS()}
	return rawFS
}
```

**Comment by hanwen** [comment]
I clarified behavior here, https://github.com/hanwen/go-fuse/commit/815666ab119f4b2e6ac801c66d4b5c06a970f1cc

the kernel already sends the mode with umask applied. Is there a reason why you want to get at the umask / original mode?
