### ISSUE TITLE
Question: Graceful Stop of Shutdown of Serve()

### ISSUE THREAD

**Issue by jdgiotta** [hanwen/go-fuse#230]
I noticed that if I stop a loopback that it will maintain the mountpoint path. Is there a graceful shutdown of the `Server`?

**Comment by hanwen** [comment]
what does "maintain mountpoint path mean"? 

```hanwen@localhost ~]$ fusermount -u /tmp/mnt 
[hanwen@localhost ~]$ loopback  /tmp/mnt $HOME&
[1] 9915
Mounted!
[hanwen@localhost ~]$ mount|grep tmp/mnt
/home/hanwen on /tmp/mnt type fuse.loopbackfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
[hanwen@localhost ~]$ fusermount -u /tmp/mnt 
[1]+  Done                    loopback /tmp/mnt $HOME
[hanwen@localhost ~]$ mount|grep tmp/mnt
[hanwen@localhost ~]$ 
```

**Comment by jdgiotta** [comment]
I approached it by calling `Unmount()` on signals. Basically, I was finding that if the program stopped that a fuse mounted directory was still in a odd mount state.

Thank you for your time!
