### ISSUE TITLE
Loopback Write

### ISSUE THREAD

**Issue by jdgiotta** [hanwen/go-fuse#231]
I want to leverage Loopback to read existing files, but new files need to be altered before going to the root path.

Are there any examples of how to accomplish this?

**Comment by hanwen** [comment]
see here https://github.com/hanwen/go-fuse/commit/815666ab119f4b2e6ac801c66d4b5c06a970f1cc#diff-6bfdee382bdca324de4d14fb9a1d43ac

for an example of how to override calls (in this case, the Create and Mkdir calls.)

**Comment by jdgiotta** [comment]
Cool, but what about with files? For example, reverse the contents of written file. From what I understand the `Write` operation is where I can alter the file, but what if I'm adding content?
