### ISSUE TITLE
ReadDir returns outdated directory content

### ISSUE THREAD

**Issue by slackner** [hanwen/go-fuse#252]
First of all, thanks for this awesome project! I'm currently debugging an issue I found with gocryptfs (which uses go-fuse) on macOS, and I hope its okay to open a bug report here to get some more opinions involved. The bug is https://github.com/rfjakob/gocryptfs/issues/351, however, I will provide a short summary/analysis below.

The issue occurs in a test that repeatedly creates files and queries directory listings with multiple FUSE systems mounted on top of each other. While this test works fine on Linux, on macOS apparently at some point the directory listings contain outdated information. The exact timing of the failure is more or less random. Looking at the debug output shows that, at the point where the application calls `OpenDir`, there is no corresponding FUSE call. Instead, the following `ReadDir` calls use an existing file handle?!

Relevant log (shortened and annotated):

```
2019/01/15 12:02:45 rx 2: OPENDIR i1 
2019/01/15 12:02:45 tx 2:     OK, {Fh 2 }

    ... file is created here ...

2019/01/15 12:02:45 rx 4: LOOKUP i1 ["gocryptfs.longname.iNPx_rqvgCZCkSHiDxThVRUMDqfqDYPSMcu58uAVTdA"] 63b
2019/01/15 12:02:45 tx 4:     OK, {i330 g329 tE=1s tA=1s {M0100644 SZ=0 L=1 503:204 0 0:3182331 A 1547582565.000000 M 1547582565.000000 C 1547582565.000000}}
[...]
2019/01/15 12:02:45 rx 4: OPEN i330 {O_RDONLY} 
2019/01/15 12:02:45 tx 4:     OK, {Fh 3 }
[...]
2019/01/15 12:02:45 rx 2: RELEASE i330 {Fh 3   L0} 
2019/01/15 12:02:45 tx 2:     OK

    ... opening the file seems to work fine ...
    ... here is an OpenDir call in the source, but there is no matching OPENDIR fuse call ...

2019/01/15 12:02:45 rx 3: READDIR i1 {Fh 2 [0 +6553) } 
2019/01/15 12:02:45 tx 3:     OK,  328b data "\u038d0\x00\x00\x00\x00\x00"...
2019/01/15 12:02:45 rx 2: READDIR i1 {Fh 2 [6 +6553) } 
2019/01/15 12:02:45 tx 2:     OK

    ... unsurprisingly the application gets the outdated directory listing ...
```

Full log is available [here](https://gist.githubusercontent.com/slackner/ca6a69b8886faf9fba3fafd32d7e2f5c/raw/0f5e117898f6d4189a76ce95739a43a02f0b1af1/gistfile1.txt), however it is difficult to read since multiple logs are interleaved.

This gave me the suspicion that the kernel reuses an existing Fh that has been opened, but never read from. To verify this hypothesis, I tried removing the `d.lastOffset > 0` condition in `fuse/nodefs/dir.go`, and it indeed fixed the issue:

```
	// rewinddir() should be as if reopening directory.
	// TODO - test this.
	if d.lastOffset > 0 && input.Offset == 0 {
		d.stream, code = d.node.OpenDir((*fuse.Context)(&input.Context))
		if !code.Ok() {
			return code
		}
	}
```

I know that we are now querying the directory content twice, but for a short demonstration it should be sufficient. A comparison with `libfuse` confirms that this is also what the C-implementations do.

Linux: https://github.com/libfuse/libfuse/blob/b8093eb57b5cf71dbe91dcb5cf5f8c86b1641752/lib/fuse.c#L3703
MacOS: https://github.com/osxfuse/fuse/blob/abc35f85fdede186ed164082bd71fc1217d2f58f/lib/fuse.c#L3983

In both cases, the code states that:

```
	/* According to SUS, directory contents need to be refreshed on
	   rewinddir() */
	if (!off)
		dh->filled = 0;

	if (!dh->filled) {
		err = readdir_fill(f, req, ino, size, off, dh, &fi, flags);
```

I suspect `go-fuse` should behave in the same way and needs to drop the whole `d.lastOffset` tracking. What else could be done to track this problem down further?

Probably no longer relevant then after fixing this bug, but I also stumpled upon the following lines in `fuse/nodefs/dir.go` where the `d.lastOffset` update seems to be missing.

```
		// No need to fill attributes for . and ..
		if e.Name == "." || e.Name == ".." {
			continue
		}
```
**Edit:** If it matters, I'm currently testing on macOS High Sierra with kernel version `17.7.0`.  Osxfuse is at version `3.8.3` and `go-fuse` is at 425e8d5301f6ca119f7abfe798920dbf24a396c7.

**Comment by hanwen** [comment]
/* According to SUS, directory contents need to be refreshed on
	   rewinddir() */

what is SUS ?

**Comment by slackner** [comment]
Apparently it refers to the SUSv3 standard. The comment was initially added in https://github.com/libfuse/libfuse/commit/77ccf6540abc0af4deb4d76d7b527b909dde52e3. More discussion seems to be available here: https://sourceforge.net/p/fuse/mailman/message/7409313/:

> OK, looked at the SUSv3 standard, and it does specify the behavior on
> rewinddir():
> 
>    It shall also cause the directory stream to refer to the current
>    state of the corresponding directory, as a call to opendir() would
>    have done.
> 
> Also offsets returned by telldir() may become stale after a
> rewinddir():
> 
>    If the value of loc was not obtained from an earlier call to
>    telldir(), or if a call to rewinddir() occurred between the call to
>    telldir() and the call to seekdir(), the results of subsequent
>    calls to readdir() are unspecified.
> 
> So let's reset dh->filled, when offset is zero (after opendir() and
> rewinddir()).  That should make it conforming, and so hopefully also
> fix the 'rm -rf' issue.

**Comment by rfjakob** [comment]
I think this can be fixed without API change by dropping the initial OpenDir call from rawBridge

**Comment by slackner** [comment]
Another suspicious observation: Why is "." and ".." only added in the initial `OpenDir`, but not when rewinding?

**Comment by slackner** [comment]
And yet another possible issue in the current implementation: The `ReadDir` implementation contains code to skip empty names.

```
		if e.Name == "" {
			log.Printf("got empty directory entry, mode %o.", e.Mode)
			continue
		}
```

However, this means that the offsets returned in `out *fuse.DirEntryList` might differ from the real offsets in the `d.stream`. As a result, an application trying to resume enumeration might pass the wrong offset, and get the same entries multiple times. If I don't miss anything, it could even get stuck in an endless loop when the list contains enough empty entries.

**Comment by slackner** [comment]
Hacky draft patch of what I had in mind. So far completely untested (besides a quick compilation check):
http://ix.io/1yPt

**Comment by hanwen** [comment]
this looks really complicated; what do you think of @rfjakob 's suggestion ?

**Comment by rfjakob** [comment]
True, does not fix either of those. However, for https://github.com/hanwen/go-fuse/issues/252#issuecomment-455527399 , returning empty directory entries is a bug in the FS, so I'd call that "garbage in, garbage out, we warned you" ;)

For the corrupted directory listings, I'd call that a bug in osxfuse's kernel module (but I guess they are working around some limitation in osx)

**Comment by rfjakob** [comment]
Patch updated, thanks for the comments @slackner : https://github.com/rfjakob/go-fuse/commit/816463b68fc3207585d252ad14bac52d0d9506eb

**Comment by slackner** [comment]
I can confirm that https://github.com/rfjakob/go-fuse/commit/816463b68fc3207585d252ad14bac52d0d9506eb fixes the main issue on macOS. Thanks for your effort!

Btw, regarding the remaining "OSXFUSE" issue: The more I think about it, the more I believe that it might also affect Linux. While the POSIX specification of [seekdir](http://pubs.opengroup.org/onlinepubs/007908799/xsh/seekdir.html) does not require that previous offsets work after a `rewinddir`,

> If the value of loc was not obtained from an earlier call to telldir() or if a call to rewinddir() occurred between the call to telldir() and the call to seekdir(), the results of subsequent calls to readdir() are unspecified.

there is no such exception in the [Linux](http://man7.org/linux/man-pages/man3/seekdir.3.html), [BSD](https://www.freebsd.org/cgi/man.cgi?query=readdir&apropos=0&sektion=0&manpath=FreeBSD+4.3-RELEASE&format=html), or macOS man pages. This is probably why the OSXFUSE devs relied on it, but other developers might make similar assumptions in their code.

**Comment by rfjakob** [comment]
Great, thanks for testing! I'll send this through xfstests, and make a PR if it does not explode

**Comment by rfjakob** [comment]
Looks good, no new failures: https://gist.github.com/rfjakob/5845869e8d11590a0310b862b09dbb34

**Comment by slackner** [comment]
While the main issue should be fixed with @rfjakob's patch, I've been further looking into the remaining issues and got some quite interesting observations with the following hacky tests: http://ix.io/1z7l

Instructions:
```
gcc -o test test.c
cd directory-to-test
./test
```

**Linux:**
EXT4 has no trouble reusing directory offsets after a refill even if entries have been deleted in the meantime - all tests pass. For go-fuse with @rfjakob's patch applied there is only one remaining test failure: Rewinding to offset 0 invalidates any previous offsets. This is acceptable since the specs say it is undefined. So far everything as expected.

**MacOS:**
Here it gets a bit interesting: Both tests related to rewinding to offset 0 fail. But not just for go-fuse, they also fail for HFS. For testing purposes I also modified the test, and a concurrent "ls testdir"-process is sufficient to mess up directory enumeration when offsets have changed. I'm really surprised that this is not taken into account, but at least its a good excuse why we don't try to workaround it. More surprisingly, the tests also show that there are apparently off-by-one errors with the directory offsets... this needs further investigations.

**Comment by hanwen** [comment]
this should be fixed now.
