### ISSUE TITLE
Why may Node.Open() return a nil File, while Node.Create() may not?

### ISSUE THREAD

**Issue by EdSchouten** [hanwen/go-fuse#255]
I'm creating a file system for which I don't necessarily need to track per-file-descriptor information. In my case it thus makes sense to let Node.Open() return nil and implement Node.Read(), Node.Write(), etc. I managed to get this working all right.

Now the second step is to implement file creation, so I implemented Node.Create(). Just like Node.Open(), I made it so that it returns a nil File object. But this causes crashes due to nil pointer dereferences in several places.

I made a crude patch for go-fuse to work around the nil pointer dereferences, but due to me now knowing what I'm doing, I suspect that this is just causing the library to misbehave. My question is thus, is this a limitation of FUSE in general, or simply a missing feature of go-fuse?

**Comment by navytux** [comment]
I also had to do something with `Node.Open()` that returns File=nil for the open to be handleless. I would say `Node.Create()` should also support File=nil for consistency and to support statless creates/opens. We should not have any wrapper for that to work, and if something does not work here on go-fuse side its a bug that should be fixed.

For the reference some nil-pointer crash related to Open -> File=nil has been just fixed: https://github.com/hanwen/go-fuse/pull/258.

If you still see things to be not working for you, I suggest to provide `TestNoFile` amendment with demonstration of your problem. Then it should be more clear what to do.

**Comment by hanwen** [comment]
this shouldl be supported on the v2 fs/ API.
