### ISSUE TITLE
Semantic version release tags

### ISSUE THREAD

**Issue by creachadair** [hanwen/go-fuse#272]
In order to better support Go modules, would you please consider adding release tags in the `v1.2.3` format? In particular, the only tagged release so far is `v20170619` which is neither in the semantic version format, nor particularly recent. 

I don't have a strong feeling about whether this package's API ought to be `v0` or a `v1`, but I am trying to update the dependencies of https://github.com/kythe/kythe to use tagged module versions and would be happy with anything reasonably recent.

**Comment by hanwen** [comment]
Hey Michael !
nice to hear from you.

$ git show v1.0.0 | head
tag v1.0.0
Tagger: Han-Wen Nienhuys <hanwen@google.com>
Date:   Fri Mar 1 11:00:41 2019 +0100

Tag this version arbitrarily as v1.0.0, to aid Go module versioning

commit fb9b7327a6ab6a80f4a61aab97f021ebcea25142
Author: Han-Wen Nienhuys <hanwen@google.com>
Date:   Sat Feb 23 14:00:14 2019 +0100

**Comment by hanwen** [comment]
(I tried to send you email, but couldnt readily find your contact info.)

Is there a real use of go-fuse for Kythe? ISTR that it was an experimental intern project. 

If you are interested in FUSE file systems, I am building a new API more or less from scratch at 

 https://github.com/hanwen/go-fuse/pull/270 

and any insights are welcome.

hope that all is well on your side. It's perf time over here, so things are busy.

**Comment by creachadair** [comment]
> Is there a real use of go-fuse for Kythe? ISTR that it was an experimental intern project.

I suppose it depends on your definition of "real". It is not on the critical path, but we do have a FUSE wrapper recently contributed by @robinp that exposes the path structure of an index. I think you may be thinking of the LSP integration, which @djrenren wrote a couple years ago during his internship on the Grok team. That code is actually in production inside Google (it's the core of the editor integrations described at go/kythe-language-server assuming the URL hasn't changed)—but does not use FUSE.

Thanks for adding the tag!

**Comment by creachadair** [comment]
By the way, if you have any questions about Kythe's use of go-fuse, feel free to hop onto our Slack workspace, to which I just sent you an invite (hopefully).

**Comment by hanwen** [comment]
I'm not a slack person, so if you have pointers to source code / public forums, that would be great.

**Comment by creachadair** [comment]
> I'm not a slack person, so if you have pointers to source code / public forums, that would be great.

We have a [kythe-dev](https://t.co/iiWMKI5rvr) mailing list (Groups), and the [main Kythe repo](http://github.com/kythe/kythe) is on GitHub where we also track issues.

Imports go inbound from GitHub to Google, so the upstream is the main source of truth except for internal-specific wrappers.

That said: You can use [our Slack workspace](https://kythe-project.slack.com/) from the browser, so even if you aren't a frequent user it's not too painful to set up if you want to ask live questions.

**Comment by hanwen** [comment]
I know about slack, but it's one more thing to keep track of. In the meantime, I did find kythefs. thanks!
