### ISSUE TITLE
direct_io support

### ISSUE THREAD

**Issue by ryanstout** [hanwen/go-fuse#28]
Fuse has support for direct_io.  My understanding is that golang doesn't out of the box, but there are some extensions to support it.  Has anyone looked into adding direct_io support?

Thanks

**Comment by yasker** [comment]
Hi @hanwen 

I tried `direct_io` option, but cannot figure out why it doesn't work on my setup(Ubuntu 16.04):

```
conn := nodefs.NewFileSystemConnector(newFs.Root(), nil)
opts := &fuse.MountOptions{
                        MaxBackground: 12,
                        Options:       []string{"direct_io"},
                }
server, err := fuse.NewServer(conn.RawFS(), fs.GetMountDir(), opts)
```

fusermount reports:

```
/bin/fusermount: mount failed: Invalid argument
```

And if I remove `direct_io` option it works.

**Comment by vChrysanthemum** [comment]
try   
```
func(fs *FS) Open(name string, flags uint32, context *fuse.Context) (nodefs.File, fuse.Status) {
        f := ...
        return &nodefs.WithFlags{
                File:      f,  
                FuseFlags: fuse.FOPEN_DIRECT_IO,
        }, fuse.OK
}
```

**Comment by yasker** [comment]
Thanks @vChrysanthemum , I've figured that out lately, but it still doesn't work for me. I am sure kernel is handling the file in direct-io mode but it somehow hangs(soft lock up) due to waiting for a page to be locked. I am still investigating.

And I saw `bazil/fuse` seems tested with direct_io already, so may want to give that a try as well.

**Comment by yasker** [comment]
Just a update: soft lock up caused by a kernel bug in FUSE interaction with loopback device. It exists after Linux v4.1. Details can be found at https://sourceforge.net/p/fuse/mailman/message/35276378/

**Comment by WoolenWang** [comment]
having the same issue , can not support when using namazu with direct_io , it use this go-fuse lib.
@yasker 
have you find out how to support this direct_io?

**Comment by hanwen** [comment]
you can use directio by specifying the fuse.FOPEN_DIRECTIO flag from create or open methods.
