### ISSUE TITLE
Any support for tar.gz planned?

### ISSUE THREAD

**Issue by hanneslehmann** [hanwen/go-fuse#285]
As the title says, I have a tar.gz which I would like to mount, as zip does not support all features I would need. Anything in the pipeline?

Thanks and regards,
Hannes

**Comment by hanwen** [comment]
See https://github.com/hanwen/go-fuse/commit/d1deed27c98bed3e0f83a4fdce9401f491c27305

$ fusermount -u /tmp/x ; go run github.com/hanwen/go-fuse/example/multizip /tmp/x & 
$ cd /tmp/x
$ ln -s /usr/share/sawfish/themes/mxflat.tar.gz config/mxflat
$ cd mxflat/
$ ls
mxflat
$ find 
.
./mxflat
./mxflat/button-icons
./mxflat/button-icons/default-9
./mxflat/button-icons/default-9/button-a1.png
./mxflat/button-icons/default-9/button-lock2.png

etc.

**Comment by hanneslehmann** [comment]
Hi,
that was quick - thanks. Will check it out
