### ISSUE TITLE
Have trouble in go-fuse filesystem with nfsv4 of esxi

### ISSUE THREAD

**Issue by losewell** [hanwen/go-fuse#305]
Hello All:
    I have a problem that I have written a go-fuse filesystem,and I mounted any directory successfully.But,when I export the mount directory with nfsv4,I found that the directory on nfs client (my esxi host) is empty.
    For example,/x is a mount directory,which is mounted by my program that based to go-fuse.Then I want to export it for client to share,so something like below int /etc/exports:
    /x  *(rw,sync,fsid=0,crossmnt,no_subtree_track)
Finally,I create a nfs datastore in my esxi host,and the share directory is empty.
I'm not sure whether this question is suited to ask here!So, Any suggestions would be appreciated!

**Comment by losewell** [comment]
Thank for your reply!
Do you mean fusermount?

**Comment by hanwen** [comment]
I mean the hello file system. 

Or any other libfuse based file system, eg. sshfs.

**Comment by losewell** [comment]
Hi!
I have tried your hello file system in example directory.But unluckily,it failed,and my esxi reported an I/Oerror

**Comment by hanwen** [comment]
I mean the one that comes with the libfuse C library, so we can decide if this is an issue in the Go library or something with FUSE on your kernel, fuse + NFS in general.

**Comment by losewell** [comment]
Hi,Mr.hanwen
Now it seems to find the problem: I didn't implement the StatFs function!
So a followup question:
StatFs(name string) *fuse.StatfsOut
Does StatFs function's argument, the name represent the mounted directory path? Thanks!

**Comment by losewell** [comment]
Hi!
I want to ask another question: if mountpoint is one level directory,for example, /a, there is no problem in my go-fuse program.But if moutpoint is Multilevel directory,for example, /a/b/, files in directory b aren't shown in the NFS client. I don't know whether is the problem of my program or not.How can I solve it? The configuration of /etc/exports is:
/a *(rw,sync,fsid=0,crossmnt,no_subtree_track)
/a/b *(rw,sync,crossmnt,no_subtree_track)
Thanks!

**Comment by hanwen** [comment]
I don't know. Have you tried asking in an NFS forum?

**Comment by losewell** [comment]
Thanks!
Maybe I need to do more work about this weird question.So I close it,and if I have some thought,I will record here!
