### ISSUE TITLE
What is the buffer arg in NodeReader.Read() for?

### ISSUE THREAD

**Issue by yasushi-saito** [hanwen/go-fuse#307]
Read() takes arg dest []bytes, but returns the ReadResult, which manages its own memory. In fact, all the existing implementations of Read only looks at the length of dest, but they never fill dest. Can I fill data into dest, then create a ReadResult that points to dest? 

Maybe it's clearer to change the interface to

Read(ctx context.Context, fileHandle, nByte int, offset int64) (ReadResult, Errno)

**Comment by hanwen** [comment]
"Can I fill data into dest, then create a ReadResult that points to dest?" 

yes, that is the intended use. The buffer is recycled to avoid creating garbage.

**Comment by yasushi-saito** [comment]
Ok, thanks for the clarification.
