### ISSUE TITLE
in server.go, is ms.singleReader has wrong use?

### ISSUE THREAD

**Issue by lixi520** [hanwen/go-fuse#308]
see:
if ms.singleReader {
			go ms.handleRequest(req)
} else {
			ms.handleRequest(req)
}

**Comment by hanwen** [comment]
I don't think so. Why do you say that?

**Comment by rfjakob** [comment]
The code is somewhat confusing, but the logic is like this:

if singlereader -> create new thread to handle the request so we don't block the main thread

else -> we already are in a dedicated thread, handle immediately
