### ISSUE TITLE
Update MAX_KERNEL_WRITE

### ISSUE THREAD

**Issue by darthShadow** [hanwen/go-fuse#309]
Since the Linux Kernel has increased the max allowed write from 128 KB to 1 MB from version 4.20, can this value be updated accordingly?

Apologies if this is stupid.

**Comment by rfjakob** [comment]
Hi! Do you have a link to the kernel commit?

**Comment by darthShadow** [comment]
This should be it: http://lkml.iu.edu/hypermail/linux/kernel/1810.3/05384.html

**Comment by darthShadow** [comment]
Not very sure whether the correct parameter to increase is MAX_KERNEL_WRITE or something else.

In case this is helpful, mergerfs has implemented it this way: https://github.com/trapexit/mergerfs/commit/7cbd88ac812478b31b3ff50ad4fa9e4d376a21fd

**Comment by darthShadow** [comment]
And the corresponding commit in libfuse: https://github.com/libfuse/libfuse/pull/384

**Comment by ghz-gehtz** [comment]
Hi,

this is what I needed to do to have bigger readahead and write size:

# increase pipe size for github.com/hanwen/go-fuse
# kernel: fs/pipe.c (default 1Mio)
# allow to lower memory foontprint and cpu usage by a lot if files are local
unsigned int pipe_max_size = 16777216;

# fuse 4MB readahead and write
kernel/fs/fuse/fuse_i.h:
#define FUSE_MAX_PAGES_PER_REQ ((int)((4*1024*1024) / (PAGE_SIZE)))

kernel/include/linux/mm.h:
#define VM_MAX_READAHEAD        4096    /* kbytes */

kernel/mm/readahead.c:
In a function named "force_page_cache_readahead"
unsigned long this_chunk = (4 * 1024 * 1024) / PAGE_CACHE_SIZE;

From what I understand from hanwen code, buffers are dynamically created/re-used with the request size (go-fuse/fuse/bufferpool.go).

Note: I didn't test bigger readahead / write size with hanwen code but with jacobsa code. Still in the process of using hanwen and port everything. I have memory leak with jacobsa code...

**Comment by hanwen** [comment]
I tried to naively set CAP_MAX_PAGES, but would still see small reads. I would be grateful is somebody could hack something together that shows what mantra to send to the kernel to make it work.

**Comment by darthShadow** [comment]
Apologies, but I am not good enough with Go to figure out where to even start experimenting with this.

@hanwen There is an ongoing discussion about this @ https://forum.rclone.org/t/max-pages-on-linux-with-rclone-mergerfs/12724 where you will find folks better suited to help you.

If you would like to stick to Github itself, then you can ping them directly.

Contacts: ncw (https://github.com/ncw) & trapexit (https://github.com/trapexit)

Both are very knowledgable and between all 3 of you, this should be easily solvable.

**Comment by darthShadow** [comment]
@hanwen Could you give the example code that you tried so I can experiment further with it and see what works?

I believe we need a couple of things to get it working:
* Check if CAP_MAX_PAGES is present and set in the input flags
* Set CAP_MAX_PAGES [here](https://github.com/hanwen/go-fuse/blob/4367657f4c6f8397ee01acfbb92a7d5fa2ed8b4e/fuse/opcode.go#L91) if the above check is true
* Set the MaxPages parameter to 256 if the above check is true
* Set MaxWrites to 1 MB (instead of 128 KB) if the above check is true

**Comment by hanwen** [comment]
well, yes, you might be right, but then you also need to make a test that writes a file in 1 MB chunks, and then run it and observe that it really did write 1 MB chunks.  I did this but didn't observe the writes.
I can't remember where I left the code, unfortunately.

**Comment by darthShadow** [comment]
I have sent a PR #347 for adding the configuration. I tested it using the rclone implementation and it seems to be working fine with dd provided the block size is specified correctly. `cp` & `rsync` don't seem to support writes above 128k & 256k respectively which may explain your observation.

**Comment by trapexit** [comment]
Yes, `dd` is your friend here. For apps which don't write large sets of data the writeback cache can help.

**Comment by hanwen** [comment]
I've commented on the PR.

**Comment by hanwen** [comment]
fixed in https://review.gerrithub.io/c/hanwen/go-fuse/+/530724,

commit 265a39266958b8c4a540b4102e57b6fc0c5f95ef
