### ISSUE TITLE
Migrating from old nodefs/pathfs API to new fs API?

### ISSUE THREAD

**Issue by sebastianhaberey** [hanwen/go-fuse#311]
Hi,

I am contemplating migrating the [adbfs project](https://github.com/zach-klippenstein/adbfs) from nodefs/pathfs API to the new one. How would you rate the compatiblity of the old and new APIs on a scale from "complete rewrite" to "100% compatible"? In other word how much effort do you think a migration would take? Thanks for your input,

Sebastian

**Comment by hanwen** [comment]
Pathfs will likely be substantial work. Nodefs should be straightforward.

**Comment by sebastianhaberey** [comment]
Ok good to know, thanks for the assessment!
