### ISSUE TITLE
examples don't work due to missing /v2/ import

### ISSUE THREAD

**Issue by GregorioDiStefano** [hanwen/go-fuse#312]
These examples don't work due to this change: 
https://github.com/hanwen/go-fuse/commit/e9498b6bbccf0f17ddd56006dbf8a87a159e8304

The /v2/ folder doesn't exist on master.

Thanks

**Comment by hanwen** [comment]
which version of Go are you using? The v2 paths are for modules.

**Comment by ShayBox** [comment]
Yeah the v2 directory doesn't exist anymore, the examples should be updated, removing the /v2 from the imports fixes the problem.
Module or not it doesn't exist.

**Comment by hanwen** [comment]
Can you confirm this works _with_ modules?

Per https://blog.golang.org/migrating-to-go-modules, 

```
Another scenario in which a module's canonical path may differ from its repository path occurs for Go modules at major version 2 or higher. A Go module with a major version above 1 must include a major-version suffix in its module path: for example, version v2.0.0 must have the suffix /v2. However, import statements may have referred to the packages within the module without that suffix. For example, non-module users of github.com/russross/blackfriday/v2 at v2.0.1 may have imported it as github.com/russross/blackfriday instead, and will need to update the import path to include the /v2 suffix.
```

the v2 suffix is only necessary for the new API, whcih was introduced a few months ago. The old API should continue to work without v2 imports (as evidenced by the unionfs/ subdirectory).
