### ISSUE TITLE
Allow not depending on fusermount when running as root

### ISSUE THREAD

**Issue by MagicalTux** [hanwen/go-fuse#314]
The fusermount helper allows programs running as users to access the fuse subsystem while performing a number of safety checks (see util/fusermount.c in fuse source), however when the program runs as root it should be possible to avoid needing it at all by directly calling the mount syscall.

At minimum the process on Linux looks like this:
* Open /dev/fuse with O_RDWR
* Call mount syscall, pass fd to opened /dev/fuse in mount option fd=

It feels like this should be easy enough to implement and would remove the need to use fusermount which can be useful in some cases, such as when the executable runs in a read-only embedded system.

**Comment by hanwen** [comment]
see https://review.gerrithub.io/c/hanwen/go-fuse/+/467837 for the review.

**Comment by hanwen** [comment]
https://review.gerrithub.io/c/hanwen/go-fuse/+/467837 was merged.
