### ISSUE TITLE
rename cause file or dir miss

### ISSUE THREAD

**Issue by Sherlock-Holo** [hanwen/go-fuse#317]
When I try to implement [NodeRenamer](https://godoc.org/github.com/hanwen/go-fuse/fs#NodeRenamer), [mycode](https://github.com/Sherlock-Holo/tfs/commit/866c575c4d92de09631fc5ac193591e2aa67a0b1#diff-e1d60f6961aaad612feb94169ea4abffR333), I do it on my shell

```
/tmp/test $ dd if=/dev/urandom of=123.txt bs=1M count=10
记录了10+0 的读入
记录了10+0 的写出
10485760 bytes (10 MB, 10 MiB) copied, 0.099892 s, 105 MB/s
/tmp/test $ mv 123.txt 111.txt
/tmp/test $ ls
./  ../
```
the file disappears, it confuses me, anything I miss or I write wrong codes?

**Comment by Sherlock-Holo** [comment]
I manage children by myself, I create a map to store name and inode and fix this problem

**Comment by hanwen** [comment]
you're doing what the library internally does for you. Ie. you just have to return OK

see here:

https://github.com/hanwen/go-fuse/blob/a3bb2189dd75e519c3c70563526e09f04f08456e/fs/bridge.go#L454

**Comment by Sherlock-Holo** [comment]
thanks, should we mention it on NodeRenamer doc？

Han-Wen Nienhuys <notifications@github.com> 于 2019年9月16日周一 16:23写道：

**Comment by hanwen** [comment]
It's already documented, really, but happy to review improvements.

**Comment by Sherlock-Holo** [comment]
sorry, I misunderstand the doc, now I know it, thanks for your help 🤣

Han-Wen Nienhuys <notifications@github.com> 于 2019年9月16日周一 17:46写道：
