### ISSUE TITLE
(pathfs.FileSystem).Getattr() vs (nodefs.File).Getattr()

### ISSUE THREAD

**Issue by dsoprea** [hanwen/go-fuse#318]
I'm using _pathfs_, but there's an API for `Getattr()` at both the filesystem (_pathfs.FileSystem_) and file (_nodefs.File_; both _nodefs_ and _pathfs_ both seem to use _nodefs.File_ as their basic file type/API) level. When I create a file, I'm getting hits on both _Getattr()_ implementations. To follow-up from https://github.com/hanwen/go-fuse/issues/245, is _(pathfs.FileSystem).Getattr()_ just used to check for the existence of the file beforehand (read: should I be returning ENOENT or actually populating the attributes for the new file)? Whether I return ENOENT or set the attributes, I'm always getting success from FUSE for a file-create but an IO error at the command-line:

```
$ date > /tmp/tempmount/newdata
bash: /tmp/tempmount/newdata: Input/output error
```

However, FUSE isn't reporting any problems.

When _(pathfs.FileSystem).Getattr()_ returns ENOENT:

```
2019/09/18 05:09:55 rx 1: INIT i0 {7.26 Ra 0x20000 AUTO_INVAL_DATA,READDIRPLUS,READDIRPLUS_AUTO,WRITEBACK_CACHE,POSIX_ACL,BIG_WRITES,DONT_MASK,SPLICE_READ,NO_OPEN_SUPPORT,HANDLE_KILLPRIV,EXPORT_SUPPORT,SPLICE_MOVE,FLOCK_LOCKS,ASYNC_READ,ATOMIC_O_TRUNC,SPLICE_WRITE,PARALLEL_DIROPS,POSIX_LOCKS,IOCTL_DIR,ASYNC_DIO} 
2019/09/18 05:09:55 tx 1:     OK, {7.26 Ra 0x20000 ASYNC_READ,PARALLEL_DIROPS,AUTO_INVAL_DATA,READDIRPLUS,BIG_WRITES,NO_OPEN_SUPPORT 0/0 Wr 0x10000 Tg 0x0}
Waiting for unmount.
2019/09/18 05:09:55 rx 2: ACCESS i1 {u=1000 g=1000 r} 
2019/09/18 05:09:55 tx 2:     38=function not implemented
2019/09/18 05:09:55 rx 3: LOOKUP i1 [".Trash"] 7b
2019/09/18 05:09:55 tx 3:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/09/18 05:09:55 rx 4: LOOKUP i1 [".Trash-1000"] 12b
2019/09/18 05:09:55 tx 4:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/09/18 05:09:58 rx 5: LOOKUP i1 ["newdata"] 8b
2019/09/18 05:09:58 tx 5:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/09/18 05:09:58 rx 6: CREATE i1 {0100644 [TRUNC,WRONLY,CREAT,0x8000] (022)} ["newdata"] 8b
2019/09/18 05:09:58 tx 6:     OK, {i3 g2 {M00 SZ=0 L=1 0:0 B0*0 i0:3 A 0.000000 M 0.000000 C 0.000000} &{2 0 0}}
```

When we'e setting the actual attributes:

```
2019/09/18 05:23:36 rx 1: INIT i0 {7.26 Ra 0x20000 ASYNC_READ,EXPORT_SUPPORT,NO_OPEN_SUPPORT,HANDLE_KILLPRIV,ATOMIC_O_TRUNC,SPLICE_MOVE,READDIRPLUS,AUTO_INVAL_DATA,READDIRPLUS_AUTO,PARALLEL_DIROPS,DONT_MASK,SPLICE_WRITE,FLOCK_LOCKS,IOCTL_DIR,POSIX_ACL,POSIX_LOCKS,BIG_WRITES,SPLICE_READ,ASYNC_DIO,WRITEBACK_CACHE} 
2019/09/18 05:23:36 tx 1:     OK, {7.26 Ra 0x20000 READDIRPLUS,AUTO_INVAL_DATA,PARALLEL_DIROPS,BIG_WRITES,ASYNC_READ,NO_OPEN_SUPPORT 0/0 Wr 0x10000 Tg 0x0}
Waiting for unmount.
2019/09/18 05:23:36 rx 2: ACCESS i1 {u=1000 g=1000 r} 
2019/09/18 05:23:36 tx 2:     38=function not implemented
2019/09/18 05:23:36 rx 3: LOOKUP i1 [".Trash"] 7b
2019/09/18 05:23:36 tx 3:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/09/18 05:23:36 rx 4: LOOKUP i1 [".Trash-1000"] 12b
2019/09/18 05:23:36 tx 4:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/09/18 05:23:40 rx 5: LOOKUP i1 ["newdata"] 8b
2019/09/18 05:23:40 tx 5:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
2019/09/18 05:23:40 rx 6: CREATE i1 {0100644 [CREAT,WRONLY,TRUNC,0x8000] (022)} ["newdata"] 8b
2019/09/18 05:23:40 tx 6:     OK, {i3 g2 {M0755 SZ=0 L=1 1000:1000 B0*65536 i0:75 A 1568798620.260837 M 1568798620.260837 C 1568798620.260837} &{2 0 0}}
```

The latter looks correct but both are showing "OK".

I would expect that _(pathfs.FileSystem).Getattr()_ was called beforehand to verify whether the file/path already exists and _(nodefs.File).Getattr()_ was called afterword to read the new attributes. However, one is not explicitly called after the create (or we're failing before it gets there), and I'm not clear while it's failing at all when FUSE is returning success.

It's worth mentioning that:

1. The logging is showing that the "LOOKUP" event for "newdata" is returning ENOENT, but this never actually enters my implementation. Obviously FUSE must hit its own in-memory representation or yours without querying my implementation. 

2. The "CREATE" event includes all of the attribute information. So, clearly the _Create()_ call from FUSE calls my _Create()_ method but either you (likely) or FUSE (less likely) is calling my _Getattr()_ _alongside_ the _Create()_ call rather than making a separate call (because it's not logged as a separate call).

I cold use help filling in the holes.

**Comment by hanwen** [comment]
` {M0755`

you are missing mode bits. 

This is one of the things that has been fixed in the newer fs API.

**Comment by dsoprea** [comment]
What should it be? A _regular_ file is (0).

I'm already using pathfs as previously recommended. Which newer interface/type are you referring to?

**Comment by hanwen** [comment]
the newer API is https://godoc.org/github.com/hanwen/go-fuse/fs
