### ISSUE TITLE
OnUnmount usage

### ISSUE THREAD

**Issue by dsoprea** [hanwen/go-fuse#319]
I'm having trouble getting OnUnmount to activate under _pathfs_. I added verbosity on every implementation of it that appeared to be relevant, and nothing ever prints. This happens with the _unionfs_ example as well. I'm unmounting from the command-line.

Where I injected debugging (among other places): https://github.com/hanwen/go-fuse/blob/e9498b6bbccf0f17ddd56006dbf8a87a159e8304/fuse/pathfs/loopback.go#L55
The unionfs example: https://github.com/hanwen/go-fuse/blob/e9498b6bbccf0f17ddd56006dbf8a87a159e8304/example/unionfs/main.go

What am I missing?

**Comment by hanwen** [comment]
this is for "sub"mounts, a poorly conceived idea that is not available in the new API.

You can wait on server.Serve() to return, and execute cleanups afterwards.

**Comment by dsoprea** [comment]
Yep. That's what I'm doing.

Can't hurt to add that note, for the APIs that it affects, to the documentation.
