### ISSUE TITLE
go 1.13 breaks loopbackFile writing to O_APPEND files

### ISSUE THREAD

**Issue by sb10** [hanwen/go-fuse#325]
`go-fuse/fuse/nodefs/files.go` has a `Write()` method that calls `os.File.WriteAt()`.

That was [changed](https://go.googlesource.com/go/+/c7f7f59368c3a964b8214018dc5100806b243938%5E%21/) in go v1.13 to return an error if the file was opened with O_APPEND.

I'm note sure how to work around this. Any ideas?

**Comment by sb10** [comment]
In the end I did this hack, which works:

```
--- a/fuse/nodefs/files.go
+++ b/fuse/nodefs/files.go
@@ -7,6 +7,7 @@ package nodefs
 import (
        "fmt"
        "os"
+       "strings"
        "sync"
        "syscall"

@@ -133,6 +134,9 @@ func (f *loopbackFile) Read(buf []byte, off int64) (res fuse.ReadResult, code fu
 func (f *loopbackFile) Write(data []byte, off int64) (uint32, fuse.Status) {
        f.lock.Lock()
        n, err := f.File.WriteAt(data, off)
+       if err != nil && strings.Contains(err.Error(), "os: invalid use of WriteAt on file opened with O_APPEND") {
+               n, err = f.File.Write(data)
+       }
        f.lock.Unlock()
        return uint32(n), fuse.ToStatus(err)
 }
```

**Comment by rfjakob** [comment]
I think the right thing to do is to not open the underlying file with O_APPEND.

**Comment by sb10** [comment]
@rfjakob Not sure I understand. This is a file system. How users use the file system is out of my control. Opening files in append mode is a quite normal thing for people to do.

**Comment by hanwen** [comment]
best if nodefs file implementations were changed to use syscalls directly. Or we could filter out O_APPEND from the incomign flags.

**Comment by rfjakob** [comment]
To be honest, i'm not completely sure what the semantics of a fuse WRITE are supposed to be on a file opened in O_APPEND.

Filtering out O_APPPEND (as i also suggested above) makes appending to files racy

**Comment by hanwen** [comment]
I hope the FUSE kernel code would do the work of translating appending write calls to the right offsets.

**Comment by rfjakob** [comment]
I don't see how this could possibly work with concurrent writes & truncates

**Comment by hanwen** [comment]
per man page:

      O_APPEND
              The file is opened in append mode.  Before  each  write(2),  the
              file  offset  is  positioned  at the end of the file, as if with
              lseek(2).  The modification of the file offset and the write op‐
              eration are performed as a single atomic step.


I think you can do concurrent append writes, and I'd expect that this is a typical way to write log files.

**Comment by rfjakob** [comment]
For FUSE filesystems, this means the kernel has to do

1) GETATTR # find file size
2) WRITE # write there

My concern was that the file size may change between GETATTR and WRITE. But yes, in-kernel filesystems have the same problem. And it seems to be solved somehow, as appending to log files concurrently works fine.

After re-reading my own code, gocryptfs filters out O_APPEND, and it works fine. So there seems to be locking before the GETATTR.

**Comment by rfjakob** [comment]
No, sorry, gocryptfs does its own per-inode-number locking because I never found out if the kernel actually guarantees that are no concurrent writes. Would be interesting to disable the extra locking and see if xfstests explodes.

**Comment by hanwen** [comment]
@sb10 - Sendu,  can you try out https://review.gerrithub.io/c/hanwen/go-fuse/+/473409/1 ?

you can download it with

   git fetch "https://review.gerrithub.io/hanwen/go-fuse" refs/changes/09/473409/1 && git checkout FETCH_HEAD

please let me know if it fixes the problem.

**Comment by sb10** [comment]
Using commit d1b56cc4b9d6 did not solve my problem, because I don't call `*loopbackFileSystem.Open()` but do essentially the same thing in one of my own methods, opening a file and then calling `nodefs.NewLoopbackFile(localFile)`.

Anyway, I tried adding the same filter as in your commit to my own code but that just breaks everything. Presumably because the file that was supposed to be opened with O_APPEND no longer is.

How could your commit be expected to work correctly?

**Comment by sb10** [comment]
The bug here is that if a file is opened with O_APPEND, writing fails.
Your solution is to silently ignore O_APPEND, so that files are opened in some other mode (RW? R? nothing??).
Obviously that will have disastrous consequences when writes are attempted and assumed to be going on the end of the file.

BTW, your travis tests are not configured to test with go v1.13, and your tests are failing on most of the versions of go you test with.

**Comment by hanwen** [comment]
it would be helpful if you can provide a unittest that proves that these semantics are wrong,

as it stands, [this test](https://github.com/hanwen/go-fuse/commit/d1b56cc4b9d670064defab62857ef930e350a10a#diff-1e2b34d70e59d44a2bedcafc2e34eaad) is passing, so I think this is correct. If this is failling for you, or if you can construct some other test where a FUSE file system doesn't behave as expected, I'd love to hear about it.

**Comment by sb10** [comment]
Instead of my hack that tests for the failure of `WriteAt()`, or your solution that ignores O_APPEND, it would be best to store the fact that the file was opened with O_APPEND, and then call `Write()` instead of `WriteAt()`.
For users who open their own files and do `nodefs.NewLoopbackFile(localFile)`, there should be a public way of setting that the file was opened with append.

I'll try and come up with a test.

**Comment by hanwen** [comment]
thanks for your suggestions, I'll think about it. 

random thoughts:

* backward compatibility: given the golang bug discussion, it's obvious that this behavior has been broken in go-fuse too, since O_APPEND on OSX vs Linux would give different results. 

* the new fs/ package has the intention of closely following the system call interface, so it should not do magic things like filtering out flags. I'll revert that part.

* if we add a method for users to signal the mode that the file was opened, then that will require action from users, and potentially breaks backward compatibility. Maybe we can get the current flags of the FD using ioctl or fcntl?

all-in-all, it was a mistake to involve the os package here. The os package tries to provide a system independent layer over system calls, but we want to be close to the system here.

**Comment by sb10** [comment]
(Running your whole test suit fails for me, either with a number of fails on one machine, or 1 failure and then hanging on a different machine.)

Just the test of interest passes:

```
git checkout d1b56cc4b9d670064defab62857ef930e350a10a
go test -count 1 -run TestPosix -v ./fuse/test
[...]
--- PASS: TestPosix (0.60s)
    --- PASS: TestPosix/SymlinkReadlink (0.08s)
    --- PASS: TestPosix/MkdirRmdir (0.07s)
    --- PASS: TestPosix/RenameOverwriteDestNoExist (0.08s)
    --- PASS: TestPosix/RenameOverwriteDestExist (0.08s)
    --- PASS: TestPosix/ReadDir (0.16s)
    --- PASS: TestPosix/ReadDirPicksUpCreate (0.06s)
    --- PASS: TestPosix/AppendWrite (0.07s)
PASS
ok  	github.com/hanwen/go-fuse/v2/fuse/test	0.610s
```

BTW, your `AppendWrite()` isn't strictly speaking testing appending, since you're really creating the file, and the O_APPEND is ignored anyway?

A clearer test would be:

```
func AppendWrite(t *testing.T, mnt string) {
	content := []byte("hello")
	fn := mnt + "/file"

	if err := ioutil.WriteFile(fn, content, 0755); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	fd, err := syscall.Open(fn, syscall.O_WRONLY|syscall.O_APPEND, 0644)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer func() {
		if fd != 0 {
			syscall.Close(fd)
		}
	}()
	if _, err := syscall.Write(fd, []byte("world")); err != nil {
		t.Fatalf("Write 1: %v", err)
	}

	if err := syscall.Close(fd); err != nil {
		t.Fatalf("Open: %v", err)
	}
	fd = 0
	want := []byte("helloworld")

	got, err := ioutil.ReadFile(mnt + "/file")
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	if bytes.Compare(got, want) != 0 {
		t.Errorf("got %q want %q", got, want)
	}
}
```

But that also passes. I confirmed that it fails if I remove your filters. Somehow I'm doing something significantly different to your tests to get failures. I'll look in to things on my end some more.
