### ISSUE TITLE
v2 API: making filesystem read only?

### ISSUE THREAD

**Issue by ukai** [hanwen/go-fuse#327]
Any good way to make read only filesystem in v2 fs API, something like pathfs.NewReadonlyFileSystem?

wrapping InodeEmbedder with methods that returns EROFS for write operations doesn't work well.
e.g. wrapping InodeEmbedder created by fs.NewLoopbackRoot would cause panic with
```
panic: interface conversion: fs.InodeEmbedder is main.ReadOnlyInodeEmbedder, not *fs.loopbackRoot
```

**Comment by hanwen** [comment]
There is no special mechanism. If you don't implement methods you'll get
the default which is a read only filesystem, but with error code enotsupp.
Other than that you'll have to catch attempts to write data.

Op ma 28 okt. 2019 07:27 schreef Fumitoshi Ukai <notifications@github.com>:

**Comment by rfjakob** [comment]
You can also mark the filesystem as "ro" to the kernel by appending `ro` to `MountOptions.Options`, like this:
https://github.com/hanwen/go-fuse/blob/17c7e2cd98b3e0a70d7bca872c132a3a468041f6/example/loopback/main.go#L93

The kernel will block any write requests before they even reach FUSE.
