### ISSUE TITLE
Direct io writes got an error

### ISSUE THREAD

**Issue by jack0liu** [hanwen/go-fuse#328]
When useing `fio` test go-fuse with flag `-direct=1`, there will be an error "22=invalid argument", debug info is here

```
19:45:52.449459 rx 9: LOOKUP i1 ["test.txt"] 10b
19:45:52.449559 tx 9:     OK, {i820741 g1 tE=1s tA=1s {M0100600 SZ=1048576 L=1 0:0 B2048*4096 i0:820741 A 1572434644.319000 M 1572435532.351000 C 1572435532.351000}}
19:45:52.645634 rx 10: OPEN i820741 {**DIRECT**,RDWR,0x8000}
19:45:52.645674 tx 10:     OK, {Fh 1 }
19:45:52.646063 rx 11: GETXATTR i820741 {sz 0} ["security.capability"] 20b
19:45:52.646078 tx 11:     61=no data available
19:45:52.646138 rx 12: WRITE i820741 {Fh 1 [0 +65536) LOCKOWNER L 7204619708509661410 RDWR,DIRECT,0x8000}  65536b
19:45:52.646159 tx 12:     **22=invalid argument**
19:45:52.646284 rx 13: FLUSH i820741 {Fh 1}
19:45:52.646301 tx 13:     OK
19:45:52.646320 rx 14: RELEASE i820741 {Fh 1 DIRECT,RDWR,0x8000 0x2 L8374468906798491651}
19:45:52.646330 tx 14:     OK
```

**Comment by hanwen** [comment]
which file system are you testing?

**Comment by jack0liu** [comment]
loopback fs in example

**Comment by hanwen** [comment]
1) can you provide a complete command line?

[hanwen@localhost y]$ fio -direct=1
No job(s) defined
..


2) can you confirm that the underlying FS actually supports direct I/O ? open(2) says:

       EINVAL The filesystem does not support the O_DIRECT flag.  See NOTES for more information.

**Comment by jack0liu** [comment]
ok, i test fio with full command as below:

```
fio -filename=./test.txt -direct=1 -iodepth=1 -rw=randwrite -ioengine=libaio -bs=4K -runtime=3000 -name=mytest -size=2G
```

and i confirm underlying FS is ext4，that supports direct I/O

**Comment by jack0liu** [comment]
I add some fix code in my local repo, it works with direct io, but i'm not sure if i can submitted these code . 

Fix codes:  alloc readPool `NewServer` function in server.go, 
```
	ms.readPool.New = func() interface{} {
		poolSize := o.MaxWrite+pageSize
		wInSize := int(unsafe.Sizeof(WriteIn{}))
		buf := make([]byte, poolSize + blockSize)
		left := align(buf[wInSize:])
		offset := 0
		if left != 0 {
			offset = blockSize - left
		}
		buf = buf[offset:poolSize+offset]
		return buf
	}
```
add new `align` function in server.go, 
```
const blockSize = 512
func align(data []byte) int {
	return int(uintptr(unsafe.Pointer(&data[0])) & uintptr(blockSize-1))
}
```

**Comment by hanwen** [comment]
thanks for the detailed diagnosis! Yes, if direct IO requires aligned memory blocks, something like this would be needed.  

Let me see if I can come up with a unittest and a tweak to the block allocation to fix this.

**Comment by hanwen** [comment]
I came up with this: https://review.gerrithub.io/c/hanwen/go-fuse/+/473391/1

You can get it through: 

git fetch "https://review.gerrithub.io/hanwen/go-fuse" refs/changes/91/473391/1 && git checkout FETCH_HEAD

can you have a look at TestOpenDirectIO (fs/simple_test.go) ?

the Open/Write/Read calls seem to work when running against ext4, but I don't get back the data that I read, so somethign seems off.
