### ISSUE TITLE
Out of bounds array access in fs.rawBridge.Setattr()

### ISSUE THREAD

**Issue by EdSchouten** [hanwen/go-fuse#329]
On macOS + OSXFUSE, I have observed that `fuse.SetAttrIn.Fh` is not guaranteed to be zero when `in.Valid&fuse.FATTR_FH == 0`. This causes `fs.rawBridge.Setattr()` calls `b.inode()` with an arbitrary value. This in turn causes out of bounds array access in that function.

**Comment by hanwen** [comment]
https://review.gerrithub.io/c/hanwen/go-fuse/+/473688
