### ISSUE TITLE
InodeEmbedder's embed() function makes it impossible to do anything other than embedding fs.Inode directly

### ISSUE THREAD

**Issue by EdSchouten** [hanwen/go-fuse#330]
Consider the case where one writes a general purpose (non-FUSE) in-memory file system:
```go
type Directory struct {
    ...
}
// Functions that have a non-FUSE 'native' API.
func (d *Directory) Mkdir(name string) error { ... }
...
```
And one decides to expose this file system through FUSE as well. Because Go doesn't support function name overloading or Rust-style traits, you end up with the problem that you can't let Directory implement fs.NodeMkdirer due to naming collisions. To solve this you decide to implement a separate adapter-like type with the FUSE methods:
```go
type DirectoryFUSENode struct {
    d *Directory
}
// Functions that have a go-fuse API.
func (d *DirectoryFUSENode) Mkdir(ctx context.Context, name string, mode uint32, out *fuse.EntryOut) (*fs.Inode, syscall.Errno) { ... }
```
Because there should only be up to one fs.Inode per Directory, and because Directory likely needs to call into fs.Inode to do things like invalidation, you decide to embed fs.Inode in Directory:
```go
type Directory struct {
    fuseInode fs.Inode
    ...
}
```
This should be all right, as long as DirectoryFUSENode still implements fs.InodeEmbedder. But here's the problem: fs.InodeEmbedder contains an unexported method named embed(). [This means the interface can only be satisfied by using anonymous structure fields.](https://stackoverflow.com/questions/26181271/is-it-possible-to-implement-an-interface-with-unexported-methods-in-another-pack)

Considering that `embed()` does exactly the same thing as `EmbeddedInode()`, would it make sense to eliminate it entirely?

**Comment by hanwen** [comment]
why don't you embed fs.Inode inside DirectoryFUSENode ?

the embed() method is specifically there so I can be sure that the user supplied node maps 1-to-1 to a fs.Inode, and that the Inode is the one embedded in the user-node.

**Comment by EdSchouten** [comment]
The issue here is that DirectoryFUSENode objects are created on demand. There may be zero DirectoryFUSENodes for directories that are not being looked up at all (good), but there may also be multiple in case of concurrent lookups (bad). But you're right, I could prevent this by doing something like this:

```go
type Directory struct {
    fuseNode DirectoryFUSENode
}

type DirectoryFUSENode struct {
    fs.Inode
}
```

That said, there is also a second, maybe even more important reason why I stumbled upon this issue. By having unexported methods in there, it is also harder to unit test file systems implemented on top of go-fuse. If `embed()` wasn't there, people could create their own interface of the parts of go-fuse they use:

```go
type GoFUSEInode interface {
    EmbeddedInode() *fs.Inode
    NotifyEntry(name string) syscall.Errno
}

type DirectoryFUSENode struct {
    GoFUSENode
}
```

And then use [gomock](https://github.com/golang/mock) to generate a mock of `GoFUSENode` to unit test their implementation.

**Comment by hanwen** [comment]
I'd consider that a feature: I think tests with mocks are an antipattern.

Filesystems have a very well defined API, the linux/posix spec, and you should just test filesystems by executing filesystem operations on the mount. It's best to test with race-detector, as filesystem are always parallel in practice.

**Comment by EdSchouten** [comment]
That's a pity. So far I'm really enjoying the mock-based unit tests I wrote, for the reason that they can easily be run on separate infrastructure that doesn't ship with FUSE (CI systems) or doesn't permit it (Unprivileged Docker containers spawned by a CI system).

**Comment by hanwen** [comment]
You can set up Inodes without a mount, by calling NewNodeFS().

You can then trigger operatiosn by calling the fuse.RawFileSystem methods. 

We could add some scaffolding such that you can intercept the notify functions. How does that sound?

**Comment by EdSchouten** [comment]
That would be nice. Thanks!
