### ISSUE TITLE
Under which conditions is it safe to call fs.Inode.{Notify*,ReadCache}()?

### ISSUE THREAD

**Issue by EdSchouten** [hanwen/go-fuse#334]
The `fs.Inode.{Notify*,ReadCache}()` functions all [assume `n.bridge != nil`](https://github.com/hanwen/go-fuse/blob/c4765ac768cb32996c8cc6b95462b5c8a48f592d/fs/inode.go#L690-L723). In the case of dynamically discovered file systems, it may well be the case that nodes in a tree contain `fs.Inode` objects that are still default initialised (i.e., not having `initInode()` called on them), meaning you will trigger nil pointer dereferences when calling these functions.

Could the documentation be extended to clarify which prerequisites need to be satisfied before calling these functions? Alternatively, maybe these functions may be extended to be no-ops when `n.bridge == nil`.

Relatedly, I have a question about the ordering/consistency between Lookup() and NotifyEntry(). Assume an implementation of a directory that is mutated both through go-fuse and some alternative means. If go-fuse calls Lookup() on a file that is about to be deleted, the following sequence of calls may happen:

- go-fuse calls fs.NodeLookuper.Lookup("foo") and obtains a reference to the file, right before it gets deleted.
- The goroutine gets suspended.
- Some other goroutine deletes file "foo" from the directory and calls NotifyEntry("foo").
- The kernel gets notified of the file's deletion.
- The original goroutine resumes and returns the inode of the -- now deleted -- file to the kernel.

Am I correct that this may occur in the current design? Would this be a problem? Also, is it even somewhat feasible to fix this? Maybe `fs.rawBridge.Lookup()` and `Notify*()` should pick up some per-inode lock to ensure consistency?

**Comment by hanwen** [comment]
NewInode only delivers fully formed inodes, so you should be able to avoid creating half-initialized structures by simply do not handing out data before you called NewInode on them. After NewInode is called it is safe to call operations.

re. lookup / delete: it's not altogether clear why your situation would be a problem. Similar scenarios are allowed for network file systems too (eg. NFS).

If you are worried about your filesystem not being full-fidelity posix compliant, you would have to tie the Lookup to acquiring a file handle from your backend. Deleting a file normally removes the path to a file, but file handles remain valid even if there are no directory entries pointing to the file.

**Comment by hanwen** [comment]
I don't know which ReadEvent function you're referring to.

**Comment by EdSchouten** [comment]
Errr... ReadCache. Fixed!

**Comment by hanwen** [comment]
I don't think there is anything left to comment here. Please file a new issue if there are questions.
