### ISSUE TITLE
[question] why  nodefs is high level?

### ISSUE THREAD

**Issue by caiwk** [hanwen/go-fuse#335]
I saw comment in nodefs package as  below: 
The nodefs package offers a high level API that resembles the
 kernel's idea of what an FS looks like.
Is nodefs not a low level implementation of fuse?

**Comment by rfjakob** [comment]
Yes this library implements the low-level parts of FUSE, but it gives the user a friendly interface, which is what is called "high-level" here.

**Comment by caiwk** [comment]
thx
