### ISSUE TITLE
Windows Support Discussion

### ISSUE THREAD

**Issue by DavidVorick** [hanwen/go-fuse#340]
What's the current status of supporting Windows? What's the reason that windows isn't currently supported? What's the amount of effort required to get Windows support? Is there any intention at this point to support windows in the near or distant future?

Our application would like to support Windows for fuse, even if it requires having our users download external programs or even compatibility layers, trying to get a sense of what the options are.

It it's not a ton of work, there's a chance our team would look at trying to add windows support here ourselves, though we'd need a much better understanding of what we are getting ourselves into first.

**Comment by rfjakob** [comment]
So there's two implementations of FUSE-like kernel module for Windows that I'm aware of: https://github.com/billziss-gh/winfsp and https://github.com/dokan-dev/dokany .

Getting go-fuse to work on Windows means finding a way to interface with one of those guys.

**Comment by hanwen** [comment]
I think this can never work. Both winfsp and dokany have an API that is specified in terms of file names, rather than Linux' lookup-inode based mechanics.

**Comment by dertuxmalwieder** [comment]
WinFsp comes with a FUSE compatibility layer though. I'm playing with WinFsp right now, and porting my (now working ;-)) file system over from macOS looks like it would be sufficient to port types_darwin.go to types_windows.go...?

    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:218:41: undefined: GetAttrIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:219:41: undefined: SetAttrIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:222:39: undefined: MknodIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:246:42: undefined: SetXAttrIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:252:40: undefined: CreateIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:254:38: undefined: ReadIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:263:39: undefined: WriteIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:272:41: undefined: ReadIn
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\types.go:550:2: undefined: Attr
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\types.go:578:2: undefined: Attr
    C:\Users\tux0r\go\pkg\mod\github.com\hanwen\go-fuse\v2@v2.0.3\fuse\api.go:272:41: too many errors

**Comment by sanwan** [comment]
@dertuxmalwieder hi，do you solve this problem?I have the same problem

**Comment by dertuxmalwieder** [comment]
I have solved it by ditching Windows support.
