### ISSUE TITLE
[v2 API] xfstests generic/257 fails (getdents seek trouble)

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#344]
xfstests generic/257 calls getdents and tries to seek to all directory offsets.

```
fuse-xfstests$ sudo ./check-loopback generic/257
[sudo] password for jakob: 
fuse-xfstests gocryptfs-2018-08-18/6471488e
Fri 27 Dec 2019 07:04:44 PM UTC

loopback is /usr/local/bin/loopback
FSTYP         -- fuse.loopback
PLATFORM      -- Linux/x86_64 brikett 5.3.12-300.fc31.x86_64
MKFS_OPTIONS  -- /var/tmp/fuse-xfstests/check-loopback/scratchdev
MOUNT_OPTIONS -- -o context=system_u:object_r:root_t:s0 /var/tmp/fuse-xfstests/check-loopback/scratchdev /var/tmp/fuse-xfstests/check-loopback/scratchdir

generic/257	- output mismatch (see /home/jakob.donotbackup/code/fuse-xfstests/results//generic/257.out.bad)
    --- tests/generic/257.out	2018-01-20 14:29:39.090452011 +0100
    +++ /home/jakob.donotbackup/code/fuse-xfstests/results//generic/257.out.bad	2019-12-27 20:04:56.317648932 +0100
    @@ -1,2 +1,339 @@
     QA output created by 257
    +getdents returned 0 on entry 169
    +entry 169 has inode 4333821, expected 4333872
    +getdents returned 0 on entry 168
    +entry 168 has inode 4333821, expected 4333962
    +getdents returned 0 on entry 167
    +entry 167 has inode 4333821, expected 4333952
    ...
    (Run 'diff -u tests/generic/257.out /home/jakob.donotbackup/code/fuse-xfstests/results//generic/257.out.bad'  to see the entire diff)
Ran: generic/257
Failures: generic/257
Failed 1 of 1 tests

Runtime was 12 seconds, exit code 1
```

**Comment by rfjakob** [comment]
The C program that does the actual testing is [t_dir_offset2.c](https://github.com/rfjakob/fuse-xfstests/blob/gocryptfs-2018-08-18/src/t_dir_offset2.c) . It calls `lseek` on the directory and then `getdents`.

The `lseek` translates into the next READDIRPLUS call having the requested offset.

Looking at the go-fuse code, reading from a specific directory offset is just not implemented. I'll try to come up with a poor-man's solution for now that skips over the directory entries until the requested offset is found.

**Comment by hanwen** [comment]
are you sure this is supposed to work?

**Comment by rfjakob** [comment]
Yes I think so - it works for gocryptfs which still uses the v1 API ( https://travis-ci.com/rfjakob/fuse-xfstests/jobs/270447743#L1574 )

**Comment by hanwen** [comment]
the alternative is to update the DirStream interface so that it supports lseek. This probably more consistent with the idea to keep close to the syscall interface

**Comment by rfjakob** [comment]
Maybe as an additional interface `DirSeeker` ? If not implemented we can fall back to skipping through the list.

**Comment by rfjakob** [comment]
Care to take a look at https://review.gerrithub.io/q/owner:jakobunt%2540gmail.com+is:open ?

**Comment by hanwen** [comment]
I should set up an email notification :P

**Comment by rfjakob** [comment]
No worries, I guess I should have clicked "request review"
