### ISSUE TITLE
[v2 API] fs.Mount() vs server.Wait() race

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#345]
`fs.Mount()` spawns a new goroutine that calls `wg.Add()`. Because it is a new goroutine, this executes concurrently with `server.Wait()` that calls `wg.Wait()`.

So we have `wg.Add()` and `wg.Wait()` executing concurrently, and, depending on who is faster, `wg.Wait()` may return immediately.

Found with the race detector like this:

```bash
$ go install -race ./example/loopback
```

Then run xfstests. Result at mount:

```
WARNING: DATA RACE
Write at 0x00c0000da134 by main goroutine:
  sync.(*WaitGroup).Wait()
      /usr/local/go/src/internal/race/race.go:41 +0xee
  main.main()
      /home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:391 +0x7d6

Previous read at 0x00c0000da134 by goroutine 8:
  sync.(*WaitGroup).Add()
      /usr/local/go/src/internal/race/race.go:37 +0x18d
  github.com/hanwen/go-fuse/v2/fuse.(*Server).Serve()
      /home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:363 +0x67

Goroutine 8 (running) created at:
  github.com/hanwen/go-fuse/v2/fs.Mount()
      /home/jakob/go/src/github.com/hanwen/go-fuse/fs/mount.go:32 +0x10b
  main.main()
      /home/jakob/go/src/github.com/hanwen/go-fuse/example/loopback/main.go:113 +0x72a
```

**Comment by hanwen** [comment]
I think this might be a false positive. fs.Mount calls WaitMount which actually waits until the whole machinery has processed the poll hack.

**Comment by rfjakob** [comment]
No, WaitMount happens later, server.Wait() happens before that:
```
loopback.go:main()
-> fs.Mount()
  -> server.Wait()        -> go server.Serve()
   -> ms.loops.Wait()         -> ms.loops.Add(1)
```

**Comment by rfjakob** [comment]
No, I got this wrong. fs.Mount() does not return before WaitMount returns. Hmm.

**Comment by rfjakob** [comment]
False positive, I agree. Race detector cannot see that as the synchronization goes through FUSE.

**Comment by hanwen** [comment]
still, we need to somehow make this go away.

**Comment by hanwen** [comment]
I think we will need to add a  

  fs.ServeBackground()

or similar function that will do the wg.Add before spawning the goroutine.

**Comment by hanwen** [comment]
fixed by https://github.com/hanwen/go-fuse/commit/fe141f38f2b7598223935963e2916b0b9a609ccf
