### ISSUE TITLE
what  EnableLocks actually do

### ISSUE THREAD

**Issue by Sherlock-Holo** [hanwen/go-fuse#349]
I saw the `fuse.MountOptions` has a field `EnableLocks` with comment 

>  If set, ask kernel to forward file locks to FUSE

I wonder what it does actually, does it pass some option to kernel like `mount -o ro` ?

**Comment by hanwen** [comment]
see https://github.com/hanwen/go-fuse/blob/0f51f7080204d9b3bd69aad35135be935a6766ec/fuse/opcode.go#L94
