### ISSUE TITLE
Investigating a possible memory leak in lookup

### ISSUE THREAD

**Issue by pierreis** [hanwen/go-fuse#352]
I am currently investigating a possible memory leak in the `rawBridge.Lookup` method, causing the following allocation to appear in the profile (in my lookup implementation):

```
   20.90GB    20.90GB     83:   inode := fsNode{
         .          .     84:           dataID:       dataID,
         .          .     85:           relativePath: relativePath,
         .          .     86:           dataPath:     dataPath,
         .          .     87:           root:         n.root,
         .          .     88:   }
         .    10.61GB     89:   child := n.NewInode(ctx, &inode, stableAttrs)
         .          .     90:
         .          .     91:   return child, 0
```

Note that nothing is done for caching these nodes, and they are returned straight to the underlying `go-fuse` implementation.

The heap trace is the following:

![Heap trace](https://i.imgur.com/gpC3dG8.png)

My understanding is that of the approximately 30 GB generated from the Lookup method, 20 related to the `fsNode` struct, that is referenced from the `Inode`, and not garbage collected until the latter goes out of scope. I cannot figure out where the `Inode` could be retained.

The file system is mounted with the following options:

```
AttrTimeout: &time.Second,
EntryTimeout: &time.Second,
NegativeTimeout: nil,
MountOptions: {
  DisableXAttrs: true,
  IgnoreSecurityLabels: true,
  AllowOther: true,
  RememberInodes: false,
}
```

It looks like `go-fuse` is retaining this memory in `addNewChild`:

```
   31.85GB    31.85GB    120:         parent.setEntry(name, child)
```

Hence the question: I am trying to build a dynamically discoverable file system aggregating large numbers of inodes. I am not sure how to update the behavior of the library so that the tree is not kept in memory.

Looking at the code, it is not clear to me what the mechanism to evict inodes is -- it seems that as long as these root nodes are remembered somewhere, all their hierarchy will also be forever.

**Comment by hanwen** [comment]
have you tried to force the kernel to clear the inode cache?  

https://www.tecmint.com/clear-ram-memory-cache-buffer-and-swap-space-on-linux/

you want the dentry and inode cache.

**Comment by hanwen** [comment]
(the lifetime of the tree is controlled by the kernel)

**Comment by pierreis** [comment]
I just tried, it doesn't seem to have any impact at all on the running process unfortunately.

**Comment by hanwen** [comment]
you can try running the daemon with --debug. If you force the kernel cache flush, you should see a flurry of FORGET messages, that should cause the inodes to be dropped from the profile.

**Comment by pierreis** [comment]
I see forget coming from the kernel regularly, also when clearing the cache manually. My issue is that inodes do not seem to be garbage collected despite these requests.

**Comment by pierreis** [comment]
To be sure that the issue is related to go-fuse and not to my code, I did adjust the few methods I am implementing to use Bazil's FUSE library. I see no such memory issue, and the memory is stable over time, with the same workload. It would tend to indicate that there is indeed some memory leak in go-fuse preventing it from dereferencing nodes despite FORGET requests being received by the kernel, but I still cannot pinpoint where.

**Comment by hanwen** [comment]
thanks, that sounds worrying. I'll have a look into it.

**Comment by pierreis** [comment]
Thanks. I'll continue digging on my side. Please advise how I can assist you best.

**Comment by hanwen** [comment]
I added a test that verifies that it works as expected, and it passes over here. Can you check if this test works for you? https://github.com/hanwen/go-fuse/commit/18e94a3cf5c407c36de45f4f58d82ed62916ad6d

cd fs && go test -c && sudo ./fs.test -test.run TestForget -test.v

if you want to debug more deeply, you can do the same thing that the test does: drop the cache and, then len(rawBridge.nodes) should be 1.

IIRC bazil.org FUSE doesn't support readdirplus, so go-fuse will trigger different codepaths.

**Comment by pierreis** [comment]
Sounds great, I’ll do this and let you know.

**Comment by hanwen** [comment]
another avenue of investigation is disabling readdirplus, by removing _CAP_READDIRPLUS here

https://github.com/hanwen/go-fuse/blob/18e94a3cf5c407c36de45f4f58d82ed62916ad6d/fuse/opcode.go#L92

**Comment by pierreis** [comment]
I am trying various ways to understand what is happening here. I am starting to suspect that the leak-like appearance could be due to the way the go runtime hooks to its allocated memory combined with the kernel being lazy forgetting nodes.

The memory increase with Brazil's FUSE is much slower (probably due to a significantly lower memory size per inode), but nonetheless growing after a few days under sustained load.

I am currently integrating active eviction from the application using an LRU cache to try mitigate the issue (which is, AFAIK, the way it is handled in Ceph). I'll update as soon as I get more details on this.

**Comment by pierreis** [comment]
After extensive testing, it appears that the difference between `basil.org/fuse` and `go-fuse` boils down to executing on servers with a different setting for `vfs_cache_pressure`, which did cause the server running `basil.org/fuse` to forget nodes significantly more aggressively. When deployed with the same setting of `100`, the memory usage of both tends to increase due to the kernel tendency to retain cache.

Adding active notification to forget cache items helped keeping the memory usage stable over multiple hours. The test case you developed helped a ton in debugging this issue.

Appreciate the help immensely.

Closing this issue.
