### ISSUE TITLE
v2 api: readdir doesn't handle readdirplus overflow situations correctly (missing files!)

### ISSUE THREAD

**Issue by jtolds** [hanwen/go-fuse#353]
hello!

I have discovered that in some cases, go-fuse ignores items returned in NewListDirStream from NodeReaddirers. Here's an example:

https://gist.github.com/jtolds/a3f2bf35ccd27c6298afdac27894ac6e

If you run this program (with go-fuse v2.0.2), then inside the mountpoint `mnt` run `ls go/dist/1.13.3/doc/gopher`, `talks.png` doesn't show up! everything else does, though.

I've traced it down in debug logging to being that the ReadDirPlus code is deciding adding talks.png constitutes an overflow, but I don't know more about the code than that.

Why doesn't `talks.png` show up in the above case? everything else does.

**Comment by hanwen** [comment]
looks like the bug fixed by 1cb24af20040ac4571e6ee2b41b1322a2f9f8df3

can you try with current master?

**Comment by hanwen** [comment]
I pushed a v2.0.3 tag for your convenience.

**Comment by jtolds** [comment]
That fixed it, thanks
