### ISSUE TITLE
What is the set of Node.* interfaces required for a writable file system?

### ISSUE THREAD

**Issue by TACIXAT** [hanwen/go-fuse#358]
I see you must implement some interfaces otherwise it defaults to a read only file system. Is the set of (minimal or complete) interfaces documented anywhere?

Very nice library, happy to be doing this stuff in Go and not C 🙂

**Comment by hanwen** [comment]
there is no single answer. It depends on what type of writes you want to support.

**Comment by TACIXAT** [comment]
So will even implementing 1 write method make it not read only? 

I'm looking to copy in files to the root, then `touch` as a means  to notify the file system.

**Comment by rfjakob** [comment]
You will need at least CREATE and WRITE

**Comment by TACIXAT** [comment]
Very nice, I implemented a create function that does not work, but now it is writable. Thank you for the help!
