### ISSUE TITLE
How to block underlying file creation and redirect to something else?

### ISSUE THREAD

**Issue by TACIXAT** [hanwen/go-fuse#359]
I am trying to hijack file creation and instead create a directory. The directory will have a file `0` which is the intended file. 

I am mounting to an existing directory, `/tmp/ffs`.

```golang
func (r *FFSRoot) Create(ctx context.Context, name string, flags uint32, mode uint32, out *fuse.EntryOut) (*fs.Inode, fs.FileHandle, uint32, syscall.Errno) {
	fmt.Println(name)
	if !r.IsRoot() || strings.Contains(name, "/") {
		return nil, nil, 0, syscall.EPERM
	}

	d := r.NewInode(ctx, &fs.Inode{}, fs.StableAttr{Mode: fuse.S_IFDIR})

	f := d.NewInode(ctx, &FFSFile{
			Data: []byte{},
			Attr: fuse.Attr{
				Mode: 0444,
			},
		}, fs.StableAttr{Ino: 0})

	if ok := d.AddChild("0", f, true); !ok {
		return nil, nil, 0, syscall.EBADF
	}

	if ok := r.AddChild(name+"suffix", d, true); !ok {
		return nil, nil, 0, syscall.ENOTDIR
	} 

	for n, _ := range r.Children() {
		fmt.Println(n)
	}

	return f, nil, 0, 0
}
```

When I do something like `echo "hello" > /tmp/ffs/ey` I get `/tmp/ffs/ey -> hello, /tmp/ffs/eysuffix/0 -> hello`. 

Any idea how to block it from creating `/tmp/ffs/ey`?

**Comment by hanwen** [comment]
you can't. What you could do is to remove the "ey" file at some point (eg. when the file is closed) and use an entry notification to force the kernel to lookup the file again (so it will disappear.)
