### ISSUE TITLE
Add optional attr shortcut for readdirplus

### ISSUE THREAD

**Issue by pierreis** [hanwen/go-fuse#361]
Currently, the readdirplus implementation provides no simple way to pass attrs in the `DirStream`. This consequently requires potentially costly `lookup` calls that could be avoided altogether.

I am thinking about creating a merge request that would:

- Add an optional Attr field in DirEntry
- Update Readdirplus logic so that this field is used if provided, otherwise a lookup is performed

Do you think such a pull could be accepted?

**Comment by hanwen** [comment]
why do you think that a lookup is expensive, but providing an attr is cheap?

**Comment by pierreis** [comment]
Example:

When developing a loopback file system, the `ioutil.ReadDir` for example returns a list of `os.FileInfo`. In most cases, this is sufficient to answer the `lookup` query. Not being able to pass the information on lookup means potentially costly `stat` syscalls in lookup that would be unnecessary if we could pass this information right from the `readdir`.

**Comment by hanwen** [comment]
My recommendation is to not use ioutil.ReadDir. It is a convenient shortcut, but you pay for this convenience.  Have you considered https://pkg.go.dev/github.com/hanwen/go-fuse/fs?tab=doc#NewLoopbackDirStream ?

**Comment by pierreis** [comment]
Thanks for the suggestion, I'll look into it. Unfortunately, we are getting the information from an upstream service that we cannot really alter.

**Comment by hanwen** [comment]
You could get the data from your backend service, and then instantiate the nodes to go with the directly from your readdir function. See https://github.com/hanwen/go-mtpfs/blob/42254b1935eb89625d0c8b61bb8128db2cd3c22f/fs/fs.go#L421

**Comment by hanwen** [comment]
I'm going to close this. I don't see anything to be done here.
