### ISSUE TITLE
ReadDir firing multiple times after completion

### ISSUE THREAD

**Issue by glp-p4** [hanwen/go-fuse#367]
Thanks for the great work on this fuse library! I have been mostly figuring things out on my own, but I do have a question regarding readdir (using a raw filesystem). Specifically, I am not sure what to do when I have no more entries to provide. At the moment, I am just returning a fuse.OK status without calling the add functions (AddDirEntry or AddDirLookupEntry). This does eventually get me where I want to be, but I have noticed a few extra readdir calls with what appears to be an increasingly larger buffer:

2020/06/26 14:56:57 rx 13: READDIR i1 {Fh 0 [0 +838) } 
2020/06/26 14:56:57 tx 13:     OK,  96b data "\xff\xff\xff\xff\x00\x00\x00\x00"...
2020/06/26 14:56:57 rx 11: READDIR i1 {Fh 0 [3 +838) } 
2020/06/26 14:56:57 tx 11:     OK
2020/06/26 14:56:57 rx 12: READDIR i1 {Fh 0 [3 +1676) } 
2020/06/26 14:56:57 tx 12:     OK
2020/06/26 14:56:57 rx 5: READDIR i1 {Fh 0 [3 +3353) } 
2020/06/26 14:56:57 tx 5:     OK

So is there a different status or better way to let readdir know I am done and have no more entries?

Thanks in advance!
G

**Comment by hanwen** [comment]
never seen that. Can you check what happens if you do the same syscall against the provided examples?

**Comment by glp-p4** [comment]
Yeah, just tried the loopback example:
https://raw.githubusercontent.com/hanwen/go-fuse/master/example/loopback/main.go

And it does the same thing:
15:37:49.802610 rx 4: READDIR i1 {Fh 1 [0 +838) } 
15:37:49.802737 tx 4:     OK
15:37:49.802799 rx 5: READDIR i1 {Fh 1 [0 +1676) } 
15:37:49.802865 tx 5:     OK
15:37:49.802909 rx 2: READDIR i1 {Fh 1 [0 +3353) }

**Comment by rfjakob** [comment]
Isn't that the offset that is increasing?

**Comment by glp-p4** [comment]
No, the first number, 0, is the "offset" and the second is the "size" (of the buffer I assume).

**Comment by hanwen** [comment]
things look sane over here on linux. I'd blame it on OSX weirdness.

**Comment by glp-p4** [comment]
Ok, fair enough. Won't worry about it then because it eventually does the right thing and I plan to use it mostly on linux anyway.
