### ISSUE TITLE
Resource leaking after request processed and interrupted

### ISSUE THREAD

**Issue by davies** [hanwen/go-fuse#369]
For interrupted requests, the writing response could return ENOENT.

For example, when opening a file, the request could be interrupted by user, and a file is opened and OK returned to kernel. FUSE module find that the request is canceled (the unique is not found in processing queue), it return ENOENT to FUSE process. Since the response of OPEN is not handled by kernel, so kernel will never issue RELEASE to tell FUSE process to release underlying resources, which cause leaking.

What can we avoid the leaking?

**Comment by hanwen** [comment]
good question. I need to think a little about this

**Comment by hanwen** [comment]
returning ENOENT  is incorrect. If the request was interrupted, you can return EINTR to signal that the request was canceled, or you can return any other code to signal that you do not support interrupted requests. In that case, returning an OK status code would lead to an open file handle, which can be closed later on.
