### ISSUE TITLE
rename dir may cause other client path error

### ISSUE THREAD

**Issue by Victor1319** [hanwen/go-fuse#376]
By using fuse pathfs api, I implement a distribute file system. I found that, rename dir may cause other client building wrong path when visit child in this dir. this may be caused by multi-parent child.

`
func (n *pathInode) findChild(fi *fuse.Attr, name string, fullPath string) (out *pathInode) {
	if fi.Ino > 0 {
		n.pathFs.pathLock.RLock()
		r := n.pathFs.clientInodeMap[fi.Ino]
		if r != nil {
			out = r.node
			r.refCount++
			if fi.Nlink == 1 {
				log.Printf("Found linked inode, but Nlink == 1, ino=%d, fullPath=%q", fi.Ino, fullPath)
			}
		}
		n.pathFs.pathLock.RUnlock()
	}

	if out == nil {
		out = n.createChild(name, fi.IsDir())
		out.setClientInode(fi.Ino)
	} else {
		n.Inode().AddChild(name, out.Inode())
	}
	return out
}
`

**Comment by hanwen** [comment]
if you have multiple clients and a distributed FS, you need to do some sort of notification so other clients can see the updated state.
