### ISSUE TITLE
Question about enabling WRITEBACK_CACHE

### ISSUE THREAD

**Issue by glp-p4** [hanwen/go-fuse#380]
Hi, I just wanted to ask if there is an easy way to enable writeback caching in the kernel by setting the CAP_WRITEBACK_CACHE init flag? I am not clear on the best way to set this flag so that the capability will be enabled.

**Comment by hanwen** [comment]
Often, adding support for CAP_XXX needs tweaks to go-fuse as well (see eg. 1eca9006d0f2410c01fe65d69c536a36c146c460 for implementing locking). Otherwise, you could try patching opcode.go to return CAP_WRITEBACK_CACHE to see if this does what you want.

**Comment by glp-p4** [comment]
Ok, just wanted to make sure there wasn't some obvious hook or opportunity somewhere to be able to modify the flags before they were sent out to the kernel.
