### ISSUE TITLE
cp --preserve=timestamps yields invalid argument error

### ISSUE THREAD

**Issue by glp-p4** [hanwen/go-fuse#381]
On Linux with the latest release of go-fuse v2.
I am wondering if it is possible to get the following command to work:
```
$ cp --preserve=timestamps /foo bar
cp: preserving times for ‘bar/foo’: Invalid argument
```
I don't see any timestamp data available to the Create call, nor any attempts to call SetAttr appearing in the logs. Is this a mistake on my part, a limitation on fuse itself, or a limitation on go-fuse?

**Comment by hanwen** [comment]
works for me.

$ fusermount -u /tmp/x; go run ./example/loopback/main.go -debug  /tmp/x /tmp/orig/ 
..
$ cp --preserve=timestamps ipass.txt  /tmp/x/
..
0:15:52.586554 rx 36: CREATE n1 {0100640 [EXCL,CREAT,WRONLY,0x8000] (027)} ["ipass.txt"] 10b
20:15:52.586632 tx 36:     OK, {n2 g1 {M0100640 SZ=0 L=1 47210:89939 B0*4096 i0:12322661 A 1608146152.586054 M 1608146152.586054 C 1608146152.586054} &{1 0 0}}
..
20:15:52.587061 rx 46: WRITE n2 {Fh 1 [0 +39)  L 0 WRONLY,0x8000} "\n\nUserna"... 39b
20:15:52.587082 tx 46:     OK
20:15:52.587108 rx 48: SETATTR n2 {atime 1598295457.323212125, mtime 1574227779.897469408} 
20:15:52.587130 tx 48:     OK, {tA=0s {M0100640 SZ=39 L=1 47210:89939 B8*4096 i0:12322661 A 1598295457.323212 M 1574227779.897470 C 1608146152.586054}}

**Comment by glp-p4** [comment]
Ah, sorry, I was copying from one fuse mount to another and the issue is apparently not on the destination volume, but the source one. Any chance you you could try again, but copy file from your fuse filesystem to your normal filesystem?

**Comment by glp-p4** [comment]
Oops, apologies. I think I see the problem. There appears to be an issue with the timestamp values themselves. I think that is the most likely source of the issue. I will close this ticket for now and if I continue to see this behavior after I fix the timestamps, I will reopen it.
