### ISSUE TITLE
Question about caching of directory entries

### ISSUE THREAD

**Issue by glp-p4** [hanwen/go-fuse#382]
This is a general question, not a bug or issue, but I would be grateful for any insights on this topic.

I would like to be able to "prime" the kernel cache in advance so that reads on a given directory will already be cached before a read is performed. Furthermore, I would like to be able to add new entries to a directory I have already primed or read and have future directory reads to still use the kernel cache without calling ReadDir / ReadDirPlus.

In short, I want to minimize ReadDir / ReadDirPlus calls and maximize the use of the kernel cache. Presently, when OpenDir is called, I do provide the following open flags:
```
out.OpenFlags = fuse.FOPEN_KEEP_CACHE | fuse.FOPEN_CACHE_DIR
```
These help ensure that the second read on the (unchanged) directory are served from the kernel cache, but this approach doesn't seem to work if I happen add or remove entries, which leads to a new ReadDir / ReadDirPlus round.

Is there any way to manage the caching so that I can achieve my objective? Thanks in advance!

**Comment by hanwen** [comment]
not that I know. Maybe if you use FUSE_NOTIFY_STORE ? I'd ask on the fuse-devel list, where the kernel devs hang out. 

I'm closing this for now. If you discover something that should be supported in go-fuse, please reopen.
