### ISSUE TITLE
Panic on mknod if NodeMknoder isn't implemented

### ISSUE THREAD

**Issue by tomyl** [hanwen/go-fuse#387]
`rawBridge.Mknod` currently panics if `NodeMknoder` isn't implemented. PR #385 makes it return `ENOTSUP` instead.

If preferred I can push to Gerrit.

**Comment by hanwen** [comment]
yes, gerrit preferred.

**Comment by hanwen** [comment]
oops.

**Comment by tomyl** [comment]
Pushed https://review.gerrithub.io/c/hanwen/go-fuse/+/509897

**Comment by tomyl** [comment]
This was fixed in d46c63e8f33e79c89fcd95844218c5d20d2d0ded.
