### ISSUE TITLE
fusermount3 binary not supported

### ISSUE THREAD

**Issue by spinnau** [hanwen/go-fuse#394]
The name of the fusermount binary is hardcoded to `fusermount`in https://github.com/hanwen/go-fuse/blob/a90e1f463c3f172a7690a6449fe5955a180dfec3/fuse/mount_linux.go#L196-L197

On Arch Linux the names of the binary are `fusermount` for fuse2 and `fusermount3` for fuse3. It would be nice, if go-fuse could default to the newer version, if that is installed. That naming of the binaries is also used on Fedora and maybe on other Linux distributions.

Usecase: I'm using gocryptfs on USB-drives with exfat filesystems. For ease of use, I'm mounting gocryptfs directly on the exfat device. I would really like to use the new in-kernel exfat driver, as it is faster than the older fuse driver. However, mounting a fuse filesystem (e.g. the plain dir for gogyrptfs) on top of an exfat FS with the new kernel-driver is only possible with fuse3, as this FS is only whitelisted there (https://github.com/libfuse/libfuse/pull/573).

**Comment by rfjakob** [comment]
Note: this fuse whitelist only applies to the *mountpoint*. That means you can always mount to something like $HOME/mnt/foo .

**Comment by rfjakob** [comment]
https://review.gerrithub.io/c/hanwen/go-fuse/+/529698
