### ISSUE TITLE
fs.LoopbackNode show incorrect files

### ISSUE THREAD

**Issue by hanchaogit** [hanwen/go-fuse#401]
at the Fuse mount dir 

 stat src/conditions/BUILD
  文件："src/conditions/BUILD"
  大小：1257208   	块：2456       IO 块：4096   普通文件
设备：25h/37d	Inode：277081225585302  硬链接：1
权限：(0644/-rw-r--r--)  Uid：(    0/    root)   Gid：(    0/    root)
最近访问：2021-07-29 18:23:23.269204414 +0800
最近更改：2021-07-29 18:23:23.285204395 +0800
最近改动：2021-07-29 18:23:23.285204395 +0800
创建时间：-

but at the LoopbackRoot

stat src/conditions/BUILD
  文件："src/conditions/BUILD"
  大小：4059      	块：8          IO 块：4096   普通文件
设备：fc01h/64513d	Inode：418454      硬链接：1
权限：(0644/-rw-r--r--)  Uid：(    0/    root)   Gid：(    0/    root)
最近访问：2021-07-29 18:21:41.021317061 +0800
最近更改：2021-07-29 18:21:41.021317061 +0800
最近改动：2021-07-29 18:21:41.021317061 +0800
创建时间：-

they are different size . 
any clue how I can debug this case ?

most of files at Fuse mount dir are correct , only some of file have such issue.

**Comment by hanchaogit** [comment]
when I open the debug log got this .
2021/07/29 19:43:03 rx 31898: LOOKUP n1 ["src"] 4b
2021/07/29 19:43:03 tx 31898:     OK, {n78 g1 tE=0s tA=0s {M040644 SZ=4096 L=7 0:0 B8*4096 i0:277081225576981 A 1627557016.880668 M 1627557112.484506 C 1627557112.484506}}
2021/07/29 19:43:03 rx 31899: LOOKUP n78 ["conditions"] 11b
2021/07/29 19:43:03 tx 31899:     OK, {n35264 g1 tE=0s tA=0s {M040644 SZ=4096 L=2 0:0 B8*4096 i0:277081225585330 A 1627557099.600528 M 1627557371.224063 C 1627557371.224063}}
2021/07/29 19:43:03 rx 31900: LOOKUP n35264 ["BUILD"] 6b
2021/07/29 19:43:03 tx 31900:     OK, {n22362 g1 tE=0s tA=0s {M0100644 SZ=4059 L=1 0:0 B8*4096 i0:277081225585303 A 1627557099.680527 M 1627557099.680527 C 1627557099.680527}}
2021/07/29 19:43:03 rx 31901: GETATTR n22362 {Fh 0}
2021/07/29 19:43:03 tx 31901:     OK, {tA=0s {M0100644 SZ=1257208 L=1 0:0 B2456*4096 i0:277081225585303 A 1627557371.224063 M 1627557371.236063 C 1627557371.236063}}


why when LOOKUP n35264 ["BUILD"]. got correct Attr SZ=4059
when GETATTR got incorrect SZ=1257208

**Comment by rfjakob** [comment]
Are you on latest master? This may have been fixed by 

https://github.com/hanwen/go-fuse/commit/a90e1f463c3f172a7690a6449fe5955a180dfec3

**Comment by hanchaogit** [comment]
I use github.com/hanwen/go-fuse/v2 v2.1.0
and I will try the master version .

But I found same code with  github.com/hanwen/go-fuse/v2 v2.1.0 can run at other machine .
is there any other env or system packaged influencing factors

**Comment by hanchaogit** [comment]
works after upgrade the master version github.com/hanwen/go-fuse/v2 v2.1.1-0.20210611132105-24a1dfe6b4f8
