### ISSUE TITLE
Generation number isn't being used properly

### ISSUE THREAD

**Issue by akalin** [hanwen/go-fuse#41]
It looks like a new generation number generated for an inode whenever a child is added to it (NewChild). However, I don't think this is correct. This manifests itself in the following way (on OS X -- Linux seems to be more permissive):

Imagine a filesystem with a non-empty directory 'foo'. Let's say I do `rmdir foo`. go-fuse does a lookup on foo, and its inode gets a default generation number of 0. Everything works as expected, i.e. the filesystem returns ENOTEMPTY, which gets propagated to the kernel, and nothing is changed.

Now imagine that I then do `touch foo/bar`. The filesystem creates the file, etc., which ends up with the node of 'bar' being added to 'foo' via `(*Inode).NewChild()`. Then 'foo''s inode now has a non-zero generation number. Now if I try to do `rmdir foo` again, the filesystem returns ENOTEMPTY again, which gets propagated to the kernel properly, but then OSXFUSE gets confused by the new generation number and forgets the node ID (sending out a bunch of FORGET requests, too). Then trying to stat the file (or `ls` its parent directory) returns with a ESTALE error for 'foo' (with the message 'stale NFS handle').

According to http://ptspts.blogspot.com/2009/11/fuse-protocol-tutorial-for-linux-26.html , the generation number should be incremented only when a node ID is reused. Consulting another go implementation -- https://github.com/bazil/fuse/blob/3a76e04b5ed7533c3530ed338942b5daa13ba9c7/fs/serve.go#L427 -- that seems to be correct.

Taking a quick look at the code, I think the solution is to:

- Move the generation field from nodefs/FileSystemConnector to handleMap.
- Have handleMap.Register() return both the inode number and the generation number.
- Increment the generation number whenever Register() reuses a previously-used node ID.

**Comment by hanwen** [comment]
Your suggestion sounds reasonable.

I have never given the generation number much thought; the current scheme is an attempt to never issue the same node ID + generation number, so you can NFS mount a file system without clients confusing which inode they are accessing.

If you can you can maintain that property, that would be great.

**Comment by hanwen** [comment]
IIRC, the handlemap is used for file handles too, but I think you could just ignore the generation number in that case.

**Comment by hanwen** [comment]
fixed by https://github.com/hanwen/go-fuse/commit/92a4cb63d27d6abe68ead6ea9907dc0e7e1ee939
