### ISSUE TITLE
Spinlock causes system call time to grow.

### ISSUE THREAD

**Issue by tongtongtongtong** [hanwen/go-fuse#414]
In the case of readRequest and returnRequst function execution, 
because golang's sync.Mutex causes the operating system to spin lock, 
resulting in performance degradation.

**Comment by hanwen** [comment]
do you have a reproduction scenario?

**Comment by tongtongtongtong** [comment]
![image](https://user-images.githubusercontent.com/22701681/150765315-f02de6ec-6ec8-43e5-a823-1dcfeef2fa91.png)

When the compilation is started with fuse loopback mode, this is a screenshot of the command: perf top -p <pid> at that time.

**Comment by rfjakob** [comment]
Hmm, how does "perf top" look like on ext4?

**Comment by hanwen** [comment]
I had a look at this source code to refresh my memory, but I don't see much of a solution. Because we support request cancellation, we have to keep track of a centralized list of in-flight requests. This list is shared between the parts that read the fuse device (to add inflight requests) and the part that writes the response (to remove inflight requests).  I don't see how we can avoid synchronization here.

**Comment by tongtongtongtong** [comment]
I'm not sure whether the spinlock comes from the kernel layer or  from the golang sync.mutex used by the fuse driver.

When I use Fuse to mount the local disk, it takes time to execute：  43.4s.
When I use the local disk, it takes time to execute：  21.4s.

The following is the result of the func call when executed：
count func ( dir )
212705 readLink( build64_release )
  65068 readLink( thirdparty/java/default )
  28735 getattr( build64_release )
  17292 getattr( thirdparty/blade/blade.zip )
   7230 open( thirdparty/blade/blade.zip )

**Comment by hanwen** [comment]
It's expected that using FUSE introduces significant overhead, so your results aren't that surprising. Are these timings much different compared to the loopback filesystem from libfuse?

**Comment by tongtongtongtong** [comment]
I verified it with libfuse, it is a little faster, the time is 35.9s, but it is still a lot slower than the local disk.it seems that this problem is the normal loss of fuse.
Thank you.
