### ISSUE TITLE
Lseek default implementation should return the end of the file for SEEK_HOLE

### ISSUE THREAD

**Issue by pierreis** [hanwen/go-fuse#417]
Currently, the default Lseeker implementation for `SEEK_HOLE` returns the current position + offset. This can cause issues, such as causing `grep` to [consider a text file as binary](https://utcc.utoronto.ca/~cks/space/blog/linux/GrepBinaryFileReason).

From the [man page](https://man7.org/linux/man-pages/man2/lseek.2.html): _For the purposes of these operations, a hole is a sequence of zeros that (normally) has not been allocated in the underlying file storage. However, a filesystem is not obliged to report holes, so these operations are not a guaranteed mechanism for mapping the storage space actually allocated to a file. (Furthermore, a sequence of zeros that actually has been written to the underlying storage may not be reported as a hole.) In the simplest implementation, **a filesystem can support the operations by making SEEK_HOLE always return the offset of the end of the file**, and making SEEK_DATA always return offset (i.e., even if the location referred to by offset is a hole, it can be considered to consist of data that is a sequence of zeros)._

Can the default implementation of Lseek be updated to report the end of the file on `SEEK_HOLE`?

**Comment by hanwen** [comment]
this is about

```
	if in.Whence == _SEEK_DATA || in.Whence == _SEEK_HOLE {
		out.Offset = in.Offset
		return fuse.OK
	}
```

this is probably posix behavior, so should add a test under `test/`.
