### ISSUE TITLE
Get a error (out.Blksize undefined (type *fuse.AttrOut has no field or method Blksize) ) when run zipfs.TestZipFs()

### ISSUE THREAD

**Issue by codeboytj** [hanwen/go-fuse#421]
![image](https://user-images.githubusercontent.com/18275952/160070704-aeafde5c-0c15-4c7d-901c-fa76f867365e.png)

**Comment by hanwen** [comment]
the uint16 / uint32 confusion has been fixed. 

I can't repro the Blksize problem. `Attr` has Blksize on both darwin and linux.
