### ISSUE TITLE
Future-proof fusermount{3, 4, 5,...} call

### ISSUE THREAD

**Issue by probonopd** [hanwen/go-fuse#422]
Current behavior:
* Check for `fusermount3`,
* Fall back to `fusermount`

Suggested behavior:
* Check for `fusermountN` with `N`= any integer and use the highest one
* fall back to `fusermount`

Advantage:
Exisitng binaries will continue to work once there will be `fusermount4` instead of `fusermount3`.

https://github.com/hanwen/go-fuse/blob/934a183ed91446d218b5471c4df9f93db039f6e1/fuse/mount_linux.go#L225-L232

References:
* https://github.com/libfuse/libfuse/issues/670
* https://github.com/AppImage/AppImageKit/issues/877
* https://github.com/probonopd/static-appimage/issues/4

**Comment by hanwen** [comment]
If fusermount4 introduces a new calling convention (typically, this is what you introduce a new version number for!), then this would fail in mysterious ways, so I think this is best left alone.
