### ISSUE TITLE
With Samba, the directories that FUSE mounts are not visible， why？

### ISSUE THREAD

**Issue by xhbase** [hanwen/go-fuse#424]
A has two subdirectories B and C, which are shared by Samba and visible on Windows.  
 
If mounted to B by fuse, B will disappear on Windows and only C will be visible.

**Comment by xhbase** [comment]
Have you ever encountered this problem? @hanwen

**Comment by hanwen** [comment]
https://superuser.com/a/795482

**Comment by xhbase** [comment]
example code：https://pkg.go.dev/github.com/hanwen/go-fuse/v2@v2.1.0/fs#example-package-HandleLess

```
func main() {
	mntDir := "/example1/mount/"
	if len(os.Args) > 1 {
		mntDir = os.Args[1]
	}

	root := &fs.Inode{}

	// Mount the file system
	server, err := fs.Mount(mntDir, root, &fs.Options{
		MountOptions: fuse.MountOptions{Debug: false, AllowOther: true},

		// Setup the file.
		OnAdd: func(ctx context.Context) {
			ch := root.NewPersistentInode(
				ctx,
				&bytesNode{},
				fs.StableAttr{
					Mode: syscall.S_IFREG,
					// Make debug output readable.
					Ino: 2,
				})
			root.AddChild("bytes", ch, true)
		},
		UID: 100,
		GID: 101,
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf(`Try:

  cd %s
  ls -l bytes
  echo hello > bytes
  ls -l bytes
  cat bytes
  cd -

`, mntDir)
	fmt.Printf("Unmount by calling 'fusermount -u %s'\n", mntDir)

	// Serve the file system, until unmounted by calling fusermount -u
	server.Wait()
}
```

Results seen in the Samba container:
```
bash-5.1# mount|grep mount
rawBridge on /example1/mount type fuse.rawBridge (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
bash-5.1# ls -l /example1/
total 4
drwxr-x---    2 smbuser  smb           4096 May 12 06:48 m-test
drwxr-xr-x    0 smbuser  smb              0 Jan  1  1970 mount
bash-5.1# ls -l /example1/mount/
total 0
-rw-r--r--    0 smbuser  smb              0 Jan  1     1 bytes
```

Results seen on Windows:  
![image](https://user-images.githubusercontent.com/8764621/168009108-c5c9ff96-0bec-4541-a349-0053e97e3cf8.png)


On Windows, you see a file, not directories.  

Why do directories on Linux see files on Windows?

**Comment by hanwen** [comment]
I don't know. I've never tried this. Does it work as expected when you use an example file system from the original libfuse package?

**Comment by xhbase** [comment]
> I don't know. I've never tried this. Does it work as expected when you use an example file system from the original libfuse package?

The use of Libfuse is as follows:
```
[root@EulixOS example]# mount|grep libfuse
/root/fuse/libfuse/libfuse-fuse-3.11.0/example/hello on /example1/mount type fuse.hello (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
[root@EulixOS example]# ll /example1/      
total 4.0K
drwxr-xr-x 2 root     root        0 Jan  1  1970 mount
drwxr-xr-x 2 example1 example1 4.0K May 13 08:15 test
-rwxr--r-- 1 example1 example1    0 May 13 08:29 test2.txt
[root@EulixOS example]# ll /example1/mount/
total 0
-r--r--r-- 1 root root 13 Jan  1  1970 hello
[root@EulixOS example]# cat /example1/mount/hello 
Hello World!
```
![image](https://user-images.githubusercontent.com/8764621/168200446-6c8b00b6-692e-4eed-b42b-f6c38f5061d8.png)

![image](https://user-images.githubusercontent.com/8764621/168200526-bbd6b792-1a5f-4e3a-9893-132f742f0500.png)

The example test using LibfUse looks fine, no more problems.

**Comment by xhbase** [comment]
Thanks for your advice, this issue will be closed first. @hanwen

**Comment by JoKr4** [comment]
I had the same problem with [cgofuse](https://github.com/winfsp/cgofuse)

Please have a look at [my PR there](https://github.com/winfsp/cgofuse/pull/81)

I didnt found a way in go-fuse to add the nlink attribute, so just take this as a hint

**Comment by hanwen** [comment]
the `Attr` type has an `Nlink` field.
