### ISSUE TITLE
Splice support

### ISSUE THREAD

**Issue by codeboytj** [hanwen/go-fuse#430]
Does go-fuse support write_buf method? 

We need use splice to improve the write method performance.

![image](https://user-images.githubusercontent.com/18275952/173034702-75f22e3d-6479-4521-96cc-3a670706651a.png)

https://www.usenix.org/system/files/conference/fast17/fast17-vangoor.pdf

**Comment by rfjakob** [comment]
Have you tried searching for the word "splice" in the source code?

Like this? https://github.com/hanwen/go-fuse/search?q=splice

**Comment by codeboytj** [comment]
> 

Yes, but didn't what I want.

**Comment by hanwen** [comment]
go-fuse has splice support for reading data (ie. shipping data from fuse back to the kernel.) 

I think it has been a mistake to add this, as it complicates the calling conventions. For supporting splice on write, you'd have to add an API that can take either byte[] or a file-descriptor, which is ugly and confusing IMO.

**Comment by codeboytj** [comment]
@hanwen You mean the write_buf api? How to add this in go-fuse? Do we have some example code to do this?

**Comment by codeboytj** [comment]
Thank you. I have improve the performance successfully by reduce syscall count.

**Comment by lmlong** [comment]
go-fuse still not support write_buf/read_buf?
