### ISSUE TITLE
Not working on WSL 2

### ISSUE THREAD

**Issue by buzzy** [hanwen/go-fuse#433]
I tried compiling the examples and they work fine on a Ubuntu 20.04 system.

However, it does not work in a Ubuntu 20.04 running on WSL 2 on Windows. No error when running the example, but the actual mount never happens.

If I kill the process and run it again, I get this error:
```
/usr/bin/fusermount: failed to access mountpoint /home/buzzy/fuse: Permission denied
Mount fail: fusermount exited with code 256
```

So it seems it tried to mount and got stuck. Any ideas?

**Comment by buzzy** [comment]
It was a permissions problem. Worked fine when running as root. Please ignore.

**Comment by annetteshajan** [comment]
Hi @hanwen @buzzy 
What was the issue ? I get a similar error and am unable to solve it.
```
root, err := fs.NewLoopbackRoot(home)
	if err != nil {
		panic(err)
	}

	server, err := fs.Mount(mntDir, root, &fs.Options{
		MountOptions: fuse.MountOptions{Debug: true},
	})
```
I have this setup and I get the same error- unable to access mountpoint and permission denied.

I googled the issue and it said if I uncomment allow-other-users in /etc/fuse.conf it would work, but it still doesnt.

Any help would be appreciated.

**Comment by buzzy** [comment]
> Hi @hanwen @buzzy What was the issue ? I get a similar error and am unable to solve it.
> 
> ```
> root, err := fs.NewLoopbackRoot(home)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	server, err := fs.Mount(mntDir, root, &fs.Options{
> 		MountOptions: fuse.MountOptions{Debug: true},
> 	})
> ```
> 
> I have this setup and I get the same error- unable to access mountpoint and permission denied.
> 
> I googled the issue and it said if I uncomment allow-other-users in /etc/fuse.conf it would work, but it still doesnt.
> 
> Any help would be appreciated.

And you are running it as root?

**Comment by annetteshajan** [comment]
@buzzy What do you mean?
Should I build it and run it as sudo?
I don't think I want to do that as I am also using containers in my application (not for FUSE).
Any other workaround?

**Comment by buzzy** [comment]
> @buzzy What do you mean? Should I build it and run it as sudo? I don't think I want to do that as I am also using containers in my application (not for FUSE). Any other workaround?

How you build it is irrelevant. The user running it needs enough permission.
