### ISSUE TITLE
Callback when inode forgotten?

### ISSUE THREAD

**Issue by andrewchambers** [hanwen/go-fuse#435]
Hi there,

Is there a way to run a callback when an fs inode is forgotten? I am looking for something like the file releaser interface but cannot seem to find anything. Forgive me if I missed anything obvious.

edit: I may be misunderstanding - but if you have a dynamic filesystem, do you need to manually remove/expire inodes yourself if you want to reclaim space? It seems like the old fs interface had an OnForget function, but the new one does not.

**Comment by hanwen** [comment]
the kernel issues forgets automatically, but only does so under memory pressure (or situations like deleting a file), so you can't use it to manage constrained resources. There is also no guarantee that all inodes will be forgotten on unmount. So, I'd try to find another way to do what you want

**Comment by andrewchambers** [comment]
To elaborate, I have a situation where each inode has some state on a remote server that I want to release when the kernel is done with it. I suppose I can also do this via go finalizers, though that will be even less timely.

**Comment by andrewchambers** [comment]
Small note: I did a bit more digging and it seems like the kernel also issues a forget when a dentry is invalidated - which includes after a dentry is checked on expiry, so can happen frequently.

**Comment by andrewchambers** [comment]
I think I will try to do what I want with the raw interface instead.
