### ISSUE TITLE
question: Why is FUSE_UNKNOWN_INO 4 bytes?

### ISSUE THREAD

**Issue by andrewchambers** [hanwen/go-fuse#439]
I noticed it is defined as '0xFFFFFFFF' - but ino and node id are 64bit - is this intentional/historic or for 32 bit platforms? I was slightly confused by this and wondered if someone can enlighten me.

**Comment by hanwen** [comment]
I have no idea. You'd have to ask the folks who maintain the kernel module. Note that linux tries very hard to maintain backward compatibility, so this can't be changed.
