### ISSUE TITLE
Tests in memnode_test.go don't actually use memNode on OS X (!)

### ISSUE THREAD

**Issue by akalin** [hanwen/go-fuse#44]
Repro steps:

1) Put a panic in memNode.Create() (or other callers of newNode() or newFile()).
2) Run go test with -run MemNodeFsWrite

I expect the panic to be hit (as it is in Linux) but it's not. Various other things that I'd expect to be hit are also not hit.

I'm not sure exactly why this happens. My working hypothesis is that OSXFUSE sends does an ACCESS call, which returns a "not implemented" error, and it gets confused by that and doesn't actually do the mount.

Log below:

```
=== RUN TestMemNodeFsWrite
2015/04/23 17:23:34 Dispatch: INIT, NodeId: 0. data: *fuse.InitIn: {7.8 Ra 0x100
00 } 
2015/04/23 17:23:34 Serialize: INIT code: OK value: {7.8 Ra 0x10000  9/12 Wr 0x10000}
2015/04/23 17:23:34 Dispatch: STATFS, NodeId: 1. 
2015/04/23 17:23:34 Serialize: STATFS code: OK value: {blocks (0,0)/0 files 0/0 
bs0 nl0 frs0}
2015/04/23 17:23:34 Dispatch: STATFS, NodeId: 1. 
2015/04/23 17:23:34 Serialize: STATFS code: OK value: {blocks (0,0)/0 files 0/0 
bs0 nl0 frs0}
2015/04/23 17:23:34 Dispatch: STATFS, NodeId: 1. 
2015/04/23 17:23:34 Serialize: STATFS code: OK value: {blocks (0,0)/0 files 0/0
(lots of STATFS calls)
2015/04/23 17:23:34 Dispatch: ACCESS, NodeId: 1. data: {} 
2015/04/23 17:23:34 Serialize: ACCESS code: 78=function not implemented value: 
2015/04/23 17:23:34 Dispatch: GETATTR, NodeId: 1. data:  
2015/04/23 17:23:34 Serialize: GETATTR code: OK value: {A0.100000000 {M040777 SZ
=0 L=0 0:0 0 0:1 A 1429835014.567037062 M 1429835014.567037062 C 1429835014.5670
37062}}
(more STATFS and LOOKUP calls (for "._.")
```

**Comment by hanwen** [comment]
the other possiblity is that StatFS should return more credible values. The loopback tests are run on top of PathFS which stacked on a NodeFS, so it should be possible to make work. You could run the loopback tests (fuse/test) and see what they return .

**Comment by hanwen** [comment]
I think this may just be a race condition: the writes complete on the normal filesystem before the mount point is available.

please reopen if this still happens with current HEAD.
