### ISSUE TITLE
Can reads be async?

### ISSUE THREAD

**Issue by Inrixia** [hanwen/go-fuse#440]
I have a simple fs setup where reads trigger a goroutine that fetches data required for that read. Because I have to wait for the channel to return the data, reads block while fetching and can only run one after the other...

Is there any way where multiple reads can call off goroutines and return their buffers once said routines complete?

Here is a example (not actual code just to showcase what I'm talking about):
```go
var _ = (fs.FileReader)((*FileStreamHandle)(nil))

func (fh *FileStreamHandle) Read(ctx context.Context, dest []byte, off int64) (fuse.ReadResult, syscall.Errno) {
        c := make(chan []byte)
        go getMyData(off, len(dest), c)
	return fuse.ReadResultData(<-c), 0
}
```

I basically want it where if 4 read requests are sent `getMyData` is run 4 times in parallel with all the data being returned rather than one after the other.

**Comment by hanwen** [comment]
I recommend using some sort of cache. On the first read, the cached file contents are populated, subsequent reads would use the cache.

**Comment by Inrixia** [comment]
A cache does nothing if its not populated, adding a cache is extremely easy and in my actual code I already does so.

Even with a cache a program reading a file will result in many small requests for data not one large one meaning that blocking on each read is extremely bad performance wise. This can be alleviated by fetching ahead but that also adds latency to existing small reads.

Using a cache is not a good answer to this issue @hanwen and I wouldn't consider this resolved

**Comment by rfjakob** [comment]
> I basically want it where if 4 read requests are sent getMyData is run 4
times in parallel with all the data being returned rather than one after
the other.

Is this not already the case? Why wouldn't the reads run in parallel?

**Comment by Inrixia** [comment]
I'm looking at this from the perspective of there should be some way to have other read requests trigger goroutines while prior goroutines are being run/channels being waited on.

Though I'm coming from the javascript land of promises and afik golang blocks the main thread when waiting for data from a channel. With this in mind I'm not sure if it's even possible to achieve what I'm wanting... Ideally if reads where async while one was waiting on a goroutine to give some data others could be executed...

Thoughts?

**Comment by rfjakob** [comment]
Hi, in go-fuse,

> Each filesystem operation executes in a separate goroutine.
> https://github.com/hanwen/go-fuse/blob/master/fuse/server.go#L407

In other words: blocking in one `Read()` will not block other requests.

**Comment by Inrixia** [comment]
If that's true then why do no other read requests execute while I have a goroutine running in one. After one unblocked others which say have cached data will all finish very quickly one after the other until uncached data is hit.

I can grab an actual snippet of my code. Perhaps there is some behaviors causing goroutines to block that I'm not aware of

**Comment by rfjakob** [comment]
I suggest to enable Debug to see exactly what's happening like here:

https://github.com/hanwen/go-fuse/blob/master/example/loopback/main.go#L98

But my guess is that the user does not submit more reads until they get the results. You can try to increase [MaxReadAhead](https://pkg.go.dev/github.com/hanwen/go-fuse/v2@v2.1.1-0.20220822120740-58a7e145ff0d/fuse#MountOptions)

**Comment by Inrixia** [comment]
All this time I have been assuming that reads were coming in hatched but it may be that the application reading files is actually waiting for each chunk to return.

I'll see if I can test reading multiple chunks at once to validate this, if that is the case then problem solved.

Thanks again for the help, will update with results once I test

**Comment by hanwen** [comment]
in the code snippet you post

```
        go getMyData(off, len(dest), c)
	return fuse.ReadResultData(<-c), 0
```

you immediately consume the result of the goroutine (`<-c`), so there is no async stuff going.

the kernel can issue 4 (or more) parallel read requests, but it is common for the reads to be sequential, especially if the caller is reading the file sequentially. You can check what it does using strace.

**Comment by Inrixia** [comment]
Yes your are correct if the reads are sequential, if they aren't then 4 goroutines should execute in parallel which is what I wanted to know in this issue.

Once I test
