### ISSUE TITLE
flock support

### ISSUE THREAD

**Issue by andrewchambers** [hanwen/go-fuse#441]
The raw filesystem supports posix lock callbacks (lockf) but not bsd lock (flock) callbacks.

**Comment by hanwen** [comment]
why opcodes does this correspond to?

**Comment by andrewchambers** [comment]
Can look - here is the corresponding libfuse entry: https://github.com/libfuse/libfuse/blob/b1290d4c091a5c590e61a6195e625eab33300673/include/fuse_lowlevel.h#L1138

**Comment by andrewchambers** [comment]
Ah it might be done via a flag in the existing lock structure: https://github.com/torvalds/linux/blob/master/fs/fuse/file.c#L2584 - I can investigate how to use them via the existing interface.

**Comment by andrewchambers** [comment]
I see its controlled via flags in the existing ops.
