### ISSUE TITLE
POSIX ACL

### ISSUE THREAD

**Issue by TanCharles** [hanwen/go-fuse#446]
Hello, I have a question about ACL. I used the command setfacl to save it into xattr, but I couldn't get it from getfacl. 
What should I do

**Comment by TanCharles** [comment]
I find the answer . setting opt.IgnoreSecurityLabels = false

**Comment by mxq-151** [comment]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/12026157/212844672-89a60df1-a117-4665-a755-8a92183a3dbd.png">

i have been change the setting to false:opt.IgnoreSecurityLabels but get error as above,can you give some help

**Comment by hanwen** [comment]
use the Debug functionality to see what call generates ENOTSUPP. I expect you have to implement Setxattr.

**Comment by hanwen** [comment]
I guess you didn't implement the method correctly. See https://github.com/hanwen/go-fuse/blob/615a0a7e1178bdca80868b4f2386a7f762f41e02/fs/loopback_linux.go#L18
for an example.  You can check if you did it correctly by doing a type check, see https://github.com/hanwen/go-fuse/blob/615a0a7e1178bdca80868b4f2386a7f762f41e02/fs/loopback.go#L75 for an example.

**Comment by mxq-151** [comment]
> I guess you didn't implement the method correctly. See
> 
> https://github.com/hanwen/go-fuse/blob/615a0a7e1178bdca80868b4f2386a7f762f41e02/fs/loopback_linux.go#L18
> 
> 
> for an example. You can check if you did it correctly by doing a type check, see
> https://github.com/hanwen/go-fuse/blob/615a0a7e1178bdca80868b4f2386a7f762f41e02/fs/loopback.go#L75
> 
> for an example.

found the answer by make opt.IgnoreSecurityLabels = false
