### ISSUE TITLE
Export unmount function

### ISSUE THREAD

**Issue by Arsen6331** [hanwen/go-fuse#455]
The `fuse` package has an unexported function called `unmount`, which would be useful for cleaning up mounts in the event of an ungraceful program exit where `Server.Unmount()` could not be called. Would it be possible to rename the `unmount` function to `Unmount` to make it accessible?

Here's the function I'm talking about:

- Linux: https://github.com/hanwen/go-fuse/blob/144cb541affb5b007eefe3821261ad6fe728336e/fuse/mount_linux.go#L175
- Darwin: https://github.com/hanwen/go-fuse/blob/144cb541affb5b007eefe3821261ad6fe728336e/fuse/mount_darwin.go#L89

**Comment by hanwen** [comment]
I've looked into this for a bit, but it's a bit messy because of the handling MountOptions.DirecMount[String] option (I think that should not be part of a public function.)

The unmount function just calls `fusermount -u $DIR`. You could make your own function that does that.
