### ISSUE TITLE
Unexpected zero-read with specified inos

### ISSUE THREAD

**Issue by bitonic** [hanwen/go-fuse#462]
I encountered what I believe to be unexpected behavior. Consider the following server which just contains file `test` with contents `"0000000000\n"`, with fixed ino 42:

```go
package main

import (
	"context"
	"flag"
	"log"
	"sync"
	"syscall"
	"time"

	"github.com/hanwen/go-fuse/v2/fs"
	"github.com/hanwen/go-fuse/v2/fuse"
)

const fileName = "test"
const fileBody = "0000000000\n"

type node struct {
	fs.Inode
	root bool
	mu   sync.Mutex
}

func (n *node) Lookup(ctx context.Context, name string, out *fuse.EntryOut) (*fs.Inode, syscall.Errno) {
	if n.root && name == fileName {
		return n.NewInode(ctx, &node{root: false}, fs.StableAttr{Ino: 42, Mode: syscall.S_IFREG}), 0
	}
	return nil, syscall.ENOENT
}

func (n *node) Getattr(ctx context.Context, f fs.FileHandle, out *fuse.AttrOut) syscall.Errno {
	if n.root {
		out.Mode = 0755
		return 0
	} else {
		out.Mode = 0644
		out.Size = uint64(len(fileBody))
		return 0
	}
}

func (n *node) Open(ctx context.Context, flags uint32) (fh fs.FileHandle, fuseFlags uint32, errno syscall.Errno) {
	if n.root {
		return nil, 0, syscall.EISDIR
	} else {
		return nil, 0, 0
	}
}

func (n *node) Read(ctx context.Context, fh fs.FileHandle, dest []byte, off int64) (fuse.ReadResult, syscall.Errno) {
	n.mu.Lock()
	defer n.mu.Unlock()

	select {
	case <-ctx.Done():
		return nil, syscall.EINTR
	case <-time.After(100 * time.Microsecond):
	}

	if off < int64(len(fileBody)) {
		l := copy(dest, fileBody[off:])
		return fuse.ReadResultData(dest[:l]), 0
	} else {
		return fuse.ReadResultData([]byte{}), 0
	}
}

var _ = (fs.InodeEmbedder)((*node)(nil))
var _ = (fs.NodeLookuper)((*node)(nil))
var _ = (fs.NodeGetattrer)((*node)(nil))
var _ = (fs.NodeReader)((*node)(nil))

func main() {
	debug := flag.Bool("debug", false, "print debug data")
	flag.Parse()
	if len(flag.Args()) < 1 {
		log.Fatal("mountpoint missing")
	}
	opts := &fs.Options{}
	opts.Debug = *debug
	server, err := fs.Mount(flag.Arg(0), &node{root: true}, opts)
	if err != nil {
		log.Fatalf("Mount fail: %v\n", err)
	}
	server.Wait()
}
```

I run the above with `go run . -debug <mountpoint>`. Note how `Read` is delayed by 100us.

With this server I unexpectedly occasionally get zero reads when reading concurrently, for example using this test C program:

```c
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>

#define NUM_THREADS 2

#define FILE_LEN 11
static const char* expected_data = "0000000000\n";
static const char* filename = NULL;

void* f(void* arg) {
    int tid = *(int*)arg;
    size_t iterations = 0;
    for (;;) {
        const char* buf[FILE_LEN];

        int fd = open(filename, O_RDONLY);
        if (fd < 0) {
            printf("%d, %lu: could not open %s: %d\n", tid, iterations, filename, errno);
            exit(1);
        }

        int read_so_far = 0;
        while (read_so_far < FILE_LEN) {
            ssize_t r = read(fd, buf+read_so_far, FILE_LEN-read_so_far);
            printf("%d: read at off=%d, r=%ld\n", tid, read_so_far, r);
            if (r < 0) {
                printf("%d, %lu: could not read: %d\n", tid, iterations, errno);
                exit(1);
            }
            if (r == 0) {
                printf("%d, %lu: EOF\n", tid, iterations);
                exit(1);
            }
            read_so_far += r;
        }

        if (strncmp((char*)buf, expected_data, FILE_LEN) != 0) {
            printf("%d, %lu: bad file contents\n", tid, iterations);
            exit(1);
        }

        if (close(fd) < 0) {
            printf("%d, %lu: couldn't close: %d\n", tid, iterations, errno);
            exit(1);
        }

        iterations++;
    }

    return NULL;
}

int main(int argc, const char** argv) {
    if (argc != 2) {
        printf("usage: %s <file>", argv[0]);
        exit(2);
    }

    filename = argv[1];

    pthread_t threads[NUM_THREADS];
    int thread_ids[NUM_THREADS];

    for (int i = 0; i < NUM_THREADS; i++) {
        thread_ids[i] = i;
        int rc = pthread_create(&threads[i], NULL, f, (void*)&thread_ids[i]);
        if (rc) {
            printf("%d: failed to create thread: %d\n", i, rc);
            exit(1);
        }
    }

    int rc = pthread_join(threads[0], NULL);
    if (rc) {
        printf("failed to join: %d\n", rc);
        exit(1);
    }
    printf("unexpected termination\n");

    return 0;
}
```

I compile it with `gcc -Wall -O2 -o test test.c -lpthread`, and run it with `./test <mountpoint>/test`:

```
% ./test go/mnt/test
0: read at off=0, r=11
1: read at off=0, r=11
0: read at off=0, r=11
1: read at off=0, r=11
1: read at off=0, r=11
0: read at off=0, r=11
0: read at off=0, r=11
1: read at off=0, r=11
1: read at off=0, r=11
0: read at off=0, r=0
0, 4: EOF
```

I reliably get a spurious zero-sized read at some point. On my laptop 2 threads are enough, on different machines I need more to get a failure quickly.

The problem does _not_ manifest itself if I don't manually assign the inode. `strace` confirms that I get zero-sized `reads`s, although I can't match it with anything in go-fuse itself, so I suspect it's some interaction between the VFS layer and go-fuse short-circuiting a read to be empty. I'll probably dig a bit more into this myself, but I wanted to put it out there in the meantime (also to confirm that I'm not using the API wrong). The problem does _not_ manifest itself if I let go-fuse assign the ino.

* go 1.19.8
* go-fuse 2.2.0
* linux 5.15

**Comment by hanwen** [comment]
Curious. Does the go-fuse debug trace reveal anything interesting?

**Comment by rfjakob** [comment]
I wonder if the offset inside the file gets messed up, and the `read` actually reads from offset 11.

Can you repro this with `pread` instead of `read` (i.e. tracking the file offset manually instead of letting the kernel do it).

**Comment by rfjakob** [comment]
No, it's simpler. You forgot to set the file size in Lookup. This fixes the problem in my testing:

```
func (n *node) Lookup(ctx context.Context, name string, out *fuse.EntryOut) (*fs.Inode, syscall.Errno) {
	if n.root && name == fileName {
		out.Size = 11
		return n.NewInode(ctx, &node{root: false}, fs.StableAttr{Ino: 42, Mode: syscall.S_IFREG}), 0
	}
	return nil, syscall.ENOENT
}
```

**Comment by hanwen** [comment]
thanks Jakob for looking into this.

**Comment by bitonic** [comment]
Thanks, that makes sense. I think it would be helpful to note that `Lookup` essentially needs to do what `Getattr` does in this part of the docs: https://pkg.go.dev/github.com/hanwen/go-fuse/v2/fs#hdr-Structure_of_a_file_system_implementation .

**Comment by bitonic** [comment]
> Curious. Does the go-fuse debug trace reveal anything interesting?

BTW, what made this super annoying to debug is that this was happening inside the VFS as I suspected (the zero-sized size from the lookup was sometimes short-circuiting the `read` call to an EOF). So the debug output showed no such zero-read. I haven't tracked down exactly why this only happened with concurrent executions, but probably due to the syscalls getting interrupted because of context switches.

**Comment by hanwen** [comment]
> So the debug output showed no such zero-read

Forgetting to set Size leading to short reads is a classical mistake, which would stand out in the debug output, as it would say `sz 0` in the lookup result.

I should probably add a note to the bug template to add debug output if at all possible.

**Comment by hanwen** [comment]
for the doc, fixed in https://github.com/hanwen/go-fuse/commit/f32523e1f1de5339676645d6c2c6c0bf2125e40e
