### ISSUE TITLE
user process can't access filesystem when not in primary group 

### ISSUE THREAD

**Issue by jonleivent** [hanwen/go-fuse#465]
I asked this in the gocryptfs discussions page, and it was suggested that I ask it here:

I have a mounted fuse (gocryptfs) filesystem that a user owns and can access.  However,a process with that user's UID but not the user's primary group GID cannot access the filesystem.  The filesystem is not mounted with the allow_others option, and I would rather not have to resort to using allow_others.  I haven't tried allow_others to see if it changes this behavior, because of the security implications.

Is this expected behavior?  Is there an alternative way around it besides using the allow_others mount option?

**Comment by hanwen** [comment]
It sounds like something outside of go-fuse control. Does a debug log show that it's trying to check for access? (ACCESS opcode)? Let me check over here.

**Comment by rfjakob** [comment]
No, gocryptfs leaves the permission checking to the kernel.

I linked to the kernel check in the cross-post:

https://github.com/rfjakob/gocryptfs/discussions/740#discussioncomment-5898883

**Comment by hanwen** [comment]
https://github.com/hanwen/go-fuse/issues/466 for the loopback problem.
