### ISSUE TITLE
monitor file operations without entering the mount point

### ISSUE THREAD

**Issue by xnray** [hanwen/go-fuse#483]
I want to monitor file operations in the /home/kong/k directory without affecting the user's experience and without entering the mount point. I want to use the go-fuse v2 version to achieve this,what should I do,Who can show me how to do that, thank you！

**Comment by hanwen** [comment]
if /home/kong/k is a FUSE mount, there is no way to do it. If it is not a FUSE mount, FUSE is not a solution, and you should look into inotify instead.
