### ISSUE TITLE
first level gocryptfs.diriv file always same when init in reverse mode

### ISSUE THREAD

**Issue by F-Hauri** [hanwen/go-fuse#486]
Let's see:

$ gocryptfs -q -init -reverse test1 <<<'what a fucking strong pass phrase'
$ gocryptfs -q -init -reverse test2 <<<"another long'n strong pass phrase"
$ gocryptfs -q -init -reverse test3 <<<"shortPassword"
$ gocryptfs -q -reverse test1 <<<'what a fucking strong pass phrase' crypt1
$ gocryptfs -q -reverse test2 <<<"another long'n strong pass phrase" crypt2
$ gocryptfs -q -reverse test3 <<<"shortPassword" crypt3
$ sha1sum crypt?/gocryptfs.diriv
2c9b6702d05d2de71816666387f6d4ea3c28c9cd  crypt1/gocryptfs.diriv
2c9b6702d05d2de71816666387f6d4ea3c28c9cd  crypt2/gocryptfs.diriv
2c9b6702d05d2de71816666387f6d4ea3c28c9cd  crypt3/gocryptfs.diriv

But

$ mkdir test{4,5,6}
$ gocryptfs -q -init  test4 <<<'what a fucking strong pass phrase'
$ gocryptfs -q -init  test5 <<<'what a fucking strong pass phrase'
$ gocryptfs -q -init  test6 <<<'what a fucking strong pass phrase'
$ sha1sum test?/gocryptfs.diriv
f38755738a0be70b6b103f6fdbdb05aaebb3ffe5  test4/gocryptfs.diriv
e2e64788a6e2f0a4554bc56d9b17e55471766398  test5/gocryptfs.diriv
206d278a405d3f826da842abdcdd37e475f9e02e  test6/gocryptfs.diriv

**Comment by hanwen** [comment]
I believe you want to report this here: https://github.com/rfjakob/gocryptfs
