### ISSUE TITLE
`Lseek` does not handle `ENXIO`

### ISSUE THREAD

**Issue by turan18** [hanwen/go-fuse#487]
The current implementation of `Lseek` with whence `SEEK_DATA` set always returns the current offset of the file: https://github.com/hanwen/go-fuse/blob/0b3e1fde6eb5eeb1600388535913ee66f23bdc5b/fs/bridge.go#L1176

`SEEK_HOLE` always returns the end of the file:

https://github.com/hanwen/go-fuse/blob/0b3e1fde6eb5eeb1600388535913ee66f23bdc5b/fs/bridge.go#L1186

According to https://man7.org/linux/man-pages/man2/lseek.2.html the filesystem should return an `ENXIO` when the offset is greater than the file size on either  `SEEK_DATA` or `SEEK_HOLE` **or**  if the offset is set to the end of the file with `SEEK_DATA` (where there is a hole). 

Re man page:
```
ENXIO   whence is SEEK_DATA or SEEK_HOLE, and offset is beyond the
        end of the file, or whence is SEEK_DATA and offset is
        within a hole at the end of the file.
```

For some context, we had an OracleLinux container running with `soci-snapshotter`, a lazy loading containerd snapshotter, that creates FUSE filesystems for layers in an image. We had issue where a call to `cp` on a sparse file would hang indefinitely. With some digging we found that the command  was making calls to `Lseek` in an infinite loop after the contents of the file were read and the offset was set to the end of the file. We found that this was because `Lseek(fd, EOF_OFFSET, SEEK_DATA)` would keep returning the offset at the end of the file instead of throwing an `ENXIO`.

I have a working implementation and would be happy to contribute upstream if that's fine.

**Comment by hanwen** [comment]
> I have a working implementation and would be happy to contribute upstream if that's fine.

SGTM. Please see CONTRIBUTING for instructions.

**Comment by turan18** [comment]
Hey, the PR is up: https://github.com/hanwen/go-fuse/pull/488
