### ISSUE TITLE
Is Event Driven Flow Supported

### ISSUE THREAD

**Issue by gstraiht** [hanwen/go-fuse#491]
Hi
Please do I see it right from examples that library provides more like state driven interface. So that from the API level it is to define the state of FS in advance and  next on a FUSE level fs consumer communicates to that "deployed" state

Yet is it possible to configure the behavior of a FS from the event driven perspective so that we don't provide any state but to provide  response to a customer on the fly.  E.g. user tries to read `/som/path/to/file` so we receive an event and make decision in place do we have any info/content on that specific `/som/path/to/file` item?

**Comment by hanwen** [comment]
Most examples use predefined trees, but you can dynamically discover trees as well, see [here](https://pkg.go.dev/github.com/hanwen/go-fuse/v2/fs#hdr-Dynamically_discovered_file_systems) .

**Comment by gstraiht** [comment]
Great thanks
