### ISSUE TITLE
Operation to Set ACL not supported ?

### ISSUE THREAD

**Issue by imnaveed** [hanwen/go-fuse#50]
Hi,

1) I've mounted NFS Share directly at ('/mnt/servers/1' without fuse layer) and did some tests using 'nfs4_setfacl'; they does replicate ACLs to backend NFS Shares. see attached test_result.png for details:
![test_result](https://cloud.githubusercontent.com/assets/10295079/8105503/250cc53c-1053-11e5-872e-551826ba8635.png)

2) But when mounted NFS Share through a (golang fuse layer project) at '/mnt/storage/1' and then tried some tests using 'nfs4_setfacl'; I get error like: "Operation to set ACL not supported."

Note: My golang project mounts NFS directly using system 'mount' command and then runs 'go-fuse/NewLoopbackFileSystem' on it and passes through to back-end NFS servers. All works well except I can't run 'nfs4_setfacl' command on NFS Share mounted using 'Loopback file system'.

So my question is; is this allowed to set ACL to remote NFS Shares or I've to explicitly execute such commands directly on NFS Share mounted in a normal way; like I did manually in step 1. 

Or I mean; I've to automate step 1 from within fuse project when I get ACL change request?

Many thanks for your help!

**Comment by hanwen** [comment]
Try running your FS with debug enabled, and see if setACL generates any FUSE calls.

**Comment by imnaveed** [comment]
I did enabled debug and got the output; please see the snapshot below:
![snapshot](https://cloud.githubusercontent.com/assets/10295079/8117451/989075d2-10a1-11e5-9aa2-826c6cd19ec3.png)

**Comment by imnaveed** [comment]
Hi,

Did you managed to identify what's the solution to the problem I'm having? Looking forward to your reponse...

Thanks

**Comment by rfjakob** [comment]
Maybe related to https://github.com/hanwen/go-fuse/issues/56

**Comment by hanwen** [comment]
there are more debug options. I need to see the lowlevel one. Also, please paste as text rather than image.

**Comment by hanwen** [comment]
please reopen if you have more data.
