### ISSUE TITLE
Error message when using `DirectMount: true`: writer: Write/Writev failed, err: 2=no such file or directory. opcode: RELEASE

### ISSUE THREAD

**Issue by bduffany** [hanwen/go-fuse#505]
When using `DirectMount: true`, the following error message occasionally gets logged:

```
writer: Write/Writev failed, err: 2=no such file or directory. opcode: RELEASE
```

It can be reproduced reliably with the following code, adapted from the `hello` example (set `DirectMount: false` and the error message goes away).

(go-fuse version 2.5.0, Linux kernel version 6.5.0)

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/hanwen/go-fuse/v2/fs"
	"github.com/hanwen/go-fuse/v2/fuse"
)

type HelloRoot struct{ fs.Inode }

func (r *HelloRoot) OnAdd(ctx context.Context) {
	ch := r.NewPersistentInode(
		ctx, &fs.MemRegularFile{
			Data: []byte("file.txt"),
			Attr: fuse.Attr{Mode: 0644},
		}, fs.StableAttr{Ino: 2})
	r.AddChild("file.txt", ch, false)
}

func main() {
	if err := os.MkdirAll("./hello", 0755); err != nil {
		log.Fatalf("Create root dir: %s", err)
	}

	for i := 0; i < 10_000; i++ {
		opts := &fs.Options{
			MountOptions: fuse.MountOptions{DirectMount: true},
		}

		server, err := fs.Mount("./hello", &HelloRoot{}, opts)
		if err != nil {
			log.Fatalf("Mount fail: %v\n", err)
		}
		server.Unmount()
		server.Wait()
	}
}
```

**Comment by hanwen** [comment]
I've seen this happen in the tests as well, and never looked deeply into it. RELEASE means that something opened a file in the mount. This can either be the POLL hack, or your operating system (eg. desktop search indexing the mount). Does it go away if you add `WaitMount()` ?

**Comment by bduffany** [comment]
`fs.Mount()` internally calls `WaitMount()` if that's what you mean?

I don't think it's an external process such as an indexer, since this message is also logged when running inside of a microVM (in our VMs we only run a bare-bones init process and don't have any file watchers etc.)

**Comment by hanwen** [comment]
here is an example of what is going on: n18446744073709551615 is the poll hack inode.

```
14:30:27.976833 rx 14: FLUSH n18446744073709551615 {Fh 18446744073709551615} 
14:30:27.976839 tx 14:     OK
14:30:27.977006 unmount: executing ["/usr/bin/fusermount3" "-u" "/tmp/TestParallelMount595956975/001"]
14:30:27.980986 rx 8: LOOKUP n1 [".Trash"] 7b
14:30:27.981216 tx 8:     2=no such file or directory, {n0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
14:30:27.981532 rx 18: LOOKUP n1 [".Trash-1000"] 12b
14:30:27.981680 tx 18:     2=no such file or directory, {n0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
14:30:27.984163 rx 16: RELEASE n18446744073709551615 {Fh 18446744073709551615 LARGEFILE  L0} 
14:30:27.984292 tx 16:     OK
14:30:27.984460 writer: Write/Writev failed, err: 2=no such file or directory. opcode: RELEASE
14:30:27.984561 received ENODEV (unmount request), thread exiting
```

`syscall.Close(pollFD)` closes out the poll hack file descriptor, but the close is only synchronized with the FLUSH opcode. Once the FLUSH is finished, the file system is unmounted. While the unmount is being processed, the file close also generates a RELEASE opcode. For reasons unknown (probably an error in the protocol design), this opcode expects a reply, but by the time we write the reply, the unmount is finished, and the FUSE device has gone away.

We probably have to write a reply at all for RELEASE (or we´d leak kernel memory)

Maybe I can just suppress the message incase of ENOENT for a RELEASE opcode.

**Comment by hanwen** [comment]
i've tagged v2.5.1 for this.
