### ISSUE TITLE
Concurrent mount/unmount results in hanging

### ISSUE THREAD

**Issue by bduffany** [hanwen/go-fuse#506]
The following code snippet runs a simplified version of the `hello` example, mounting then immediately unmounting the hello FS 100K times, to distinct directories each time.

When setting the concurrency limit of the errgroup to anything greater than 1, the code consistently hangs. It doesn't seem to matter whether we use `DirectMount` or not, unlike in #505.

(go-fuse version 2.5.0, Linux kernel version 6.5.0)

```
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/hanwen/go-fuse/v2/fs"
	"github.com/hanwen/go-fuse/v2/fuse"
	"golang.org/x/sync/errgroup"
)

type HelloRoot struct{ fs.Inode }

func (r *HelloRoot) OnAdd(ctx context.Context) {
	ch := r.NewPersistentInode(
		ctx, &fs.MemRegularFile{
			Data: []byte("file.txt"),
			Attr: fuse.Attr{Mode: 0644},
		}, fs.StableAttr{Ino: 2})
	r.AddChild("file.txt", ch, false)
}

func main() {
	_ = os.RemoveAll("./hello")
	if err := os.MkdirAll("./hello", 0755); err != nil {
		log.Fatalf("Create root dir: %s", err)
	}

	var eg errgroup.Group
	eg.SetLimit(8)
	const n = 100_000
	for i := 1; i <= n; i++ {
		i := i
		if i%100 == 0 {
			log.Printf("Mounting %d of %d", i, n)
		}
		eg.Go(func() error {
			dir := fmt.Sprintf("./hello/%d", i)
			defer os.RemoveAll(dir)

			if err := os.Mkdir(dir, 0755); err != nil {
				return err
			}
			opts := &fs.Options{
				MountOptions: fuse.MountOptions{DirectMount: true},
			}
			server, err := fs.Mount(dir, &HelloRoot{}, opts)
			if err != nil {
				return err
			}

			server.Unmount()
			server.Wait()
			return nil
		})
	}
	if err := eg.Wait(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by hanwen** [comment]
thanks for your report. This is an interesting trace. It shows that it's calling `fusermount` despite specifying `DirectMount`. This is because there is a fallback; did you try using StrictDirectMount ?

Subprocessing with FUSE is a known source of deadlocks, see https://pkg.go.dev/github.com/hanwen/go-fuse/v2/fs#hdr-Deadlocks.  Obviously, the `umount` operation should work, but if you force direct mounting, I think the problem will go away.

I'll try to have a detailed look later this week.

**Comment by bduffany** [comment]
Switching to `DirectMountStrict: true` indeed fixes things. Thanks!

**Comment by hanwen** [comment]
Some debugging:

* problem is related to the subprocess for the mount; the unmount seems OK
* problem goes away if we disable the poll hack

**Comment by hanwen** [comment]
found a trace here:

```
syscall.Syscall6(0x100c000143818?, 0x7f7bbc608718?, 0xc0000cc4e0?, 0xc000034000?, 0x47e970?, 0xc0000b5bb0?, 0xc0000b5c28?)
	/usr/lib/golang/src/syscall/syscall_linux.go:91 +0x30 fp=0xc0000b5b70 sp=0xc0000b5ae8 pc=0x47e970
syscall.Syscall6(0x10f, 0xc0000b5ce0, 0x1, 0xc0000b5c90, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0x3d fp=0xc0000b5bb8 sp=0xc0000b5b70 pc=0x47eefd
golang.org/x/sys/unix.ppoll(0xc0000225c0?, 0x38?, 0x38?, 0xc0000225c0?)
	/home/hanwen/go/pkg/mod/golang.org/x/sys@v0.0.0-20220520151302-bc2c85ada10a/unix/zsyscall_linux.go:124 +0x57 fp=0xc0000b5c38 sp=0xc0000b5bb8 pc=0x5391f7
golang.org/x/sys/unix.Ppoll({0xc0000b5ce0?, 0x0?, 0xc0000225c0?}, 0x0?, 0xffffffffffffff9c?)
	/home/hanwen/go/pkg/mod/golang.org/x/sys@v0.0.0-20220520151302-bc2c85ada10a/unix/syscall_linux.go:148 +0x38 fp=0xc0000b5c68 sp=0xc0000b5c38 pc=0x539078
golang.org/x/sys/unix.Poll({0xc0000b5ce0?, 0xc0000225c0?, 0xc000067438?}, 0x10?)
	/home/hanwen/go/pkg/mod/golang.org/x/sys@v0.0.0-20220520151302-bc2c85ada10a/unix/syscall_linux.go:157 +0x8d fp=0xc0000b5cb0 sp=0xc0000b5c68 pc=0x53914d
github.com/hanwen/go-fuse/v2/fuse.pollHack({0xc0000203c0?, 0xc00012aac0?})
	/home/hanwen/vc/go-fuse/fuse/poll_linux.go:22 +0xaf fp=0xc0000b5d18 sp=0xc0000b5cb0 pc=0x543ecf
github.com/hanwen/go-fuse/v2/fuse.(*Server).WaitMount(0xc000161ba0)
```

```
//sys   ppoll(fds *PollFd, nfds int, timeout *Timespec, sigmask *Sigset_t) (n int, err error)

func Ppoll(fds []PollFd, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {
        if len(fds) == 0 {
                return ppoll(nil, 0, timeout, sigmask)
        }
        return ppoll(&fds[0], len(fds), timeout, sigmask)
}
```

if ppoll has special support for nonblocking i/o again, we are hosed again.

**Comment by hanwen** [comment]
This is  probably the scenario that involves dup3 documented at https://pkg.go.dev/github.com/hanwen/go-fuse/v2/fs#hdr-Deadlocks

When writing that section, I didn´t realize that fusermount itself uses inherited file descriptors.

**Comment by hanwen** [comment]
further detail of why the pollhack is involved: consider 2 threads (t1, t2). If t1 initiates the pollhack, it might get fd 3 for the poll hack. Then, if t2 calls fusermount, the mechanism above causes a FLUSH on the pollhack fd.

**Comment by hanwen** [comment]
see https://review.gerrithub.io/c/hanwen/go-fuse/+/1186976

**Comment by rfjakob** [comment]
Posting on Gerrithub failed for some obscure reason [1] so posting here:

I tested https://review.gerrithub.io/c/hanwen/go-fuse/+/1186976 . TestParallelMount passes with the init() change and hangs without it. LGTM.


[1]:
> An error occurred
> Error submitting review Error: selector 'gr-label-scores' did not match anything'

**Comment by rfjakob** [comment]
PS: gocryptfs already has [something similar](https://github.com/rfjakob/gocryptfs/blob/master/internal/ensurefds012/ensurefds012.go) for different reasons. It's so things don't completely explode when fds 0,1,2 are not open.

**Comment by hanwen** [comment]
thanks, I wonder what is up with gerrithub. I couldnt add you to the review yesterday.

the "collapse" button on the reply dialog is also broken. 
![review gerrithub io_c_hanwen_go-fuse_+_1186976](https://github.com/hanwen/go-fuse/assets/31547/85bae0ba-4a0d-4e91-a3d8-3c54399d6a60)

@lucamilanesio

**Comment by hanwen** [comment]
fixed in https://github.com/hanwen/go-fuse/commit/36b359112698c1ccc5d5139693b92f62eb02477c

**Comment by hanwen** [comment]
i've tagged v2.5.1 for this.

**Comment by rfjakob** [comment]
The open question is: why doesn't DirectMount work? I looked at the code and I don't see how this can do the wrong thing.

**Comment by hanwen** [comment]
not an open question. I think the tests were run as a normal user, so DirectMount fails with permission error. Then we fallback to fusermount.

**Comment by rfjakob** [comment]
Ack
