### ISSUE TITLE
Implementing Loopback FS - memory access error in path() function

### ISSUE THREAD

**Issue by annetteshajan** [hanwen/go-fuse#511]
I'm writing a simple filesystem which can implement some functions of the loopback filesystem. 

```
type SimpleNode struct {
	fs.Inode
	loopFS *fs.LoopbackNode
	name string 
}
```

I want to call the loopback GetAttr function as such:
```
func (s *SimpleNode) Getattr(ctx context.Context, f fs.FileHandle, out *fuse.AttrOut) syscall.Errno {
	return s.loopFS.Getattr(ctx, f, out)
}
```

However this does not work and it raises a pointer error
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x786821]

goroutine 64 [running]:
github.com/hanwen/go-fuse/v2/fs.(*Inode).Root(...)
        /home/ashajan/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fs/inode.go:148
github.com/hanwen/go-fuse/v2/fs.(*LoopbackNode).Getattr(0xc0001ca5a0, {0x8fdcd0?, 0xc0001440f0?}, {0x0?, 0x0?}, 0xc000150000)
        /home/ashajan/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.5.1/fs/loopback.go:355 +0xc1
main.(*SimpleNode).Getattr(0xc0000dc580, {0x8fdcd0, 0xc0001440f0}, {0x0, 0x0}, 0xc000150000)
```

Can you help me in where  I am going wrong?
Thanks

**Comment by hanwen** [comment]
```
	fs.Inode
	loopFS *fs.LoopbackNode
	name string 
}
```

assuming this is a node definition, this is wrong: the LoopbackNode already is an InodeEmbedder, so you'd do something like

```
type BlaNode struct {
  *fs.LoopbackNode
}
```

so `BlaNode` inherits the functionality of LoopbackNode.

**Comment by annetteshajan** [comment]
I want to just selectively use Loopback functionalities and not inherit all the functionalities.
Is that possible with go-fuse?

**Comment by hanwen** [comment]
> I want to just selectively use Loopback functionalities 

No. But the LoopbackNode doesn't use any internal functionality. So you can reimplement (eg copy&paste) the parts you need.
