### ISSUE TITLE
Changing filesize in Getattr Loopback

### ISSUE THREAD

**Issue by annetteshajan** [hanwen/go-fuse#513]
In my custom filesystem which extends the loopback filesystem - I want to change the file size in Getattr.
But it seems that the Getattr is only being called on the root level according to the debug.
And it is not being reflected in each of the files.
```
func (s *SimpleNode) Getattr(ctx context.Context, f fs.FileHandle, out *fuse.AttrOut) syscall.Errno { 
out.Size = 100
	return s.LoopbackNode.Getattr(ctx, f, out)
}
```

Can somebody tell me where I am going wrong?

**Comment by rfjakob** [comment]
You also have to change `Lookup()`!
