### ISSUE TITLE
How to exit go-fuse process gracefully?

### ISSUE THREAD

**Issue by yangyun50** [hanwen/go-fuse#524]
I use the hello example and mount it to the /mnt dir. And then I user ctrl+c to exit the hello example. However, after this the mountpoint /mnt is still mounted and it is a abandoned mountpoint, which I need to umount manually after the ctrl+c.

So I want to know  how to exit go-fuse process gracefully?

**Comment by hanwen** [comment]
`fusermount -u $mountpoint`

or catch the ^C and call `server.Unmount()`
