### ISSUE TITLE
How to mount a LoopBackRoot into an in-memory tree

### ISSUE THREAD

**Issue by nuwang** [hanwen/go-fuse#526]
I've been experimenting with the library and I'm trying to find the simplest method to mount a loopback root into an in-memory tree. I've tried to combine the examples in hello.go and loopback.go and haven't had much luck. I tried to create a minimal example of this below. Is there something I'm missing?

```
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"syscall"

	"github.com/hanwen/go-fuse/v2/fs"
	"github.com/hanwen/go-fuse/v2/fuse"
)

// inMemoryFS is the root of the tree
type inMemoryFS struct {
	fs.Inode
}

// Ensure that we implement NodeOnAdder
var _ = (fs.NodeOnAdder)((*inMemoryFS)(nil))

// OnAdd is called on mounting the file system. Use it to populate
// the file system tree.
func (root *inMemoryFS) OnAdd(ctx context.Context) {
	folder1 := root.NewPersistentInode(ctx, &fs.Inode{},
		fs.StableAttr{Mode: syscall.S_IFDIR})
	root.AddChild("folder1", folder1, true)
	subfolder1 := folder1.NewPersistentInode(ctx, &fs.Inode{},
		fs.StableAttr{Mode: syscall.S_IFDIR})
	folder1.AddChild("subfolder1", subfolder1, true)
	file1content := &fs.MemRegularFile{
		Data: []byte("Hello World"),
	}
	file1 := subfolder1.NewPersistentInode(ctx, file1content, fs.StableAttr{})
	subfolder1.AddChild("file1", file1, true)

	home := os.Getenv("HOME")
	loopbackRoot, err := fs.NewLoopbackRoot(home)
	if err != nil {
		log.Fatal(err)
	}

	subfolder2 := folder1.NewPersistentInode(ctx, loopbackRoot, fs.StableAttr{Mode: fuse.S_IFDIR})
	folder1.AddChild("subfolder2", subfolder2, true)
}

func main() {
	mntDir, _ := os.MkdirTemp("", "")
	root := &inMemoryFS{}

	// Mount the file system
	server, err := fs.Mount(mntDir, root, &fs.Options{
		MountOptions: fuse.MountOptions{Debug: true},
	})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Mounted on: %s\n", mntDir)
	fmt.Printf("Unmount by calling 'fusermount -u %s'\n", mntDir)

	// Serve the file system, until unmounted by calling fusermount -u
	server.Wait()
}

```

**Comment by hanwen** [comment]
I was puzzled by your report, but it is actually quite simple:

the loopback node computes its path relative to the root of the mount. Trying to access it, you get   

```
2024/08/29 11:29:19 /home/hanwen/folder1/subfolder2
```

which doesn't exist. I'd have to make the root of the loopback nodes tunable, so the root loopback node computes the path "/home/hanwen".

**Comment by hanwen** [comment]
https://review.gerrithub.io/c/hanwen/go-fuse/+/1200211

**Comment by nuwang** [comment]
Thanks very much for investigating and the fix. It worked after I changed my code from:
```
	home := os.Getenv("HOME")
	loopbackRoot, err := fs.NewLoopbackRoot(home)
	subfolder2 := folder1.NewPersistentInode(ctx, loopbackRoot, fs.StableAttr{Mode: fuse.S_IFDIR})
```
to
```
	home := os.Getenv("HOME")
	lnode := &fs.LoopbackNode{
		RootData: &fs.LoopbackRoot{
			Path: home,
		},
	}
	lnode.RootData.RootNode = lnode

	subfolder2 := folder1.NewPersistentInode(ctx, lnode, fs.StableAttr{Mode: fuse.S_IFDIR})
```

However, from a programming interface perspective, I find it a bit counter-intuitive. For example, why does one have to make the root node of the loopback node point to itself? And I would have expected something like `fs.NewLoopbackRoot(home)` to just work. It would be great if there's a simpler way to expose this to a library user.

Btw, is this the same issue? https://github.com/hanwen/go-fuse/issues/503

**Comment by hanwen** [comment]
yes, #503 is the same.

**Comment by hanwen** [comment]
> I would have expected something like fs.NewLoopbackRoot(home) to just work.

good point. Updated.

**Comment by hanwen** [comment]
submitted as 612c80e9b0f2eb7495205901747e87889a0bddcf
