### ISSUE TITLE
how to implement PassthroughFd if one file has multiple backing files

### ISSUE THREAD

**Issue by half-life666** [hanwen/go-fuse#528]
In the loop back example, PassthroughFd() simply return the backing file fd, and the fuse passthrough can work.

In our system, one file presented by fuse may have multiple backing files, sometimes the multiple backing files may cross different filesystems or different servers, so how to implement PassthroughFd() in this case? Does that mean fuse passthrough can not support this kind of file backing relation?

**Comment by hanwen** [comment]
In your case, you should not use passthrough.

**Comment by half-life666** [comment]
One more question, if one fuse file has one backing file, but the backing file is larger, so multiple fuse files may have same backing file. E.g., fuse file1 and file2 have same backing fileX, but at different offsets, how to implement PassthroughFd()? 

Does fuse passthrough support this case?

**Comment by half-life666** [comment]
Is there any documentation to explain the fuse passthrough pre requirements?

**Comment by rfjakob** [comment]
Best I could find when I looked are the commit messages in the linux kernel, I'll dig out the links

**Comment by rfjakob** [comment]
This and keep klicking "parent" for the other commits 

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4a90451bbc7f7fde94041fbb9ca96dd915069943

**Comment by half-life666** [comment]
> This and keep klicking "parent" for the other commits
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4a90451bbc7f7fde94041fbb9ca96dd915069943

Thanks
