### ISSUE TITLE
What's the proper way to unmount a go-fuse filesystem after a signal?

### ISSUE THREAD

**Issue by alberto-miranda** [hanwen/go-fuse#532]
We have been seeing problems with `server.Unmount()` spuriously returning `EBUSY` when our fs still has some pending requests to finalize. This is of course expected, but has led us to wonder whether the way we wrote the shutdown process is actually the best way to do it, or we are missing crucial details here. Our mounting/unmounting process works as per the (simplified) code below: 

```golang
func mount(mountPoint string) {

    server, fs := createFS(mountPoint)

    // Install signal handler for SIGTERM, and SIGINT
    signals.OnInterrupt(func() {
        log.Debug().Msg("termination signal received -- unmounting file system")
        if err := server.Unmount(); err != nil {
            log.Err(err).Msg("on file system unmount")
        }
    })

    log.Debug().Msg("FS server ready")
    server.Serve()
    log.Debug().Msg("FS server stopped")

    fs.Shutdown()
}
```

We basically do the following:
1. Create a server and filesystem instance
2. Install a signal handler for SIGTERM and SIGINT that calls `server.Unmount()` upon reception
3. Call `server.Serve()` to start the main FUSE loop
4. After the FUSE loop returns, execute all the required tasks for shutting down our filesystem.

This assumes that a successful call to `server.Unmount()` always unblocks the main FUSE loop started with `server.Serve()`. Is this assumption correct? Assuming it is, the code above then has the problem that if `SIGTERM -> server.Unmount()` fails (e.g. `EBUSY`) we are a bit at a loss about what to do: the fs cannot be unmounted, but we also cannot stop the main FUSE loop without a successful call to `server.Unmount()`. In short, I can't help but think there's an easier way to go about this that I'm not seeing...

**Comment by hanwen** [comment]
You can see the Unmount function here: https://sourcegraph.com/github.com/hanwen/go-fuse/-/blob/fuse/server.go?L127-129

The FUSE loops only exit if the kernel thinks the file system can be unmounted. So, if you have a process holding open a file in the mount, it will never unmount.

You can kill the mount forcefully through the fusectl file system.

**Comment by hanwen** [comment]
see https://review.gerrithub.io/c/hanwen/go-fuse/+/1201948 for documentation.
