### ISSUE TITLE
how to use passthrough for RawFileSystem

### ISSUE THREAD

**Issue by half-life666** [hanwen/go-fuse#534]
If the fuse is implemented using RawFileSystem interface, how to enable passthrough feature?

**Comment by hanwen-flow** [comment]
the fs API is implemented using RawFileSystem. Please see https://github.com/hanwen/go-fuse/blob/master/fs/bridge.go#L767

**Comment by hanwen** [comment]
please see the source code of the `fs/` library for an example,  https://github.com/hanwen/go-fuse/blob/master/fs/bridge.go#L767
