### ISSUE TITLE
Question: mount fuse and run command?

### ISSUE THREAD

**Issue by vsoch** [hanwen/go-fuse#536]
Hi again! I see in the api.go there is some description for how to run as a background process:

```go
//	go fssrv.Serve()
//	err = fssrv.WaitMount()
//	if err != nil {
//		...
//	}
```
But notably, fuse has its own mount function, and I don't see the serve used there. Is there an example or best practice for how to do this? I basically want to create the mount, and then execute a command with chroot. I mostly figured out how to do that in Go, but the problem is that the server (mount) is blocking. Thanks!

**Comment by vsoch** [comment]
It looks like it should be doing that here:

https://github.com/hanwen/go-fuse/blob/a442e4929d4431e1bc435fa934afe488163e082e/fs/mount.go

But then I'm not sure why I am not able to issue commands to the root after.

**Comment by hanwen** [comment]
all of the unittests run commands inside a fuse mount, so there is plenty of precedent. Are you sure you are not hitting one of deadlock scenarios that are documented? Also, when switching on debug, where is the hang occurring? If you interrupt with ^\, what does the stacktrace say?

**Comment by vsoch** [comment]
Thank you @hanwen ! I think there was something wrong with my environment - I restarted and was able to run the command. Now what happens is that I get a permission denied (even though the context is my PWD) and when I remove the read only, it freezes and I need to manually unmount. I'm wondering now (haven't tested yet) if the issue was placing the PWD at the mount root (where I wouldn't be allowed to run a command, even if it requites write)? I'm out and AFK and I can test things when I get back, if you have suggestions or an example to point to!

I do think we are close!

**Comment by hanwen** [comment]
it is hard to say something definite based on verbal descriptions. If you have code sample that doesn't work as expected, that would be helpful.

**Comment by vsoch** [comment]
I didn't have time this week but I should be able to make time this weekend (and point at code). Stay tuned and thanks again for the help.

**Comment by vsoch** [comment]
okay here is the error that I get:

```
$ ./bin/fs-gen /home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/xz --help
⭐️ Compatibility Filesystem (clib-fs)
Preparing to find shared libraries needed for [/home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/xz --help]
ld-linux-x86-64.so.2
liblzma.so.5
libc.so.6
Mount directory /tmp/compatlib4132045661
Mounted!
proot -r /tmp/compatlib4132045661 /home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/xz --help
2024/10/20 15:34:10 Error running command: operation not permitted
Cleaning up /tmp/compatlib4132045661...
panic: Error running command: operation not permitted

goroutine 1 [running]:
log.Panicf({0x575834?, 0xc00031c000?}, {0xc0000e1f08?, 0x1?, 0x1?})
        /usr/local/go/src/log/log.go:439 +0x65
main.main()
        /home/vanessa/Desktop/Code/compat-lib/cmd/fs/fs.go:71 +0x712
```

And the entrypoint is here:

https://github.com/compspec/compat-lib/blob/main/cmd/fs/fs.go

Note that the only change I have locally (to generate that error) is that the last lines 62 to 71 are uncommented.

**Comment by vsoch** [comment]
And for some context, the reason I want the application to see the mounted directory as the root `/` is because I want to write a function that will look for when it's trying to find a *.so path, and then intercept that call to return it more quickly from a cache. Sort of like an `LD_AUDIT` thing without `LD_AUDIT`.

**Comment by vsoch** [comment]
oh! It might be that the run command has too much extra stuff - if I keep it commented out and run this:

```bash
 proot -S /tmp/compatlib3121441156 /home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/xz --help
```
in a different terminal - it works! Let me see if I can reproduce that in go.

**Comment by vsoch** [comment]
woo!! It totally worked!!

![image](https://github.com/user-attachments/assets/0c6944ff-0974-42f5-bc4d-f3cc190a4f50)

Was my choice of proot args ok? I was reading here:

https://github.com/proot-me/proot/blob/master/doc/proot/manual.rst

And I chose `-S` with `-0`

This is so cool! :sunglasses:

**Comment by hanwen** [comment]
I don't completely follow. For the problem with "operation not permitted", I recommend using the Debug option in Go-FUSE. This will let you see exactly where the EPERM error is generated. 

if your problem is resolved, can you close this issue?

**Comment by vsoch** [comment]
Yes it's resolved - sorry I didn't say that explicitly. I am happy to close the issue. Thanks!
