### ISSUE TITLE
How to get the real UID from context (Caller)

### ISSUE THREAD

**Issue by shreyaspg** [hanwen/go-fuse#540]
The FromContext() method that provides Caller struct has the Owner UID, the UID returned by this method is the effective UID. Is there a way to get the real UID from go-fuse, I took a like libfuse fuse_context and could not find anything on this too. Is this possible from FUSE itself, or is this something that needs to be implemented. 

For context, I want to know which UID is accessing the filesystem, but any user with sudo su can change the effective UID.

Any help on this would be great, Thank you.

**Comment by hanwen** [comment]
The `Caller` struct is all we get from the kernel. If you feel adventurous, you can take the PID and see if you can find something in `/proc/$PID` that answers your question.
