### ISSUE TITLE
Buffers allocated from the Pool are never freed

### ISSUE THREAD

**Issue by darthShadow** [hanwen/go-fuse#542]
I must be missing something, but it looks like with this change (https://github.com/hanwen/go-fuse/commit/9c6a577cfc191231c501699934aafdaec8255337), the buffer is never returned to the pool, because `bufferPoolOutputBuf` is always nil.

I have attached a flamegraph with v2.6.3 of the library where 12 GB from the current 16 GB of the app usage is due to go-fuse in the `handleRequest` function.
[rclone.heap.zip](https://github.com/user-attachments/files/17784280/rclone.heap.zip)

**Comment by hanwen** [comment]
hi, that looks like an oversight. Let me look into this.

**Comment by hanwen** [comment]
I tagged v2.7.0 for this.

**Comment by darthShadow** [comment]
Thanks for the quick fix.
