### ISSUE TITLE
How to get file descriptor (identifier) from loopbackFile in Flush?

### ISSUE THREAD

**Issue by vsoch** [hanwen/go-fuse#543]
Hi! I'm trying to make a direct association between an Open and Close (Flush) on the file, and I was looking to the file descriptor to do that. For the Open call in loopback, I can easily get back the call to syscall Open:
```go
	fd, err := syscall.Open(p, int(flags), 0)
```

But for Flush, which takes the FileHandle, which is a loopbackFile https://github.com/hanwen/go-fuse/blob/aff07cbd88fef6a2561a87a1e43255516ba7d4b6/fs/files.go#L21 

I don't see any way to get the underlying (private) fd (int).

https://github.com/hanwen/go-fuse/blob/master/fs/files.go

My only idea is to try re-creating the entire loopbackFile type to have that be easily accessible, but I'm hoping there is a simpler way I'm missing. Thank you!

**Comment by hanwen** [comment]
> I'm trying to make a direct association between an Open and Close (Flush) on the file, 

not sure what you mean here. As an alternative, you can make your own type but it is a bit messy, 

```
type AllFileOps interface {
  fs.FileReader
  fs.FileWriter
  fs.FileFlusher
...
}
type wrapperFile struct {
   AllFileOps
}

..

fh := &wrapperFile{
  AllFileOps: loopbackFile.(AllFileOps)
}
```

then you can store the fd separately in the wrapperFile. You need to dup() the file descriptor to avoid races, though.

**Comment by vsoch** [comment]
> you have to take care that a Flush operation cannot occur in parallel to any other operation that involves the Fd, or you risk a race condition (after close, the Fd may be reused for a different file.)

If the implication is calling flush as the developer - I wouldn't do any extra calls or operations on the descriptor. I'd just want to get the integer number for it to identify it.

**Comment by vsoch** [comment]
And how could I even reference loopbackFile if it's private? I don't think this would work:

```
AllFileOps: loopbackFile.(AllFileOps)
```

**Comment by hanwen** [comment]
> And how could I even reference loopbackFile if it's private? I don't think this would work:.

```
lf := NewLoopbackFile()

...
lf.(AllFileOps)
```

**Comment by vsoch** [comment]
Yes, it works to transform the output of Open into that interface, e.g.,:

```go
loopbackFile := fs.NewLoopbackFile(fd)
fh := &wrapperFile{
	AllFileOps: loopbackFile.(AllFileOps),
}
```
And then, let's say, I add a custom field for the Id that I need.

```go
type wrapperFile struct {
	AllFileOps
	Fid int
}
```
And set it:

```go
	fh := &wrapperFile{
		AllFileOps: loopbackFile.(AllFileOps),
		Fid:        fd,
	}
```

In close (Flush) I want to retrieve that identifier. But the `fh fs.FileHandle` type doesn't match wrapper file, I can't do this:

```
// Flush is called for the close(2) call, could be multiple times. See:
// https://github.com/hanwen/go-fuse/blob/aff07cbd88fef6a2561a87a1e43255516ba7d4b6/fs/api.go#L369
func (n *LoopbackNode) Flush(ctx context.Context, fh fs.FileHandle) syscall.Errno {
	p := n.path()
	logger.LogEvent("Close", p)
	return 0
}

```

What I'd need to be able to do is receive the wrappedFile, that has the Fid at the top level:

```go
// Flush is called for the close(2) call, could be multiple times. See:
// https://github.com/hanwen/go-fuse/blob/aff07cbd88fef6a2561a87a1e43255516ba7d4b6/fs/api.go#L369
func (n *LoopbackNode) Flush(ctx context.Context, fh wrapperFile) syscall.Errno {
	p := n.path()
	logger.LogEvent("Close", p)
	fmt.Println(fh)
	return 0
}
```
And that results in the error that I showed above:

```console
pkg/fs/record/loopback.go:24:26: cannot convert (*LoopbackNode)(nil) (value of type *LoopbackNode) to type "github.com/hanwen/go-fuse/v2/fs".NodeFlusher: *LoopbackNode does not implement "github.com/hanwen/go-fuse/v2/fs".NodeFlusher (wrong type for method Flush)
                have Flush(context.Context, wrapperFile) "syscall".Errno
                want Flush(context.Context, "github.com/hanwen/go-fuse/v2/fs".FileHandle) "syscall".Errno
make: *** [Makefile:19: build] Error 1
```
High level - we know Open happens before Close, and Open does the actual syscall that gives us the underlying File descriptor. All I need is to to have that identifier in the close function - not to act or manipulate it, but to link the open call with a specific close call.

**Comment by hanwen** [comment]
```
func (n *LoopbackNode) Flush(ctx context.Context, fh fs.FileHandle) syscall.Errno {
   wf := fh.(*wlappedFile)
```

**Comment by vsoch** [comment]
That's perfect!

![image](https://github.com/user-attachments/assets/b97ca9e1-ffee-4b78-b64e-4b20dcb3f2c8)

I can now make an exact association between an Open and Flush call. Thank you so much for your help and patience - let's close the issue! :partying_face:
