### ISSUE TITLE
MacOs cannot mount

### ISSUE THREAD

**Issue by sceneryback** [hanwen/go-fuse#544]
Always failed with 'request output buffer too small: code 52, sz 288 + 16 &{STATX 0x1009c1b50 64 288 ', from code, it seems size of some internal definitions are not matched :
```
	var r requestAlloc
	sizeOfOutHeader := unsafe.Sizeof(OutHeader{})
	for code, h := range operationHandlers {
		if h.OutputSize+sizeOfOutHeader > unsafe.Sizeof(r.outBuf) {
			log.Panicf("request output buffer too small: code %v, sz %d + %d %v", code, h.OutputSize, sizeOfOutHeader, h)
		}
	}
```

OS: MacOS 15.1

**Comment by hanwen** [comment]
oops!

Can you see if https://review.gerrithub.io/c/hanwen/go-fuse/+/1204326 fixes it for you?

Download it using `git fetch https://review.gerrithub.io/hanwen/go-fuse refs/changes/26/1204326/1 && git checkout FETCH_HEAD`

**Comment by hanwen** [comment]
actually, i found a small problem. Can you try `git fetch https://review.gerrithub.io/hanwen/go-fuse refs/changes/26/1204326/2 && git checkout FETCH_HEAD` ?

**Comment by sceneryback** [comment]
hi @hanwen I updated my MacOS to 15.1.1  and installed MacFuse (https://macfuse.github.io/), now the error disappears but new errors appears like:
```
024/11/21 11:51:00 rx 2: ACCESS n1 {u=501 g=20 x} p3307
2024/11/21 11:51:00 Getattr called
2024/11/21 11:51:00 Stat for xxx: Size=4096, ModTime=2024-11-18 14:30:56.711586747 +0800 CST, Mode=2147484150
2024/11/21 11:51:00 tx 2:     13=permission denied
```
Maybe it is not a good idea to test on MacOS, I will go to ubuntu to test. Thanks anyway!
