### ISSUE TITLE
Allow setting max_stack_depth for PASSTHROUGH on stacked FS

### ISSUE THREAD

**Issue by darthShadow** [hanwen/go-fuse#548]
References:

https://github.com/libfuse/libfuse/pull/919/files#diff-c8a29b534dd72a12f2799f6b6845f54f1b700218dc52742879f6583e54ef3cfeR617-R631

```
	 * When FUSE_CAP_PASSTHROUGH is enabled, this is the maximum allowed
	 * stacking depth of the backing files.  In current kernel, the maximum
	 * allowed stack depth if FILESYSTEM_MAX_STACK_DEPTH (2), which includes
	 * the FUSE passthrough layer, so the maximum stacking depth for backing
	 * files is 1.
	 *
	 * The default is FUSE_BACKING_STACKED_UNDER (0), meaning that the
	 * backing files cannot be on a stacked filesystem, but another stacked
	 * filesystem can be stacked over this FUSE passthrough filesystem.
	 *
	 * Set this to FUSE_BACKING_STACKED_OVER (1) if backing files may be on
	 * a stacked filesystem, such as overlayfs or another FUSE passthrough.
	 * In this configuration, another stacked filesystem cannot be stacked
	 * over this FUSE passthrough filesystem.
```

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6ce8b2ce0d7e3a621cdc9eb66d74436ca7d0e66e

```
+			 * max_stack_depth is the max stack depth of FUSE fs,
+			 * so it has to be at least 1 to support passthrough
+			 * to backing files.
+			 *
+			 * with max_stack_depth > 1, the backing files can be
+			 * on a stacked fs (e.g. overlayfs) themselves and with
+			 * max_stack_depth == 1, FUSE fs can be stacked as the
+			 * underlying fs of a stacked fs (e.g. overlayfs).
```

https://github.com/libfuse/libfuse/blob/8b34ed03682bb7806a6083b05187c4fc5475a135/lib/fuse_lowlevel.c#L2219-L2225

```
	if (se->conn.want & FUSE_CAP_PASSTHROUGH) {
		outargflags |= FUSE_PASSTHROUGH;
		/*
		 * outarg.max_stack_depth includes the fuse stack layer,
		 * so it is one more than max_backing_stack_depth.
		 */
		outarg.max_stack_depth = se->conn.max_backing_stack_depth + 1;
```

**Comment by hanwen** [comment]
v2.7.2

I am curious to hear how is passthrough is working for you. Cheers!

**Comment by darthShadow** [comment]
It's been working very well for reads (speeds have improved in the range of 4x to 6x on average).

Just trying to track down a bug with writes which is causing the files to be empty when passed through. It's probably due to opening the file with the wrong set of flags, but if you have any suggestions, I would appreciate it.

Related commit:

https://github.com/darthShadow/rclone/commit/dd0dd5d552255c8afe82f40f2d01fd54be9ccf65

Relevant changes:

https://github.com/darthShadow/rclone/commit/dd0dd5d552255c8afe82f40f2d01fd54be9ccf65#diff-d3bb03570d3c8f1cdf32e2295274338d83f6e8a5d76ef3867e30f53503b96cc1R509-R529

https://github.com/darthShadow/rclone/commit/dd0dd5d552255c8afe82f40f2d01fd54be9ccf65#diff-fe543a28063304d1af50403b09c86822662b61e5323a7624d1a64d4ecd9f172bR1665-R1673

**Comment by hanwen** [comment]
i can't remember from the top of my head if I tested that, but it should be easy to add to the go-fuse test (TestPassthrough under fs/)

**Comment by darthShadow** [comment]
Yeah, the example seems to be working fine so I guess it's an issue with how rclone deals with writes.

Will figure it out, thanks.
