### ISSUE TITLE
os.getcwd failed within mounted path, how to fix it?

### ISSUE THREAD

**Issue by chewaiwai** [hanwen/go-fuse#550]
Reproduce Steps:

1. mount a path as fuse mount-point
2. use mkdir to create a sub directory in the mount-point
3. use cd into that new created sub directory
4. execute "python3" to enter python interpreter
5. in python interpreter, execute "import os" and "os.getcwd()" sequentially
6. check the output, will get the error message as below:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory"

**Comment by lingyun-tos** [comment]
I also encountered the same issue

**Comment by rfjakob** [comment]
Is this with the loopback example?

**Comment by hanwen** [comment]
If you run with DEBUG, you can observe the call which returns errno 2 (ENOENT). It's hard to say more without more info, but typically you have a bug in your Getattr or Lookup implementation.

**Comment by chewaiwai** [comment]
Actually, there is no errno 2 (ENOENT) observed in debugging mode. If I use python to execute a script "os.getcwd()" directly, will also get this issue.

You mentioned this might be a bug in my Getattr/Lookup implementation. Do you know which attributes will cause this issue most likely？e.g the implementation for Getattr is just like:
![image](https://github.com/user-attachments/assets/1e3d26f4-f21e-4bf9-a2d9-386339af7eb1)

**Comment by rfjakob** [comment]
Another idea: missing "." or ".." in directory listings?

**Comment by chewaiwai** [comment]
@rfjakob "." and ".." are also include in directory listings.

![image](https://github.com/user-attachments/assets/659005dd-72d9-4664-a213-62d199cce1cc)

And, in debugging mode, no errno 2 (ENOENT) observed. But I can notice another error message(I don't know if this is related): "inappropriate ioctl for device"

![image](https://github.com/user-attachments/assets/d1ff742b-c250-4767-accd-51dcf73cd2af)

**Comment by chewaiwai** [comment]
Finally, I find the way. After I add the codes as below in the implementation for Lookup, this issue is fixed.
![image](https://github.com/user-attachments/assets/becf8098-c4f1-4186-8631-eb84e2f3dd90)

And another question is why this works?

**Comment by hanwen** [comment]
Lookup must also return nodes that have previously been looked up already (including implicit lookups through mkdir).
