### ISSUE TITLE
 How to enable asynchronous for fuse

### ISSUE THREAD

**Issue by TanCharles** [hanwen/go-fuse#551]

**Comment by hanwen** [comment]
Needs more info. I have no idea what you're asking about.

**Comment by TanCharles** [comment]
Sorry, I want to ask how do I enable writeback_cache because I don't see it in the options to set this parameter

**Comment by TanCharles** [comment]
I am very sorry that I did not make my meaning clear. What I meant was that fuse writes IO, can it be carried out concurrently, instead of waiting for the last IO to finish and then processing the next IO

**Comment by hanwen** [comment]
I think you want this https://github.com/hanwen/go-fuse/issues/449 . 

There is an open change but the author went AWOL after I reviewed it.

**Comment by TanCharles** [comment]
Thank you very much for your help. It was very useful to me

**Comment by trapexit** [comment]
I don't believe writeback caching is what the OP is asking about. I think the OP needs to be a lot more specific about what they are asking though. Do you mean writes to a single file or across multiple files? In directio mode or page cached mode? Do you mean the FOPEN_PARALLEL_DIRECT_WRITES feature?
