### ISSUE TITLE
Concurrent reads on a single file do not work

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#64]
When writing a test case to catch race conditions in gocryptfs, I noticed that read and write operations on a single file seem to be serialized.

The test case is simple, just insert a 1 second sleep at the top of `loopbackFile.Read()` at [files.go#L121](https://github.com/hanwen/go-fuse/blob/master/fuse/nodefs/files.go#L121) to make the issue more visible. Mount loopback to `mnt`. Then,

    echo a > mnt/a
    time ( cat mnt/a & cat mnt/a & wait )

Result: 2 seconds
Expected: 1 second

I tested this against [cluefs](https://github.com/airnandez/cluefs), that uses bazil-fuse as the backend library. Cluefs shows the expected 1 second runtime on the read test.

On writes, however, cluefs serializes just like go-fuse. This makes me wonder if this is a limitation in the FUSE protocol? The write test is just

    time ( echo 1 >> mnt/a & echo 2 >> mnt/a & wait )

It takes 2 seconds instead of the expected one second.

**Comment by hanwen** [comment]
when I do this, I get

2015/10/14 09:13:32 Dispatch: OPEN, NodeId: 3. data: {O_RDONLY,0x8000} 
2015/10/14 09:13:32 Serialize: OPEN code: OK value: {Fh 2 }
2015/10/14 09:13:32 Dispatch: OPEN, NodeId: 3. data: {O_RDONLY,0x8000} 
2015/10/14 09:13:32 Serialize: OPEN code: OK value: {Fh 3 }
2015/10/14 09:13:32 Dispatch: READ, NodeId: 3. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000} 
2015/10/14 09:13:33 Serialize: READ code: OK value:  4096 bytes data (fd data)
2015/10/14 09:13:33 Dispatch: READ, NodeId: 3. data: {Fh 2 off 0 sz 4096  L 0 RDONLY,0x8000} 

Note how the same Fh is used for both reads. 

FWIW, if you are looking for race conditions, the race detector is the best tool.

**Comment by rfjakob** [comment]
Interesting. The opens return fh 2 and 3 but the reads use both fh 2.

Is this kernel caching kicking in? I will have to check if cluefs uses
direct_io.

The race involves an on disk rmw cycle with somebody else writing to the
same file, but maybe the race detector can still help me. Will check.

**Comment by rfjakob** [comment]
I have tested this with the libfuse example loopback filesystems (`fusexmp` and `fusexmp_fh`). Both show the same behavoir. This just seems to be how the kernel schedules the operations and not an issue in go-fuse.
