### ISSUE TITLE
No input buffer for writes in Open() Pathfs

### ISSUE THREAD

**Issue by ShashankYadav** [hanwen/go-fuse#65]
I am trying to write to a fuse filesystem mounted using pathFS. From what I have seen till now, Open() callback is being called for reading as well as writing. However how is the input data buffer coming in case for write to Open() callback of PathFS .

It is possible to know whether the callback is for read or write using the flags in Open's parameters but I cannot find the buffer which has the data inputted by the user.

Any help is appreciated.

**Comment by hanwen** [comment]
the data comes as argument for the Read or Write callbacks on the file you return from Open.
