### ISSUE TITLE
unionfs self tests fail on Linux 4.1+

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#67]
Running `go test ./...` returns two failed tests:

```
FAIL: TestExplicitScan (0.02s)
	autounion_test.go:218: Should have workspace backing1: lstat /tmp/099791821/mnt/backing1: no such file or directory
```

```
FAIL: TestUnionFsDropDeletionCache (0.08s)
	unionfs_test.go:1039: Lstat() should have succeeded lstat /tmp/unionfs311629328/mnt/file: no such file or directory
```

It seems to be like that for a long time, commit f108ee9684c2556c66bbadfdfb3340da4d082754 from january already has these failures.

Full test log: https://gist.github.com/rfjakob/3955b67502299894a66a

**Comment by hanwen** [comment]
it's strange. all.bash runs the unionfs tests, and I seem to recall having run them with some frequency. Maybe this relates to the kernel version?

**Comment by rfjakob** [comment]
Indeed. This or the Go version.
* Kernel 4.1.0, Go 1.5.1 (stock Fedora Core 22): FAIL
* Kernel 3.16.0, Go 1.3.3 (stock Debian Jessie): PASS

**Comment by rfjakob** [comment]
Ok, seems to be the kernel. The go version does not make a difference:
* Kernel 4.1.0, Go 1.3.3: FAIL
* Kernel 3.16.0, Go 1.5.1: PASS

**Comment by rfjakob** [comment]
I am on 4.2.5 now (Fedora 23) and the error is gone. `all.bash` comes back clean. 
Closing the ticket.
