### ISSUE TITLE
Could not find fusermount binary: exec: "/bin/bin/fusermount"

### ISSUE THREAD

**Issue by saviola777** [hanwen/go-fuse#69]
Hello,

while compiling a project using go-fuse, I got the following error

```
Could not find fusermount binary: exec: "/bin/bin/fusermount": stat /bin/bin/fusermount: no such file or directory
```

which seems to have been introduced in 41b8187, more precisely [here](https://github.com/hanwen/go-fuse/commit/41b8187f5b1cd7af28a1a04cad50405c2dd5a5e9#diff-d6e2252063449448a2da84ca76cd6441R138). It looks for "/bin/fusermount", which it can't find since I don't have "/usr" in my PATH.

**Comment by hanwen** [comment]
where is your fusermount binary?

**Comment by saviola777** [comment]
It's in ```/usr/bin/fusermount```, and ```/usr/bin``` is in my PATH.

**Comment by rfjakob** [comment]
Oh, sorry about that! The hardcoded `/bin/fusermount` path should not have made it into the patch.

@hanwen Github does not send out notifications for comments on commits https://github.com/hanwen/go-fuse/commit/41b8187f5b1cd7af28a1a04cad50405c2dd5a5e9 , I would have fixed this sooner. I guess you could reference me using `@rfjakob`, that would trigger an email to me.
