### ISSUE TITLE
build error on mac 

### ISSUE THREAD

**Issue by vChrysanthemum** [hanwen/go-fuse#78]
# github.com/hanwen/go-fuse/fuse/nodefs
../github.com/hanwen/go-fuse/fuse/nodefs/files_darwin.go:5: imported and not used: "time"
../github.com/hanwen/go-fuse/fuse/nodefs/syscall.go:11: undefined: syscall.SYS_UTIMENSAT

**Comment by alexmojaki** [comment]
+1

The problematic callis:

    syscall.Syscall6(syscall.SYS_UTIMENSAT, uintptr(fd), 0, uintptr(unsafe.Pointer(times)), uintptr(0), 0, 0)

I'm assuming that this is the file being used:

https://golang.org/src/syscall/syscall_bsd.go

`SYS_UTIMENSAT` indeed isn't defined but there seems to be a function that can help at line 509:

```
   509	func UtimesNano(path string, ts []Timespec) error {
   510		// TODO: The BSDs can do utimensat with SYS_UTIMENSAT but it
   511		// isn't supported by darwin so this uses utimes instead
```
