### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [hanwen/go-fuse#85]
(Not a PR due to CLA -> Google Account -> failed signup over Tor.)

```go
$ go get github.com/hanwen/go-fuse/fuse
.go/src/github.com/hanwen/go-fuse/fuse/types.go:351: undefined: Attr
```
and lots of similar errors can be fixed by copying from:
- attr_darwin.go
- print_linux.go + `s/\.O_LARGEFILE/_O_LARGEFILE/`
- request_linux.go
- server_darwin.go
- splice_darwin.go
- syscall_linux.go
- types_linux.go
- pathfs/loopback_darwin.go

```go
.go/src/github.com/hanwen/go-fuse/fuse/server.go:96: undefined: unmount
.go/src/github.com/hanwen/go-fuse/fuse/server.go:181: undefined: mount
```
FreeBSD uses libfuse but not fusermount binary. Instead, the library [calls](http://sourceforge.net/p/fuse/fuse/ci/fuse_2_9_4/tree/lib/mount_bsd.c) [mount_fusefs(8)](https://man.freebsd.org/mount_fusefs/8) with *special* argument obtained via `open("/dev/fuse", ...)`. Playing with `syscall.Dup()` was enough for mounting to succeed but any VFS operation still **hangs**.

Regular users only need to `sysctl vfs.usermount=1` before mount/umount.

```go
.go/src/github.com/hanwen/go-fuse/fuse/types.go:24: undefined: syscall.ENODATA
```
[NetBSD folks](https://mail-index.netbsd.org/tech-kern/2012/04/30/msg013090.html) had an interesting discussion. OS X may unintentionally use ENODATA for unionfs here despite it's never returned.

http://fxr.watson.org/fxr/ident?v=xnu-2050.18.24&i=ENODATA
http://fxr.watson.org/fxr/ident?v=xnu-2050.18.24&i=ENOATTR

```go
$ go get github.com/hanwen/go-fuse/zipfs
.go/src/github.com/hanwen/go-fuse/fuse/nodefs/files.go:96: cannot use loopbackFile literal (type *loopbackFile) as type File in return argument:
        *loopbackFile does not implement File (missing Allocate method)
.go/src/github.com/hanwen/go-fuse/fuse/nodefs/syscall.go:11: undefined: syscall.SYS_UTIMENSAT
```
- FreeBSD and NetBSD lack fallocate(2) but have posix_fallocate(2) i.e., `syscall.SYS_POSIX_FALLOCATE`
- FreeBSD and DragonFly only [recently](https://github.com/freebsd/freebsd/commit/67db24d0f2b81a222335fe5bb13977ef0c2258a9) [added](https://github.com/DragonFlyBSD/DragonFlyBSD/commit/a89c839da6c9bff9e25c3e8638b8292762211a71) utimensat(2) support thus missing in `syscall` package

**Comment by hanwen** [comment]
I don't have a freebsd machine, so I won't be apply this.

I need a CLA for accepting changes; sorry.

**Comment by hanwen** [comment]
Please reopen when you have a patch and have signed the CLA.

**Comment by rnkn** [comment]
What is the best way around this CLA problem?

If the issue is that the CLA is hosted on the Google platform, would it be best to move it to a non-Google platform to allow regular non-Google-people to contribute? Or (and I suspect more likely) if the CLA itself is the issue, can this be given some [further consideration][1], and failing that, can the project be forked and remove the requirement for a CLA?

[1]: https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html

**Comment by hanwen** [comment]
The CLA can be signed by anybody, provided their employer is OK with it. It does not require someone to be "Google-people".

The link you point to is written from the perspective of a well-willing contributor, but unfortunately contributors (or their employers) are not always well-willing.  The CLA protects us against these people.

See https://opensource.google.com/docs/cla/policy/ for an in-depth discussion of what the CLA is. and why we require it. The case book (https://google.github.io/opencasebook/) has further legal analysis of the relevant topics, which you may find interesting.

It goes without saying that you are free to fork this project and go crazy (within the terms of the license) with it.

**Comment by rnkn** [comment]
> The CLA can be signed by anybody, provided their employer is OK with 
> it. It does not require someone to be "Google-people".

I tried following the link but it requires a Google account sign in. 
Only Google-people may pass. Resistence is futile. etc. etc. Luckily I 
made it back alive.

> The link you point to is written from the perspective of a 
> well-willing contributor, but unfortunately contributors (or their 
> employers) are not always well-willing.  The CLA protects us against 
> these people.

This is probably just theoretical, because from the looks of above, the 
issue @jbeich has is not the CLA per se but access to it. Could you 
maybe have a Google form/spreadsheet thing for people (both Google and 
normal) to fill out?

> See https://opensource.google.com/docs/cla/policy/ for an in-depth 
> discussion of what the CLA is. and why we require it. The case book 
> (https://google.github.io/opencasebook/) has further legal analysis of 
> the relevant topics, which you may find interesting.

That CLA looks like it's for contributing to Google's code... but 
https://github.com/hanwen/go-fuse#disclaimer says go-fuse is not Google 
code....?

My only interest is really just that go-fuse work on BSD....

**Comment by hanwen** [comment]
It is likely that a Google Form would also require you to sign in with a google account. .

If you are concerned about privacy implications of using a Google account, you could use an incognito tab to create an account. Then again, if you are concerned about privacy, you should probably not record your name and email address in a version control log that is public and retained indefinitely in the first place.

**Comment by hanwen** [comment]
regarding https://github.com/hanwen/go-fuse#disclaimer

go-fuse is written by me, and I work for Google, which makes it copyrighted by Google.  It is not a Google product, in the sense that it has no dedicated staffing.

**Comment by rfjakob** [comment]
> says go-fuse is not Google code....?

AFAIK go-fuse is produced in part on Google company time. The disadvantage is that it must use Google's legal framework. The advantage is that go-fuse *exists*.

I'm pretty okay with that tradeoff.

**Comment by rnkn** [comment]
> If you are concerned about privacy implications of using a Google 
> account, you could use an incognito tab to create an account. Then 
> again, if you are concerned about privacy, you should probably not 
> record your name and email address in a version control log that is 
> public and retained indefinitely in the first place. 

It's more for the OP wishing to contribute.

**Comment by hanwen** [comment]
Is @jbeich in Iran, Syria, North Korea which would preclude them having a google account? If no, I suggest they switch off TOR for signing the CLA.

**Comment by rnkn** [comment]
> Is @jbeich in Iran, Syria, North Korea which would preclude them 
> having a google account? If no, I suggest they switch off TOR for 
> signing the CLA.

Hahah so the only legit reason not to have a Google account is if you're 
living in Syria.... I have no idea what the story is, but I'm sure they 
have their reasons.

We're not programs Gerty, we're people.

**Comment by rfjakob** [comment]
I'm not sure this discussion is leading anywhere. It will certainly not lead to google changing their legal framework.

**Comment by rnkn** [comment]
Just trying to find a pragmatic solution/middle-ground.
