### ISSUE TITLE
Improve small-file performance

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#90]
`tar xzf linux-3.0.tar.gz` is my canonical small-file benchmark. The loopback example takes 2x the time compared to EncFS. 

Looking at the cpu profile, this is caused by heavy GC activity that originates in go-fuse. For each created file, an inode object is allocated. Recycling inode objects could reduce GC pressure considerably.

(github does not allow SVG attachments. Attaching as PNG and [PDF](https://github.com/hanwen/go-fuse/files/85116/c.pdf))
![c](https://cloud.githubusercontent.com/assets/286847/12223169/89010e48-b7d0-11e5-8029-9b952f0e61ac.png)

**Comment by rfjakob** [comment]
Memory profile: [mem.pdf](https://github.com/hanwen/go-fuse/files/85117/mem.pdf)

I will try to implement a sync.Pool `fuse/nodefs.(*Inode).NewChild` unless you see another way.

**Comment by hanwen** [comment]
I'm suspicious of this explanation, but if you want to try and benchmark,
be my guest.

**Comment by rfjakob** [comment]
Indeed that was not the reason. It was just a typo that caused half of the read buffers not to be returned to readPool, please check pull request #91.

The memory profile with `--alloc_space` clearly showed the problem, the earlier memory profile I posted is actually irrelevant.
