### ISSUE TITLE
Missing copyrights or who owns the code?

### ISSUE THREAD

**Issue by jbeich** [hanwen/go-fuse#94]
The license is confusing:
- only one copyright holder in LICENSE despite /graphs page showing more
- no AUTHORS files to list contributers under an umbrella copyright holder e.g., Go Authors
- no license header in individual files listing copyright(s) of contributors e.g., for inherited code before CLA was established
- README and CONTRIBUTING don't agree on affiliation to Google: Why a CLA from an entity that doesn't hold a copyright in the project matters?

```sh
$ git grep -F Copyright
LICENSE:// Copyright (c) 2010 Ivan Krasin (imkrasin@gmail.com). All rights reserved.
fuse/mount_darwin.go:// Copyright 2011 The Go Authors.  All rights reserved.
fuse/mount_darwin.go://         Copyright (c) 2006 Russ Cox
```

**Comment by hanwen** [comment]
* I've added license headers to the files. 

* mount_darwin has been rewritten since 

* ivan krasin was a Google employee at the time his FUSE library was written. His name should have never been there in the LICENSE file in the first place.

I'll see what's involved in setting up AUTHORS files.

**Comment by hanwen** [comment]
added AUTHORS file too.
