### ISSUE TITLE
pathInode.Truncate and friends ignore `file` argument

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#95]
For example, https://github.com/hanwen/go-fuse/blob/master/fuse/pathfs/pathfs.go#L666 . The passed `file` argument is ignored and instead it uses a random (?) file handle.

This sometimes picks a file handle that is already closed when [gocryptfs](https://nuetzlich.net/gocryptfs/) handles the truncate request, leading to unneccessary error messages and a general sense of "how the heck can this even happen" at yours sincerly.

Is there a reason for not using `file` or are you ok if I fix this?

**Comment by hanwen** [comment]
if the file is specifiied, it's probably better to use it, so yes, a fix would be welcome.

The code that picks a random file is trying to do something intelligent, in case somebody truncates a file using truncate(), while it is being opened as a handle as well.
